### ISSUE TITLE
[SEO] Метрика РСХБ

### ISSUE THREAD

**Issue by KazakovaLena** [redneckz/wildless-cms-uni-blocks#1105]
Нужно поставить на сайте основной счетчик метрики РСХБ 

Код:

<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();
   for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
   k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(30456412, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true,
        trackHash:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/30456412" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

**Comment by Mikage777** [comment]
Добавлен код второй метрики. Ид метрики захардкожен.
