### ISSUE TITLE
[Uni Blocks, Svoe] Рефакторинг блока Tile

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1112]
Необходим рефакторинг Tile, чтобы можно было:
- менять позиционирование картинки (слева/справа/сверху/по центру + возможность сместить ее к краю блока)
- сделать карточки кликабельными (предусмотреть для этого либо поле в настройках блока для ввода URL либо зашить ссылку в коде на первое время)

![Image](https://user-images.githubusercontent.com/112703510/210063833-ea87099f-3b05-4612-a213-2b56f7fc3e96.png)

![Image](https://user-images.githubusercontent.com/112703510/210063868-d4966c94-97e7-420b-9094-e474fff34378.png)

_Скрин. Вид плиток для Экосистемы ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=9373%3A828021&t=la8nDlYITvZn16UI-4))_

**Comment by Longraf** [comment]
После исследования выяснилось что существующий блок TIle и дизайн этого блока кардинально отличаются. 
Отличия: Структура HTML, внешние отступы, отступы между компонентами, размеры шрифтов. Принято решение реализовывать кастомный блок для экосистемы Своё

**Comment by Longraf** [comment]
Так же макет сделан под разрешение 1920px при уменьшении размера непонятно как должна выглядеть страница. Размер компонентов с нынешним flow макетом сделать в "процентах" возможности нет.
![image](https://user-images.githubusercontent.com/32570545/210748697-c72ae2fd-44d6-4f5c-bdee-a39caace0250.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
