### ISSUE TITLE
[Uni Blocks, Svoe] Доработка блока Recommendation

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1114]
Необходимо в настройках блока Recommendation сделать следующее:
- добавить в поле "Цвет карточек" (реализация поля в рамках отдельной задачи [#800](https://github.com/redneckz/wildless-cms-uni-blocks/issues/800)) в дропдаун еще одно значение - "Серый" (вид серых карточек как на Скрине ниже)

![Image](https://user-images.githubusercontent.com/112703510/210067070-6e66dba2-c28d-46e2-aae0-2be90fb7a856.png)
_Скрин. Вид блока с серыми карточками ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=9373%3A829822&t=OwM1nXUWxZURZnjE-4))_

**Comment by SergeyPilipenko** [comment]
Проверено в даталайне 2.3.44-beta, блок Карточка рекоммендаций
