### ISSUE TITLE
[Uni Blocks, Svoe] Разработка кастомного блока на основе CarouselProductCard

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1115]
Необходимо реализовать кастомный блок как на _Скрине 1_ ниже со следующими настройками (Скрин 2):
- **Заголовок блока**
  - название поля: "Заголовок"
  - тип компонента: текстовое поле
  - значение по умолчанию: "Заголовок"
- **Описание блока**
  - название поля: "Описание"
  - тип компонента: текстовое поле
  - значение по умолчанию: "Описание"
- **Изображение**
  - можно загрузить свою картинку или выбрать иконку из списка
- Кнопка
  - **Текст**
    - название поля: "Текст"
    - тип компонента: текстовое поле
    - значение по умолчанию: "Кнопка"
  - **URL**
    - название поля: "URL"
    - тип компонента: текстовое поле
    - значение по умолчанию: null
  - **Таргет**
    - название поля: "Таргет"
    - тип компонента: дропдаун
    - значение по умолчанию: null
- **Цвет блока**
  - название поля: "Цвет блока"
  - тип компонента: дропдаун
  - возможные значения:
    - Второстепенный (=желтому как на _Скрине 1_)
  - значение по умолчанию: "Второстепенный"
- Стиль
  - нет ограничений по ширине блока

![Image](https://user-images.githubusercontent.com/112703510/210070901-031e6cd9-26c8-4bc3-814c-d0f47fc108db.png)
_Скрин 1. Вид блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=9373%3A828021&t=OwM1nXUWxZURZnjE-4))_

---

![Image](https://user-images.githubusercontent.com/112703510/210070912-05bb6f19-2fce-4375-be51-405b0ff5660e.png)
_Скрин 2. Настройки блока_

**Comment by SergeyPilipenko** [comment]
Проверено в даталайне 2.3.44-beta
