### ISSUE TITLE
[Uni Blocks, Svoe] Кастомный блок Footer

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1116]
Необходимо реализовать кастомный Footer как на _Скрине_ ниже со следующей настройкой:
- **Текст в подвале**  
  - название поля: "Текст"
  - тип компонента: текстовое поле с возможностью форматирования
  - значение по умолчанию: 
     "© 2000-2022 АО «Россельхозбанк»
       Генеральная лицензия Банка России № 3349 от 12 августа 2015"

![Image](https://user-images.githubusercontent.com/112703510/210072394-c6f3884a-7c11-4b0f-ac1c-bd387f747f10.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=9373%3A828021&t=OwM1nXUWxZURZnjE-4))_

**Comment by Mikage777** [comment]
Задачу необходимо реализовать в рамках репозитория проекта "Экосистема Свое".

**Comment by SergeyPilipenko** [comment]
Проверено в Даталайне 2.3.44-beta
