### ISSUE TITLE
[Uni Blocks, Svoe] Новый кастомный блок Табы

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1117]
Необходимо реализовать новый кастомный блок с табами как на _Скрине 1_ ниже со следующими настройками (_Скрин 3_):
- Табы
  - Таб 1
    - **Тег таба**
      - название поля: "Тег"
      - тип компонента: текстово поле
      - значение по умолчанию: "tab1"
    - **Заголовок таба**
      - название поля: "Заголовок"
      - тип компонента: текстово поле
      - значение по умолчанию: "Вкладка 1"
    - **Изображение**
      - можно загрузить свою картинку или выбрать иконку из списка
  - Таб 2
    - **Тег таба**
      - название поля: "Тег"
      - тип компонента: текстово поле
      - значение по умолчанию: "tab2"
    - **Заголовок таба**
      - название поля: "Заголовок"
      - тип компонента: текстово поле
      - значение по умолчанию: "Вкладка 2"
    - **Изображение**
      - можно загрузить свою картинку или выбрать иконку из списка
  - **Добавить вкладку**
    - тип компонента: кнопка
    - при клике добавляются поля для новой вкладки
- **Текст слева от соц сетей**
  - название поля: "Текст для соц сетей"
  - тип компонента: текстово поле
  - значение по умолчанию: "Самое интересное"
- Соц сети (общие для всех табов)
  - Вконтакте
    - **URL**
      - название поля: "URL"
      - тип компонента: текстово поле
      - значение по умолчанию: "https://vk.com"
    - **Таргет**
      - название поля: "Таргет"
      - тип компонента: дропдаун
      - значение по умолчанию: null
  - Youtube
    - **URL**
      - название поля: "URL"
      - тип компонента: текстово поле
      - значение по умолчанию: "https://youtube.com"
    - **Таргет**
      - название поля: "Таргет"
      - тип компонента: дропдаун
      - значение по умолчанию: null
  - Телеграм
    - **URL**
      - название поля: "URL"
      - тип компонента: текстово поле
      - значение по умолчанию: "https://t.me"
    - **Таргет**
      - название поля: "Таргет"
      - тип компонента: дропдаун
      - значение по умолчанию: null
  - **Добавить соц сеть**
    - тип компонента: кнопка
    - при клике добавляются поля для новой соц сети
- Стиль
  - нет ограничений по ширине блока

**Для соц сетей можно использовать компонент socialbuttons**

![Image](https://user-images.githubusercontent.com/112703510/210076745-2ec8d96e-1b0e-4331-8607-0e9f1698d774.png)
_Скрин 1. Вид блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=9373%3A829822&t=OwM1nXUWxZURZnjE-4))_

---

![Image](https://user-images.githubusercontent.com/112703510/210076703-56fff8a5-1178-47b5-a113-7ed24b7d7a87.png)
_Скрин 2. Соц сети_

---

![Image](https://user-images.githubusercontent.com/112703510/210076658-622a05fd-a482-4baa-b537-63057f1f21f0.png)
_Скрин 3. Настройки блока_

**Comment by end0rfin** [comment]
Блок с социальными сетями было решено вынести в отдельный с возможностью абсолютного позиционирования относительно родителя.

**Comment by SergeyPilipenko** [comment]
Проверено в даталайне 2.3.44-beta
