### ISSUE TITLE
[Uni Blocks, Svoe] Новый кастомный блок Галерея

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1118]
Необходимо реализовать кастомный блок Галерея как на _Скрине 1_ ниже со следующими настройками (_Скрин 2_):
- **Заголовок блока**
  - название поля: "Заголовок"
  - тип компонента: текстовое поле
  - значение по умолчанию: "Заголовок"
- **Описание блока**
  - название поля: "Описание"
  - тип компонента: текстовое поле
  - значение по умолчанию: "Описание"
- Кнопка
  - **Текст кнопки**
    - название поля: "Текст"
    - тип компонента: текстовое поле
    - значение по умолчанию: "Все"
  - **URL**
    - название поля: "URL"
    - тип компонента: текстовое поле
    - значение по умолчанию: null
  - **Таргет**
    - название поля: "Таргет"
    - тип компонента: дропдаун
    - значение по умолчанию: null
- Карточки (можно добавить максимум 3 карточки)
  - Карточка 1 (кликабельна, если заполнено поле **URL**)
    - **Заголовок карточки**
      - название поля: "Заголовок"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Заголовок 1"
    - **URL**
      - название поля: "URL"
      - тип компонента: текстовое поле
      - значение по умолчанию: null
    - **Таргет**
      - название поля: "Таргет"
      - тип компонента: дропдаун
      - значение по умолчанию: null
    - **Изображение**
      - можно загрузить свою картинку или выбрать иконку из списка
  - Карточка 2 (кликабельна, если заполнено поле **URL**)
    - **Заголовок карточки**
      - название поля: "Заголовок"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Заголовок 2"
    - **URL**
      - название поля: "URL"
      - тип компонента: текстовое поле
      - значение по умолчанию: null
    - **Таргет**
      - название поля: "Таргет"
      - тип компонента: дропдаун
      - значение по умолчанию: null
    - **Изображение**
      - можно загрузить свою картинку или выбрать иконку из списка
  - Карточка 3 (кликабельна, если заполнено поле **URL**)
    - **Заголовок карточки**
      - название поля: "Заголовок"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Заголовок 3"
    - **URL**
      - название поля: "URL"
      - тип компонента: текстовое поле
      - значение по умолчанию: null
    - **Таргет**
      - название поля: "Таргет"
      - тип компонента: дропдаун
      - значение по умолчанию: null
    - **Изображение**
      - можно загрузить свою картинку или выбрать иконку из списка
- Стиль
  - нет ограничений по ширине блока

![Image](https://user-images.githubusercontent.com/112703510/210081640-025938e2-a6ea-4369-8c84-add9effd5031.png)
_Скрин 1. Вид блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=19277%3A167661&t=OwM1nXUWxZURZnjE-4))_

---

![Image](https://user-images.githubusercontent.com/112703510/210082613-3e759eeb-e69f-4124-b1af-196ef0156b6e.png)
_Скрин 2. Настройки блока_

**Comment by SergeyPilipenko** [comment]
Проверено в даталайне 2.3.44-beta
