### ISSUE TITLE
[Uni Blocks] Доработка блока Carousel (новый вид карточки)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1149]
Необходимо в блоке Carousel добавить новый вид карточки как на _Скрине 1_ ниже.

В настройках карточки должны быть следующие настройки:
- Карточки
  - Карточка 1
    - **Заголовок карточки**
      - название поля: "Заголовок"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Заголовок 1"
    - **Описание карточки**
      - название поля: "Описание"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Описание 1"
    - **Избражение**
      - можно загрузить свою картинку или выбрать иконку из списка
  - Карточка 2
    - **Заголовок карточки**
      - название поля: "Заголовок"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Заголовок 2"
    - **Описание карточки**
      - название поля: "Описание"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Описание 2"
    - **Избражение**
      - можно загрузить свою картинку или выбрать иконку из списка
  - Карточка 3
    - **Заголовок карточки**
      - название поля: "Заголовок"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Заголовок 3"
    - **Описание карточки**
      - название поля: "Описание"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Описание 3"
    - **Избражение**
      - можно загрузить свою картинку или выбрать иконку из списка
  - Карточка 4
    - **Заголовок карточки**
      - название поля: "Заголовок"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Заголовок 4"
    - **Описание карточки**
      - название поля: "Описание"
      - тип компонента: текстовое поле
      - значение по умолчанию: "Описание 4"
    - **Избражение**
      - можно загрузить свою картинку или выбрать иконку из списка
  - **Добавить карточку**
    - тип компонента: кнопка
    - при клике добавляются поля для создания новой карточки
- Стиль
  - по умолчанию ширина 12 колонок

![Image](https://user-images.githubusercontent.com/112703510/211559505-237d3783-01bb-41e6-a79a-3490118fdf3d.png)
_Скрин 1. Вид карусели ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=21146%3A31890&t=tpM34RIFKBdNm2fv-4))_

---

![Image](https://user-images.githubusercontent.com/112703510/211567369-37f0d28e-b8d0-4425-9e95-64336f1f03c5.png)
_Скрин 2. Настройки карточки_

**Comment by klapada** [comment]
Необходимо также для каждой карточки добавить поля для ввода ссылки и таргета, чтобы карточки были кликабельными (на Скрине ниже выделены эти поля):
- Ссылка
  - **URL**
    - тип компонента: текстовое поле
    - значение по умолчанию: null
  - **Таргет**
    - тип компонента: дропдаун
    - значение по умолчанию: null

<img width="163" alt="Screenshot 2023-01-11 at 15 42 19" src="https://user-images.githubusercontent.com/112703510/211809482-434c8caa-e13d-40ff-a8b3-647183e3fb73.png">

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
