### ISSUE TITLE
[Uni Blocks] Доработка блока Вкладки для добавления еще одного вида вкладок (Tabs)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1155]
Необходимо в настройках блока Tabs в поле "Режим вкладок" добавить еще один вариант табов - "По центру", которые будут выглядеть как на _Скрине_ ниже.

![Image](https://user-images.githubusercontent.com/112703510/209969739-88b55f50-84ff-4468-936c-3fd975856f7c.png)
_Скрин. Вид вкладок ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=18538%3A162814&t=99epzmnSyvgL0oNn-4))_

**Comment by Guzlik123** [comment]
2.3.54-beta

Проверено
