### ISSUE TITLE
[Uni Blocks] Доработка в Карусели карточки product (Carousel)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1157]
Необходимо в Карусели в карточке product добавить возможность выбора цвета карточки из предустановленного списка, для этого в настройках нужно добавить новое поле:
- название поля: "Цвет карточки"
- тип компнента: дропдаун
- возможные значения:
  - "Голубой" (на Скрине п.1)
  - "Зеленый" (на Скрине п.5)
  - "Оранжевый" (на Скрине п.2)
  - "Серый" (на Скрине п.4)
  - "Темно-оранжевый" (на Скрине п.6)
  - "Темно-зеленый" (на Скрине п.3)
- значение по умолчанию: "Зеленый"

![Image](https://user-images.githubusercontent.com/112703510/211806588-80de00eb-9151-4731-acfa-9e0908c01a21.png)
_Скрин. Цвета карточек ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=21146%3A31890&t=tGlGJH7qtIcUskGZ-4))_

**Comment by end0rfin** [comment]
Задача, по которой прошла реализация https://github.com/redneckz/wildless-cms-uni-blocks/issues/1240

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
