### ISSUE TITLE
[Uni Blocks] Выравнивание высоты карточек по самой большой карточке

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1163]
Необходимо в блоке Carousel сделать так, чтобы высота всех вложенных карточек была одинаковой и выравнивалась по самой большой по высоте карточке.

**Comment by SergeyPilipenko** [comment]
2.3.51-beta
https://10.80.4.9:81/#15162/content%2Fdbo-mbank.page.json

В КР карточки отображаются не по высоте, при этом на портале отображение корректно



![Image](https://user-images.githubusercontent.com/22083206/216275619-925afa2d-60a3-4420-a11f-46f7b9b7f55d.png)

**Comment by end0rfin** [comment]
Данное поведение наблюдается только в кабинете редактора.
Вызвано это наличием дополнительной обёртки над вставляемыми блоками.
При публикации карточки ведутся себя как надо, т.е. растягиваются по высоте.
Решение с исправлением багов вызванных наличием обёртки в КР пока на обсуждении.

**Comment by end0rfin** [comment]
Исправлено 
https://github.com/redneckz/wildless-cms-uni-blocks/pull/1288

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
