### ISSUE TITLE
[Uni Blocks] Фиксированная ширина карточек tariffs (Carousel)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1182]
Необходимо у карточки Карусели tariffs изменить следующее:
- сделать ее ширину фиксированной как на _Скрине_ ниже
- если карточек немного (например 2-3) и они занимают не всю ширину страницы, то они центрируются, как показано на _Скрине_ ниже

![Image](https://user-images.githubusercontent.com/112703510/212689591-a76d6d59-0fce-4af0-b9b5-dca2470ad30e.png)
_Скрин. Вид 2х карточек ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=16640%3A118960&t=ws88agS0vEisvCCX-4))_

**Comment by Longraf** [comment]
У карточки фиксированную ширину делать не будем. За ширину карточки будет отвечать сама Карусель в будущем рефакторинге

**Comment by SergeyPilipenko** [comment]
2.3.53-beta проверено, кол-во карточек регулируется настройками карусели
