### ISSUE TITLE
[Uni Blocks] Доработка кредитного калькулятора в блоке Калькулятор (Calculator)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1187]
Необходимо в блоке Calculator для Кредитного калькулятора реализовать следующее:

1) Добавить новый чекбокс - "Получаю пенсию на карту Россельхозбанка" (место, куда добавить чекбокс в блоке, показано на _Скрине 1_ ниже) + добавить новый булевый параметр в справочник, т.к. от этого чекбокса зависит ставка

2) добавить возможность настройки отображения чекбоксов в блоке (например, в блоке выводить только 1, 2 или 3 чекбокса из 4х), а для этого добавить в настройках новые поля как на _Скрине 2_:
    - **Чекбокс 1**
      - название поля: "Получаю зарплату на счёт в Россельхозбанке"
      - тип компонента: чекбокс
      - возможные значения:
        - true (= чекбокс "Получаю зарплату на счёт в Россельхозбанке" отображается в блоке)
        - false (= чекбокс "Получаю зарплату на счёт в Россельхозбанке" в блоке не отображается)
      - значение по умолчанию: true
    - **Чекбокс 2**
      - название поля: "Работаю в бюджетной организации"
      - тип компонента: чекбокс
      - возможные значения:
        - true (= чекбокс "Работаю в бюджетной организации" отображается в блоке)
        - false (= чекбокс "Работаю в бюджетной организации" в блоке не отображается)
      - значение по умолчанию: true
    - **Чекбокс 3**
      - название поля: "Получаю пенсию на карту Россельхозбанка"
      - тип компонента: чекбокс
      - возможные значения:
        - true (= чекбокс "Получаю пенсию на карту Россельхозбанка" отображается в блоке)
        - false (= чекбокс "Получаю пенсию на карту Россельхозбанка" в блоке не отображается)
      - значение по умолчанию: true
    - **Чекбокс 4**
      - название поля: "Комплексная страховая защита"
      - тип компонента: чекбокс
      - возможные значения:
        - true (= чекбокс "Комплексная страховая защита" отображается в блоке)
        - false (= чекбокс "Комплексная страховая защита" в блоке не отображается)
      - значение по умолчанию: true

3) Возможность задавать определенные условия со своими пограничными значениями суммы и/или срока в зависимости от выбранных чекбоксов в калькуляторе (например, срок кредита более 3 млн (до 5 млн вкл) доступен только при активном чекбоксе "Получаю зарплату на счёт в Россельхозбанке")

![Image](https://user-images.githubusercontent.com/112703510/216032892-647545d6-b780-4cd5-8e8b-e34f7010928a.png)
_Скрин 1. Новый чекбокс_

---

![Image](https://user-images.githubusercontent.com/112703510/216021592-5446eb6b-0fb5-412c-aca1-04b9a2a02ffc.png)
_Скрин 2. Настройки отображения/скрытия чекбоксов в блоке_

**Comment by andreySimonenko** [comment]
1. Ключ для нового чекбокса - `isPensionClient`
3. Необходимо будет добавить новые справочники с настройками пограничных значений

**Comment by SergeyPilipenko** [comment]
2.3.52-beta проверено
