### ISSUE TITLE
[Uni Blocks] Добавление нового вида Калькулятора для рефинансирования (Calculator)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1188]
1) Необходимо в настройках блока Calculator в дропдауне добавить еще один вариант выбора вида калькулятора - "Кредитный калькулятор - рефинансирование", при выборе которого отображается калькулятор как на _Скрине 1_ ниже.

2) Настройки у данного калькулятора следующие (_Скрин 2_):
    - **Адрес справочника**
      - тип компонента: дропдаун
      - значение по умолчанию: null
    - **Заголовок**
      - тип компонента: текстовое поле
      - значение по умолчанию: null
    - **Кнопки**
      - добавлена "Кнопка 1" аналогично кредитному калькулятору
    - **Сноска**
      - тип компонента: текстовое поле
      - значение по умолчанию: "Расчёт является предварительным. Точные условия будут предоставлены в отделении Банка."

3) Логика работы полей в калькуляторе следующая:
    - **Остаток долга в других банках**
      - тип компонента: слайдер
      - мин значение: задается в справочнике (30 000)
      - макс значение: задается в справочнике (3 000 000)
      - значение по умолчанию: 2 500 000
    - **Ежемесячный платеж в др банках**
      - тип компонента: слайдер
      - мин значение: задается в справочнике (0)
      - макс значение: задается в справочнике (2 500 000)
      - значение по умолчанию: 0
    - **Новый срок кредита**
      - тип компонента: слайдер
      - мин значение: задается в справочнике (13)
      - макс значение: задается в справочнике (60)
      - значение по умолчанию: 48
    - **Получаю зарплату на счёт в Россельхозбанке**
      - тип компонента: чекбокс
      - значение по умолчанию: false
    - **Комплексная страховая защита**
      - тип компонента: чекбокс
      - значение по умолчанию: true
    - **Получить дополнительную сумму**
      - тип компонента: чекбокс
      - значение по умолчанию: false
    - **Дополнительная сумма**
      - тип компонента: слайдер
      - мин значение: задается в справочнике (0)
      - макс значение: задается в справочнике (500 000)
      - значение по умолчанию: 0
      - отображается только, если **Получить дополнительную сумму** = true
    - **Ставка**
      - отображается значение из справочника, которое соответствует выбранным параметрам в калькуляторе
    - **Ежемесячный платеж**
      - отображается посчитанное значение в соответствии с выбранными параметрами (расчет аналогичный, как в кредитном калькуляторе, только сумма кредита=**Остаток долга в других банках** + **Дополнительная сумма**)
    - **Выгода в месяц**
      - формула расчета: **Ежемесячный платеж в др банках** - **Ежемесячный платеж**
      - поле и значение отображаются, если значение выгоды > 0
    - **Отправить заявку**
      - тип компонента: кнопка
      - при клике осуществляется переход по ссылке, указанной в настройках калькулятора
    

![Image](https://user-images.githubusercontent.com/112703510/216661547-516fa7b8-cf67-4d11-8937-623acbd7f486.png)
_Скрин 1. Вид нового калькулятора ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=14028%3A152924&t=uCygQm162GvaXUoB-4))_

---

![Image](https://user-images.githubusercontent.com/112703510/216385788-56e2948d-dc72-46b6-994c-b6e7ad52f8b3.png)
_Скрин 2. Настройки калькулятора "Кредитный калькулятор - рефинансирование"_

**Comment by klapada** [comment]
На логику вывода ставки, которая подтягивается из выбранного в КР справочника, влияют следующие значения:
- сумма кредита (= **Остаток долга в других банках** + **Дополнительная сумма**)
- срок кредита (= **Новый срок кредита**)
- чекбокс "Получаю зарплату на счёт в Россельхозбанке"
- чекбокс "Комплексная страховая защита"

**Comment by klapada** [comment]
В настройках калькулятора рефинансирования в подразделе "Настройка отображения чекбоксов" должно быть 2 чекбокса как на _Скрине_ ниже.

<img width="402" alt="Screenshot 2023-04-11 at 12 11 03" src="https://user-images.githubusercontent.com/112703510/231113340-9939ffd4-dd3a-4d02-9d21-4c6c36acc6b4.png">

**Comment by SergeyPilipenko** [comment]
2.3.67-beta проверено
