### ISSUE TITLE
[Uni Blocks] Доработка карточки recommendations в Карусели (Carousel)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1213]
Необходимо в блоке Carousel у карточки recommendations изменить следующее:
1) убрать абсолютное позиционирование картинки
2) картинка размещается под Заголовком и/или Описанием (как на _Скрине 1_ ниже)
3) картинка размещается справа от буллитов (как сейчас работает, если добавить список (_Скрин 2_))
4) добавить в настройках блока 2 новых поля:
    - **URL**
      - тип компонента: текстовое поле
      - значения по умолчанию: null
      - если поле заполнено, то карточка кликабельна
    - **Таргет**
      - тип компонента: дропдаун
      - значения по умолчанию: null

![Image](https://user-images.githubusercontent.com/112703510/213684469-3df9b2b7-e045-4441-8760-ebb903a5f0b8.png)
_Скрин 1. Расположение картинки в блоке ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=16640%3A115683&t=Q18OZBtAJ6pOUN5A-4))_

---

![Image](https://user-images.githubusercontent.com/112703510/213688803-2b496967-06c8-4148-aeb5-52ef9cfe1d57.png)
_Скрин 2. Карточка с картинкой и списком_

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
