### ISSUE TITLE
Всплывающая форма для куки

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1235]
Необходимо реализовать следующее:
1) добавить всплывающую форму для куки как на _Скрине_ ниже
    - ссылка для "cookie": "https://www.rshb.ru/pd-policy/cookie/"  (потом нужно будет заменить на страницу нового сайта)
    - ссылка для "Обработка Ваших персональных данных": "https://www.rshb.ru/pd-policy/" (потом нужно будет заменить на страницу нового сайта)
2) если пользователь закрыл форму нажатием на "крестик" на любой странице сайта, то:
    - запускается таймер на 1ч
    - форма для куки скрывается и при переходе между страницами повторно не всплывает
    - по истечении времени по таймеру пользователю повторно выводится форма для куки, при этом неважно, находится ли пользователь все еще на сайте или уходил с него, а потом вернулся или обновлял страницу

![Image](https://user-images.githubusercontent.com/112703510/214289172-bb8da672-c440-4e1e-ae15-1ea3fb0ef49e.png)
_Скрин. Вид формы для куки ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=24376%3A178503&t=rfj3UX54T2lXbfNL-4))_

**Comment by klapada** [comment]
Актуальные ссылки, которые будут вести на страницу на новом сайте:
- ссылка для "cookie": "pd-policy"
- ссылка для "Обработка Ваших персональных данных": "pd-policy#cookie"

**Comment by SergeyPilipenko** [comment]
2.3.53-beta проверено в даталайне и ип2.0
