### ISSUE TITLE
[Uni Blocks] Доработка карточки карусели CarouselProductCard

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1239]
Необходимо в настройках CarouselProductCard добавить 2 новых поля:
- **URL**
  - тип компонента: текстовое поле
  - значения по умолчанию: null
  - если поле заполнено, то карточка кликабельна
- **Таргет**
  - тип компонента: дропдаун
  - значения по умолчанию: null

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
