### ISSUE TITLE
[Uni Blocks] Доработка карточки карусели CarouselProgramscard

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1240]
Необходимо в карточке карусели CarouselProductCard реализовать следующее:

1) добавить возможность кликабельности карточек, а для этого в настройках блока добавить 2 новых поля:
    - **URL**
      - тип компонента: текстовое поле
      - значения по умолчанию: null
      - если поле заполнено, то карточка кликабельна
    - **Таргет**
      - тип компонента: дропдаун
      - значения по умолчанию: null

2) добавить возможность выбора цвета карточки из списка, а для этого добавить новое поле:
    - название поля: "Цвет карточки"
    - тип компнента: дропдаун
    - возможные значения:
      - "Голубой" (на Скрине п.3)
      - "Зеленый" (на Скрине п.1)
      - "Оранжевый" (на Скрине п.2)
      - "Персиковый" (на Скрине п.6)
      - "Серый" (на Скрине п.4)
      - "Салатовый" (на Скрине п.5)
    - значение по умолчанию: "Зеленый"

![Image](https://user-images.githubusercontent.com/112703510/214570591-e6315f46-be0f-4272-9e5e-35039035da7c.png)
_Скрин. Цветные карточки ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=21089%3A20861&t=ENlXplZR1u9Ikqoe-4))_

**Comment by end0rfin** [comment]
Дубль задачи https://github.com/redneckz/wildless-cms-uni-blocks/issues/1157

**Comment by SergeyPilipenko** [comment]
проверено в даталайне 2.3.51-beta
