### ISSUE TITLE
е2е. Портал. Табы. Пропадает контент таба при нажатии на якорную ссылку в другом табе

### ISSUE THREAD

**Issue by SergeyPilipenko** [redneckz/wildless-cms-uni-blocks#1244]
https://10.80.4.9/natural/payrings#howto

В блоке Частые вопросы в вертикальном компоновщике есть блок табыс группами и вертикальные компоновщики со сворачивающимися секциями для каждого таба.
Вверху станицы есть блок табы с якорными ссылками до блоков на странице.

Шаги:
1. Долистать страницу до блока Частые вопросы
2. Нажать в табах страницы пункт Как пополнить

ФР: Происходит скроллинг до нужного таба, но контент в табе Частые вопросы пропадает

![image](https://user-images.githubusercontent.com/22083206/214812766-44409578-faca-4a31-b1ea-41b5d38d11bb.png)
![image](https://user-images.githubusercontent.com/22083206/214812656-95acab54-5c46-4d91-abf0-5a826b6fb99f.png)

**Comment by lis42000** [comment]
Проблема уйдёт при выполнении задачи https://github.com/redneckz/wildless-cms-uni-blocks/issues/1260

**Comment by SergeyPilipenko** [comment]
кейс будет проверен в рамках  задачи https://github.com/redneckz/wildless-cms-uni-blocks/issues/1260
