### ISSUE TITLE
[Uni Blocks] Доработка калькулятора вкладов (Calculator)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1276]
Необходимо в калкуляторе вкладов изменить поле для выбора срока вклада со слайдера на дропдаун как на _Скрине_ ниже.

Логика работы поля "Срок вклада":
- тип компонента: дропдаун
- возможные значения: {список уникальных значений из выбранного справочника в настройках блока в поле **Адрес справочника**}
- значение по умолчанию: {первое значение из выбранного справочника в настройках блока в поле **Адрес справочника**}

![Image](https://user-images.githubusercontent.com/112703510/216027442-f0fd412b-0d72-4aa3-8f45-c818b52245e0.png)
_Скрин. Дропдаун для выбора срока вклада ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=24816%3A189706&t=tjiv1rUWyzLG8KDP-4))_

**Comment by klapada** [comment]
Необходимо также в настройки калькулятора вкладов добавить новые поля для возможности скрывать/отображать радиобаттоны по **Выплате процентов** и **Оформлению** (Скрин настроек ниже):
- Чекбокс 1
  - название поля: "Выплата процентов"
  - тип компонента: чекбокс
  - возможные значения:
    - true (= радиобаттоны "Выплата процентов" отображаются в блоке)
    - false (= радиобаттоны "Выплата процентов" в блоке не отображаются)
  - значение по умолчанию: true
- Чекбокс 2
  - название поля: "Оформление"
  - тип компонента: чекбокс
  - возможные значения:
    - true (= радиобаттоны "Оформление" отображаются в блоке)
    - false (= радиобаттоны "Оформление" в блоке не отображаются)
  - значение по умолчанию: true

<img width="193" alt="Screenshot 2023-02-03 at 12 28 43" src="https://user-images.githubusercontent.com/112703510/216563671-5c9dd4fa-0077-4dd5-a0a3-a96d207ee206.png">

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
