### ISSUE TITLE
[Uni Blocks] Доработка блока Форма заявки в части добавления новой формы (ApplicationForm)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1286]
1) Необходимо в блоке ApplicationForm добавить новый вид заявки - "Грантовая поддержка", вид которой показан на _Скрине_ ниже.

2) Нужно создать новый справочник с названиями регионов и ссылками для каждой из них для корректной работы данной формы (регионы и ссылки представлены в файле ниже)
[Бизнес_Получение гранта.xlsx](https://github.com/redneckz/wildless-cms-uni-blocks/files/10694821/_.xlsx)

3) Логика работы полей в форме:
    - **Ваш регион**
      - тип компонента: дропдаун
      - возможные значения: {значения регионов из конкретного справочника, созданного в п.2}
      - значение по умолчанию: {первое значение в списке из конкретного справочника}
    - **Перейти**
      - тип компонента: кнопка
      - при клике осуществляется переход по ссылке (открытие в новой вкладке), соответствующей в конкретном справочнике выбранному региону в поле **Ваш регион**

![Image](https://user-images.githubusercontent.com/112703510/216393833-202085e2-4847-4eac-9be2-3c8fe38303f5.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=21411%3A40494&t=hJyD8I40iBceobc4-4))_

**Comment by Guzlik123** [comment]
2.3.61-beta

Проверено в даталайне

**Comment by klapada** [comment]
В данной форме условий передачи данных нет
