### ISSUE TITLE
[Uni Blocks] Добавить кнопку "Интернет-банк" в шапке (Header)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1290]
Необходимо в блоке Header добавить кнопку "Интернет-банк" как на _Скрине_ ниже.
Ссылка на кнопке - http://next.rshb.ru/

![Image](https://user-images.githubusercontent.com/112703510/216660643-0e678242-6d96-488e-90e4-86e20a204d21.png)
_Скрин. Шапка ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=7991%3A158693&t=mO3CnwmgnUzTOwQj-4))_

**Comment by Guzlik123** [comment]
2.3.53-beta

Проверено
