### ISSUE TITLE
[Uni Blocks] Доработка карточки тарифной карусели (CarouselTariffsCard)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1291]
Необходимо в настройках CarouselTariffsCard добавить новое поле, чтобы стало доступно добавление кнопки в ячейке (_Скрин 2_):
- тип компонента: дропдаун
- возможные значения:
  - Заголовок и описание
  - Кнопки
- значение по умолчанию: "Заголовок и описание"
- при выборе значения "Заголовок и описание" отображаются поля **Название** и **Описание** (Скрин 2 слева)
- при выборе значения "Кнопки" становится доступным добавление кнопки (Скрин 2 справа) (по аналогии как сделано в блоке TariffsTable)

![Image](https://user-images.githubusercontent.com/112703510/216672872-27f5b205-8ab3-4375-a2c0-fed75a0e4e96.png)
_Скрин 1. Вид карточки с кнопкой в виде ссылки ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=21560%3A53027&t=Kw8mXC6RbkRtcddS-4))_

---

![Image](https://user-images.githubusercontent.com/112703510/216673797-c3a87fed-7e61-4d9c-a19a-40bdaa8fb3e2.png)
_Скрин 2. Настройки блока_

**Comment by Guzlik123** [comment]
2.3.53-beta

По согласованию с аналитиком пока что оставили возможность добавления в одной ячейки "кнопку" и "заголовок + описание"
