### ISSUE TITLE
[Uni Blocks] Изменить пограничные значения суммы/срока в заявке на кредит (ApplicationForm)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1308]
Необходимо в блоке ApplicationForm для вида заявки = "Кредит" изменить следующие значения:
- **Сумма кредита**
  - мин. значение: 1000
  - макс. значение: 1 000 000 000
  - значение по умолчанию: 100 000
  - на слайдере текст: "От 1 000 Р" и "До 1 000 000 000 Р"
- **Срок кредита**
  - мин. значение: 1
  - макс. значение: 180
  - значение по умолчанию: 12
  - на слайдере текст: "От 1 мес" и "До 15 лет"

![Image](https://user-images.githubusercontent.com/112703510/217752789-8fe87f81-9277-4f4b-8caa-629bd11bad20.png)

**Comment by SergeyPilipenko** [comment]
2.3.54-beta проверено в даталайне
