### ISSUE TITLE
[Uni Blocks] Доработка формы ВЭД для отправки данных в Lotus

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1313]
API: https://portal.rshbdev.ru/environments/dev/systems/internal/catalog/services/leadservice#api

Необходимо в блоке ApplicationForm для вида заявки = "ВЭД" внести следующие изменения:

#### 1) Изменить форму заявки согласно обновленному макету в зависимости от выбранного варианта:
  - если "Валютный контроль" = true, то вид формы как на _Скрине 1_
  - если "Валютный контроль" = false, то вид формы как на _Скрине 2_

#### 2) Описание всех полей в форме:
  - **Наименование организации**
    - обязательное поле
  - **ФИО**
    - обязательное поле
  - **Телефон**
    - обязательное поле
  - **Электронная почта**
    - необязательное поле
    - скрывается, если **Валютный контроль** = true
  - **ИНН**
    -  тип: текстовое поле
    - значение по умолчанию: null
    - при блюре осуществляется валидация значения на кол-во символов - 10 или 12 чисел для ООО или ИП и если значение - содержит не 10 или 12 чисел, то отображается ошибка "Некорректно заполненное поле"
    - обязательное поле
    - отображается, если **Валютный контроль** = true
  - **Регион**
    - тип: дропдаун
    - возможные значения: все значения из справочника regions
    - значение по умолчанию: выбранное значение региона в шапке
    - обязательное поле
    - отображается, если **Валютный контроль** = true
  - **Валютный контроль**
    - тип: радио
    - значение по умолчанию: true
  - **Документарные операции**
    - тип: радио
    - значение по умолчанию: false
  - **Конверсионные операции**
    - тип: радио
    - значение по умолчанию: false
  - **Иные вопросы ВЭД**
    - тип: радио
    - значение по умолчанию: false
  - **Обращение**
    - плейсхолдер: "Обращение"
    - обязательное поле

#### 3) При клике на кнопку "Отправить" осуществляется отправка данных ниже:
  - если **Валютный контроль** = true, то:
    - typeForm = KVED
    - fullName = {значение из поля **Наименование организации**}
    - name = {значение из поля **ФИО**}
    - phone = {значение из поля **Телефон**}
    - inn = {значение из поля **ИНН**}
    - region = {значение из поля **Регион**}
    - vedTypes = 
      {currencyControl = {true/false поля **Валютный контроль**}
       documentOperations = {true/false поля **Документарные операции**}
       conversionTransactions = {true/false поля **Конверсионные операции**}
       otherIssues = {true/false поля **Иные вопросы ВЭД**}}
    - partnerComments = {значение из поля **Обращение**}
  
  - если **Валютный контроль** = false, то:
    - typeForm = KVED
    - fullName = {значение из поля **Наименование организации**}
    - name = {значение из поля **ФИО**}
    - phone = {значение из поля **Телефон**}
    - mail = {значение из поля **Электронная почта**}
    - vedTypes = 
      {currencyControl = {true/false поля **Валютный контроль**}
       documentOperations = {true/false поля **Документарные операции**}
       conversionTransactions = {true/false поля **Конверсионные операции**}
       otherIssues = {true/false поля **Иные вопросы ВЭД**}}
    - partnerComments = {значение из поля **Обращение**}

![Image](https://user-images.githubusercontent.com/112703510/223068335-82081e3c-e6b4-47ae-857a-64f5c6019c19.png)
_Скрин 1. Вид блока, если **Валютный контроль** = true ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=19300%3A30352&t=7SNahxzrdnz1h7ha-4))_

![Image](https://user-images.githubusercontent.com/112703510/223068380-2730f175-b190-439c-b984-e5eb123f5a37.png)
_Скрин 2. Вид блока, если **Валютный контроль** = false ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=21212%3A65462&t=7SNahxzrdnz1h7ha-4))_

**Comment by Longraf** [comment]
Ранее ключ был PartnerComments  теперь partnerComments

**Comment by SergeyPilipenko** [comment]
проверено на рц
