### ISSUE TITLE
[Uni Blocks] Добавить текст в Footer рядом с контактами

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1316]
Необходимо в Footer после короткого номера "7787" указать следующий текст "*Для частных клиентов абонентам МТС, Мегафон, Билайн и Tele2" как показано на _Скрине_ ниже.

![Image](https://user-images.githubusercontent.com/112703510/218415977-c0090feb-692f-4c51-9993-6ecceaaf5137.png)
_Скрин. Текст в футере ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=17078%3A113674&t=bkl4bgT0TgUgHkMW-4))_

**Comment by klapada** [comment]
Необходимо несколько иначе скорректировать текст в футере. На _Скрине_ ниже показано, как должно быть.


<img width="741" alt="Screenshot 2023-02-16 at 15 30 00" src="https://user-images.githubusercontent.com/112703510/219366138-4921b942-b077-411f-b41a-d5a1979f8822.png">
_Скрин. Футер ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=1442%3A36635&t=y7KFf3LNoNoPve5r-4))_

**Comment by SergeyPilipenko** [comment]
2.3.54-beta не испарвлено

**Comment by SergeyPilipenko** [comment]
2.3.55-beta исправлено
