### ISSUE TITLE
[Uni Blocks] GracePeriod

### ISSUE THREAD

**Issue by redneckz** [redneckz/wildless-cms-uni-blocks#1334]
![image](https://user-images.githubusercontent.com/5698620/218440677-87b19cba-17db-468c-b924-e99556690dd9.png)
практически не используется.
Можно ли отказаться от этого блока?

**Comment by klapada** [comment]
Этот блок нужен, будет использоваться. 
Текущий вид не устраивает заказчика, поэтому потребуется его переработка в части UI. Пока что со страниц его убрали временно, но позже будет подготовлен макет в новом виде и нужно будет его переработать.

**Comment by Irinaristova** [comment]
Задача закрыта в связи с тем, что данный блок будет полностью переработан
