### ISSUE TITLE
[Uni Blocks] Мобильный блок ProductGallery

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1337]
Необходимо реализовать мобильный блок ProductGallery как на _Скрине 1_ ниже.

Настройки аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/221809415-5d3dd95e-5019-43d8-96dc-00f02a85f209.png)
_Скрин 1. Вид блока ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A23511&t=XX8czAZ1IR2j9nrV-4))_

**Comment by Guzlik123** [comment]
2.3.57-beta

Проверено в даталайне
