### ISSUE TITLE
[Uni Blocks] Возможность в кредитном калькуляторе задавать исключительные условия (Calculator)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1344]
Для кредитного калькулятора добавить возможность задавать определенные условия со своими пограничными значениями суммы и/или срока в зависимости от выбранных чекбоксов в калькуляторе (например, срок кредита более 3 млн (до 5 млн вкл) доступен только при активном чекбоксе "Получаю зарплату на счёт в Россельхозбанке")

**Comment by SergeyPilipenko** [comment]
2.3.83-beta проверено в даталайне
