### ISSUE TITLE
[Uni Blocks] Мобильный блок CarouselRecommendationCard

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1349]
Необходимо реализовать мобильный блок CarouselRecommendationCard как на _Скринах_ ниже.

Настройки блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/221807687-8b7358a2-dcec-4341-8765-97050d48b582.png)
_Скрин 1. Вид блока без кнопок ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A25260&t=XX8czAZ1IR2j9nrV-4))_

![Image](https://user-images.githubusercontent.com/112703510/221807758-6f20643a-767a-48c7-a8a0-16db3fc33906.png)
_Скрин 2. Вид блока с кнопками ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A23511&t=XX8czAZ1IR2j9nrV-4))_

**Comment by SergeyPilipenko** [comment]
2.3.58-beta проверено в даталайне
