### ISSUE TITLE
[Uni Blocks] Мобильный блок LinkDocs

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1355]
Необходимо реализовать мобильный блок LinkDocs как на _Скрине 1_ ниже.

Настройки блока аналогичны десктопному.
Для значения в поле description использовать шрифт = L_L

![Image](https://user-images.githubusercontent.com/112703510/219343618-8cc56d14-5cb8-4f64-86cf-77e9e06ba04f.png)
_Скрин 1. Вид блока с заголовком и списком документов ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A25328&t=fh17eBINqNBx4nuZ-4))_

![Image](https://user-images.githubusercontent.com/112703510/219345603-ea03823e-d6db-4416-91df-64c71b63753c.png)
_Скрин 2. Вид десктопного блока_

**Comment by Longraf** [comment]
Согласование с Эльдаром
Отступ от иконки до текста 12px для всех разрешений (desctop/mobile)
Выравнивание по верху
Жирность в mobile = 400 у decktop = 300 это не ошибка, а сделано специально

**Comment by SergeyPilipenko** [comment]
2.3.53-beta проверено в даталайне
