### ISSUE TITLE
[Uni Blocks] Мобильный блок StepsBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1356]
Необходимо реализовать мобильный блок StepsBlock, вид которого зависит от примененных параметров:

#### 1) Если в десктопном блоке нет кнопок или есть только общие кнопки:
- В настройках Размер шагов = "Обычный"/"Уменьшенный" и без иконки:
  - если Тема шагов = "Серая", то вид как на _Скрине ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17239%3A210793&t=fh17eBINqNBx4nuZ-4))_
![Image](https://user-images.githubusercontent.com/112703510/219355750-a8f61a39-1919-466f-b61c-d873510d5497.png)

  - если Тема шагов = "Основная" или "Второстепенная", то вид аналогичен как на _Скрине ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17833%3A111585&t=wPO0wODkrXlkzEbC-4))_, а цвет фона шагов зеленый или фона нет (логика изменения цвета цифры внутри шага аналогична десктопу)
![Image](https://user-images.githubusercontent.com/112703510/219657814-9191f586-cd78-4332-9c4c-577fa439d795.png)

- В настройках Размер шагов = "Обычный"/"Уменьшенный" и с иконкой (36х36px):
  - если Тема шагов = "Серая", то вид как на _Скрине ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17637%3A126065&t=fh17eBINqNBx4nuZ-4))_
  - если Тема шагов = "Основная", то вид как на _Скрине_, но у шагов нет фона
![Image](https://user-images.githubusercontent.com/112703510/219409823-06dd9256-629c-411c-94f4-1bc707c70043.png)

  - если Тема шагов = "Второстепенная", то вид как на _Скрине ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17833%3A187199&t=fh17eBINqNBx4nuZ-4))_
![Image](https://user-images.githubusercontent.com/112703510/219410016-9940a137-9d40-4a7e-9bff-956f2f07acd1.png)

- В настройках Размер шагов = "Обычный" и с иконкой (70х70px):
  - если Тема шагов = "Серая", "Основная" или "Второстепенная", то вид как на Скрине ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17833%3A193260&t=fh17eBINqNBx4nuZ-4))
![Image](https://user-images.githubusercontent.com/112703510/219420156-cbfeb024-d281-4273-b335-a766beecd5da.png)

#### 2) Если в десктопном блоке для каждого шага добавлена своя кнопка:
- В настройках Размер шагов = "Обычный"/"Уменьшенный" и с иконкой:
  - если Тема шагов = "Серая", "Основная" или "Второстепенная", то вид как на Скрине ниже ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=18033%3A144118&t=fh17eBINqNBx4nuZ-4))

- В настройках Размер шагов = "Обычный"/"Уменьшенный" и без иконки:
  - если Тема шагов = "Серая", "Основная" или "Второстепенная", то вид как на Скрине ниже, но без картинки, т.е. кнопка будет сразу под текстом
![Image](https://user-images.githubusercontent.com/112703510/219380772-f829e212-db87-4127-b2ad-c5913e8a8f58.png)

**Comment by SergeyPilipenko** [comment]
2.3.58-beta проверено в даталайне
