### ISSUE TITLE
[Uni Blocks] Мобильный блок Tabs

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1358]
Необходимо реализовать мобильный блок Tabs.

Настройки блока как у десктопного.

1) Если в настройках блока был выбран Режим вкладок = "По ширине экрана" и Показывать счетчик блоков во вкладках = false, то вид табов как на _Скрине 1_
2) Если в настройках блока был выбран Режим вкладок = "По ширине экрана" и Показывать счетчик блоков во вкладках = true, то вид табов как на _Скрине 2_
3) Если в настройках десктопного блока был выбран Режим вкладок = "С прокруткой", то вид табов как на _Скрине 3_

![Image](https://user-images.githubusercontent.com/112703510/219392479-50d18e72-f511-494c-865f-95d139d209be.png)
_Скрин 1. Вид табов без счетчика ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A25324&t=fh17eBINqNBx4nuZ-4))_

![Image](https://user-images.githubusercontent.com/112703510/219390968-1f5c2087-c995-4c13-927d-e1228c9596b9.png)
_Скрин 2. Вид табов со счетчиком ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17239%3A201416&t=fh17eBINqNBx4nuZ-4))_

![Image](https://user-images.githubusercontent.com/112703510/219392992-f1ee6bc9-cb3d-4e8d-b9c1-e00823a6f98f.png)
_Скрин 3. Вид табов с прокруткой ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17833%3A139192&t=fh17eBINqNBx4nuZ-4))_

**Comment by SergeyPilipenko** [comment]
2.3.57-beta проверено в даталайне
