### ISSUE TITLE
[Uni Blocks] Мобильный блок RichTextBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1364]
Необходимо реализовать мобильный блок RichTextBlock.

1) Пример списка с буллитами на _Скрине_ ниже ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17386%3A84908&t=bEIgilDOkGNPWdxQ-4))
![Image](https://user-images.githubusercontent.com/112703510/219048630-b36f7726-dbc5-44f8-a2ef-40594a85ee78.png)

2) Пример нумерованного списка на _Скрине_ ниже ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17843%3A134518&t=0DZhKTC0UUG7EZRz-4))
![Image](https://user-images.githubusercontent.com/112703510/220087293-f59a376b-464e-40f7-bff8-e7d439956dcf.png)

3) Пример жирного текста на _Скрине_ ниже ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17491%3A131815&t=0DZhKTC0UUG7EZRz-4))
![Image](https://user-images.githubusercontent.com/112703510/220089610-3f4e43fa-5e7a-4fc8-9fd2-12178b78baa1.png)

4) Заголовки в ките по [ссылке](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=13004%3A142970&t=0DZhKTC0UUG7EZRz-4)

Настройки блока аналогичны десктопному блоку.

**Comment by SergeyPilipenko** [comment]
2.3.54-beta проверено в даталайне
