### ISSUE TITLE
[Uni Blocks] Мобильный блок Calculator

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1368]
Необходимо реализовать мобильный блок Calculator.

Настройки блока аналогичны десктопному блоку.

#### 1) Кредитный калькулятор ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17239%3A82810&t=0DZhKTC0UUG7EZRz-4))
![Image](https://user-images.githubusercontent.com/112703510/220115275-938dd479-8b07-4dd9-9a43-78d5d4d197dd.png)

#### 2) Калькулятор вкладов ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17239%3A134829&t=2vAEZkGFsBVlqH35-4))
![Image](https://user-images.githubusercontent.com/112703510/220329928-1f50b256-c273-40a1-a50a-ee2b30f74abc.png)

#### 3) Калькулятор вкладов - бизнес ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17637%3A117050&t=0DZhKTC0UUG7EZRz-4))
![Image](https://user-images.githubusercontent.com/112703510/220124484-eb9a9046-8161-4d37-8509-9fb99f96c450.png)

#### 4) Вид блока с вкладками ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17239%3A77796&t=0DZhKTC0UUG7EZRz-4))
![Image](https://user-images.githubusercontent.com/112703510/220116934-b24f5cf3-7276-4f33-ab00-101a011339ae.png)

**Comment by Guzlik123** [comment]
2.3.62-beta

Проверено в даталайне
