### ISSUE TITLE
[Uni Blocks] Новый блок Фильтрация для вкладов

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1371]
1) Необходимо реализовать новый блок Фильтрация для вкладов как на _Скрине_ ниже. Данный блок работает по аналогии с блоком Фильтрация для ипотеки.

2) Логика работы полей в блоке следующая:
- **Сумма** (п.1 на Скрине 1)
  - тип: числовое поле
  - значение по умолчанию: 1000
  - плейсхолдер: "От 500 р"
  - если введено значения < 500р, то при блюре подставлять значение = 500
- **Срок** (п.2 на Скрине 1)
  - тип: слайдер
  - единица измерения: месяцы
  - мин значение = 3
  - макс значение = 24
  - шаг: 1
  - значение по умолчанию: 18
- Остальные поля по аналогии с фильтрацией для ипотеки.

3) При фильтрации вкладов в рамках одной группы фильтров поиск осуществляется среди вложенных продуктовых плиток с использованием оператора “ИЛИ”, а между разными группами фильтров - оператора “И”

![Image](https://user-images.githubusercontent.com/112703510/220137297-d469082c-b505-4354-ae31-1823c008032d.png)
_Скрин. Вид блока для фильтрации вкладов ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=24599%3A180722&t=WMg6yZreX88LnpDR-4))_

**Comment by SergeyPilipenko** [comment]
2.3.55-beta проверено в даталайне
