### ISSUE TITLE
[Uni Blocks] Доработка блока Фильтрация для ипотеки (Filtration)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1373]
Необходимо доработать блок Filtration следующим образом:

1) Изменить логику, чтобы в рамках одной группы фильтров поиск среди вложенных продуктовых плиток был с использованием оператора “ИЛИ”, а между разными группами фильтров - оператор “И”

2) Добавить возможность добавления вкладок над блоком фильтрации:
    - вид вкладок как в блоке Tabs с режимом вкладок = "По ширине экрана"
    - настройки для вкладок - "Тег" и "Заголовок" (аналогично как в блоке Tabs при выборе значения "Группа" как показано на _Скрине_ ниже)
  ![Image](https://user-images.githubusercontent.com/112703510/220130829-f27fdd9b-97c1-4348-b398-fe419e09a140.png)
    - добавить в настройки вкладки возможность отображения/скрытия фильтров (область, которую показываем или скрываем показана на _Скрине_ ниже)
      - название поля: "Показывать фильтры"
      - тип компонента: чекбокс
      - возможные значения:
        - true (= фильтры показываются на вкладке)
        - false (= фильтры не отображаются на вкладке)
      - значение по умолчанию: true
![Image](https://user-images.githubusercontent.com/112703510/220136982-eb989f33-604b-4a9c-8a7c-a732fe38e8c4.png)

**Comment by klapada** [comment]
Договорились о следующем:
1) фильтры будут отображаться на всех вкладках, поэтому чекбокс для отображения/скрытия фильтров не нужен
2) в настройках вкладок нужно добавить:
- название вкладки
- выбор подходящих фильтров
3) при переходе на вкладки включаются соответствующие фильтры, а если начать менять заданную по умолчанию фильтрацию, то активной становится вкладка со всеми программами, но включенные фильтры при этом сохраняются

**Comment by klapada** [comment]
Договорились в подборщике по вкладам в настройках плитки добавить для поля "Сумма" диапазон "от" и "до" по аналогии с полем "Срок":
- текущее поле с суммой будет как "Максимум"
- в поле "Минимум" значение по умолчанию "500"
При необходимости данные значения можно изменить


![Image](https://user-images.githubusercontent.com/112703510/228568003-f3a5ec70-6afc-4631-9c35-4660cd137c8f.png)

**Comment by klapada** [comment]
Необходимо в подборщике вкладов внести следующие изменения:
1) В инпуте "Сумма" выводить по умолчанию значения = 10000р (сейчас выводится 500р)
2) Изменить текст под полем "Срок" со значения "До 3 лет" на "До 5 лет" 

<img width="376" alt="Screenshot 2023-04-05 at 12 21 39" src="https://user-images.githubusercontent.com/112703510/230039168-730d9061-e2e6-4706-bb79-7b8c3ce4dcfb.png">

**Comment by SergeyPilipenko** [comment]
2.3.67-beta проверено
