### ISSUE TITLE
[Uni Blocks] Мобильный блок BenefitsBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1380]
Необходимо реализовать мобильный блок BenefitsBlock как на _Скринах_ ниже.

Настройки блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/221588195-85e35358-0265-4d4a-ad9f-5b0eb3b88813.png)
_Скрин 1. Вид блока только с названием преимуществ ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17824%3A109011&t=a28r3ll4BloCrl1b-4))_

![Image](https://user-images.githubusercontent.com/112703510/221588237-86705308-a55b-4500-ac8f-62666e9334f8.png)
_Скрин 2. Вид блока с названием и описанием преимуществ ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17833%3A187199&t=eUgxFU7NqITuRzTP-4))_

**Comment by SergeyPilipenko** [comment]
2.3.61-beta проверено в даталайне
