### ISSUE TITLE
[Uni Blocks] Мобильный блок CarouselTariffsCard

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1386]
Необходимо реализовать мобильный блок CarouselTariffsCard как на _Скринах 1-2_ ниже.

Настройки блока аналогичны десктопному.

Если карточек >1, то вид как на _Скрине 3_ и не зависит от того, вставлены ли карточки внутрь блока Карусель или нет.

![Image](https://user-images.githubusercontent.com/112703510/221780728-4d7574bd-b5b3-4614-8218-3b53a058cfe7.png)
_Скрин 1. Вид блока, когда Заголовок и Описание ячейки на одной строке ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17637%3A126065&t=XX8czAZ1IR2j9nrV-4))_

![Image](https://user-images.githubusercontent.com/112703510/221785227-18d390c8-7cb1-4773-9e04-a10d68f52e6d.png)
_Скрин 2. Вид блока, когда Заголовок и Описание ячейки друг под другом ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17833%3A130510&t=XX8czAZ1IR2j9nrV-4))_

![Image](https://user-images.githubusercontent.com/112703510/221792086-e16114e7-9a3c-4ec0-8c91-3e3a6916eda9.png)
_Скрин 3. Вид карточек, если их >1 ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17637%3A126065&t=XX8czAZ1IR2j9nrV-4))_

**Comment by Guzlik123** [comment]
2.3.57-beta

Проверено в даталайне

**Comment by Guzlik123** [comment]
2.3.57-beta

Проверено в даталайне
