### ISSUE TITLE
[Uni Blocks] Мобильный блок VerticalLayout

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1391]
Реализовать мобильный блок Вертикальный компоновщик аналогично десктопному.

**Comment by Longraf** [comment]
Так вроде уже реализованно, просьба проверить

**Comment by SergeyPilipenko** [comment]
2.3.54-beta Вертикальный компоновщик и вложенные блоки не отображаются на портале
КР: https://10.80.4.9:81/#2447/content%2Fveb-stranica_pokaz1.page.json 
Портал: https://10.80.4.9/veb-stranica_pokaz1#

**Comment by artem1426** [comment]
Проблем не обнаружил, нужно проверить что актуальный билд на портале.

**Comment by SergeyPilipenko** [comment]
2.3.57-beta проверено в даталайне
