### ISSUE TITLE
[Uni Blocks] Мобильный блок Footer

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1394]
Необходимо реализовать мобильный блок Footer как на _Скрине_ ниже.

Настройки блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/221841749-ce5f476a-8142-4069-b70b-ad1bb8980ecd.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A23511&t=XX8czAZ1IR2j9nrV-4))_

**Comment by SergeyPilipenko** [comment]
2.3.57-beta проверено в даталайне
