### ISSUE TITLE
[Uni Blocks] Таблица внутри мобильного блока TariffsTable

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1395]
Необходимо реализовать таблицу внутри мобильного блока TariffsTable как на _Скринах_ ниже.

Данные подтягиваются из справочников как для десктопного блока.

Для просмотра всей таблицы используется горизонтальный скролл. Скроллится каждая таблица по отдельности и вся область, которая выделена красным на _Скрине 2_, т.е. никакая ее часть не фиксируется на месте.

Связана с задачей https://github.com/redneckz/wildless-cms-uni-blocks/issues/1392

![Image](https://user-images.githubusercontent.com/112703510/221861066-834f216b-ac23-495e-b423-890bc45b78d5.png)
_Скрин 1. Вид блока со свернутой таблицей ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17386%3A80490&t=XX8czAZ1IR2j9nrV-4))_

![Image](https://user-images.githubusercontent.com/112703510/221916796-8ae0fb57-d867-4a05-a5a1-e8010b168147.png)
_Скрин 2. Вид блока с развернутой таблицей ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17239%3A150052&t=nwczdp7Yqj0alySu-4))_

**Comment by shh8te** [comment]
вот тут добавлены мобильные компоненты `feature/1395-tariffs-table-mobile`, попробовал переделать дату чтобы отрендерить таблицу используя overflow-y-scroll, не совсем удобно получается, решили попробовать добавить `useSwipeListScroll`, к сожалению доделать не успел

**Comment by Longraf** [comment]
![image](https://user-images.githubusercontent.com/32570545/231392777-34c0bce9-8633-44e3-9d2c-55fde05a32da.png)
Сворачинание/разворачивание внутренней таблице решено упразднить (согласовано с Ксенией)

**Comment by Longraf** [comment]
![image](https://user-images.githubusercontent.com/32570545/231393004-919beb1b-b7b7-4921-bca4-3cf21a58e7d7.png)
Кнопки везде приведены к одному виду 
![image](https://user-images.githubusercontent.com/32570545/231393040-2bb40847-661b-4466-ad8b-542b29bc1ecf.png)
Скачать в PDF перенесено вправо от курса валют в соответствии с десктопным вариантом 
![image](https://user-images.githubusercontent.com/32570545/231393327-4cf70774-7917-421d-8b20-329990f623a3.png)

**Comment by SergeyPilipenko** [comment]
проверено в даталайне
