### ISSUE TITLE
[Uni Blocks] Мобильный блок PictureText

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1397]
Необходимо реализовать мобильный блок PictureText как на _Скринах_ ниже.

Настройки блока аналогичны десктопному.

При наличии картинки в десктопном блоке в мобильной версии она всегда находится внизу под текстом. При необходимости Редактор будет ее сам удалять, если в мобильной версии картинка не нужна.

![Image](https://user-images.githubusercontent.com/112703510/221869907-4f26953a-f22d-4eb1-8d2f-39c230054445.png)
_Скрин 1. Вид блока с данными по суммам ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17407%3A86562&t=XX8czAZ1IR2j9nrV-4))_

![Image](https://user-images.githubusercontent.com/112703510/221874162-191a5efa-74cf-46d1-91bc-78fa29903b7b.png)
_Скрин 2. Вид блока с картинкой и без списка ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17491%3A119173&t=XX8czAZ1IR2j9nrV-4))_

![Image](https://user-images.githubusercontent.com/112703510/221875658-08d67745-e4de-4ca4-8c36-67cd840806f9.png)
_Скрин 3. Вид блока с картинкой и списком ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17884%3A136411&t=XX8czAZ1IR2j9nrV-4))_

**Comment by Longraf** [comment]
Иконки преимуществ в десктопе и мобилке сделаны 44px (согласовано с Эльдаром)
Горизонтальные отступы в десктопе сделаны как и у всех блоков 48px, были 96px (согласовано с Эльдаром)
Отступ от преимуществ вверх 24px (согласовано с Эльдаром)

**Comment by SergeyPilipenko** [comment]
2.3.57-beta проверено в даталайне
