### ISSUE TITLE
[Uni Blocks] Объединение блоков ProductBlock и BusinessBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1400]
При объединении 2х блоков оставить только ProductBlock со следующими доработками:
1) если ширина блока <= 6 колонок, то вид как на _Скрине 1_ ниже, а именно:
    - картинка располагается сверху
    - пункты списка друг под другом
    - кнопки, если их >1, располагаются по горизонтальной оси, если места достаточно, а если не хватает, то по вертикальной оси
2) убрать из настроек поле "Количество преимуществ в строке" и добавить логику перехода правого крайнего преимущества на следующую строку (_Скрин 2_) в случае, если не хватает места на одной строке (максимум на одной строке 3 преимущества, минимум - 1)

![Image](https://user-images.githubusercontent.com/112703510/221982101-7b046bb6-4952-462c-82e0-c1e2e777ee96.png)
_Скрин 1. Вид блока, если ширина <= 6 колонок ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=17078%3A113674&t=w995ayPdgf3ZDdFN-4))_

![Image](https://user-images.githubusercontent.com/112703510/221984973-93ecf325-32df-45db-a4c1-c9ebfccc4300.png)
_Скрин 2. Переход преимущества на следующую строку ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=19352%3A37805&t=w995ayPdgf3ZDdFN-4))_

**Comment by SergeyPilipenko** [comment]
2.3.57-beta проверено в даталайне
