### ISSUE TITLE
[Uni Blocks] Объединение блоков CarouselProductCard и CarouselEventCard

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1403]
При объединении 2х блоков оставить только CarouselProductCard и добавить в настройки возможность растягивания картинки на всю ширину карточки:
- название поля: "Изображение на всю ширину"
- тип компонента: чекбокс
- возможные значения:
  - true (= Изображение растянуто на всю ширину карточки как на _Скрине 1_)
  - false (= Изображение вида как сейчас в CarouselProductCard)
- значение по умолчанию: false

![Image](https://user-images.githubusercontent.com/112703510/222117641-28494b42-7838-485d-a934-4f2ab1b469f6.png)
_Скрин. Виб блока с картинкой на всю ширину карточки ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=21146%3A31890&t=hOQqgL2EpM4Ld0bx-4))_

**Comment by Irinaristova** [comment]
Договорились с Ксенией:  у новой объединенной карточки останутся стили CarouselProductCard, между заголовком, описанием, списком и доп. описанием margin = 8px. Для воспроизведения примера карточки эвентов необходимо добавить заголовок и доп. описание.

**Comment by Guzlik123** [comment]
2.3.59-beta

Проверено в даталайне

**Comment by SergeyPilipenko** [comment]
2.3.66-beta проверено в даталайне
