### ISSUE TITLE
[Uni Blocks] Мобильный блок RollupItem

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1405]
Необходимо реализовать мобильный блок RollupItem как на _Скрине 1_ ниже.

Настройки блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/222130345-6943ebbe-a315-4247-b349-da13b5a92ca4.png)
_Скрин 1. Вид блока в закрытом виде ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A25324&t=M03q7oJFWHyjWkyk-4))_

![Image](https://user-images.githubusercontent.com/112703510/222125752-8a0b50fc-7fad-4501-9554-7d1907acb6b2.png)
_Скрин 2. Вид блока с вложенным TextBlock ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A25324&t=M03q7oJFWHyjWkyk-4))_

![Image](https://user-images.githubusercontent.com/112703510/222127088-212c15c8-3315-40dd-84f2-bd7a2eb52d49.png)
_Скрин 3. Вид блока с вложенным TextBlock (список с буллитами с помощью rich text) ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17239%3A146014&t=M03q7oJFWHyjWkyk-4))_

![Image](https://user-images.githubusercontent.com/112703510/222126388-03323601-f97d-4afb-84d2-4fbdf54a880d.png)
_Скрин 4. Вид блока с вложенным LinkDocs ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17943%3A162599&t=M03q7oJFWHyjWkyk-4))_

**Comment by Longraf** [comment]
Иконки сделать везде (desktop/mobile) 44px
Отступы сверху/снизу изменить на 20px 
![image](https://user-images.githubusercontent.com/32570545/224241462-961213e9-ddc5-4c31-9cd1-430312e0888e.png)
Всё согласовано с Эльдаром

**Comment by SergeyPilipenko** [comment]
2.3.57-beta проверено в даталайне
