### ISSUE TITLE
[Uni Blocks] Мобильный блок CarouselProgramsCard

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1414]
Необходимо реализовать мобильный блок CarouselProgramsCard как на _Скрине_ ниже.

Настройки блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/222451656-f6b85e63-4a20-4a09-b0fd-86112085ed2d.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17833%3A200445&t=GFevD1zIUkAWripA-4))_

**Comment by Guzlik123** [comment]
2.3.58-beta

Проверено в даталайне
