### ISSUE TITLE
[Uni Blocks] Мобильный блок Header

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1419]
1) Необходимо реализовать мобильный блок Header как на _Скринах 1-3_ ниже.

2) Кнопка "Войти" аналогична кнопке "Интернет-банк" в десктопном блоке Header.

3) Логотип на _Скрине 1_ и _3_ кликабелен и ведет на Главную разводящую страницу (также как в десктопном блоке).

4) Настройки блока аналогичны десктопному, но необходимо добавить новое поле (_Скрин 4_):
    - тип компонента: дропдаун
    - возможные значения:
      - Не выбрано
      - Название
      - Кнопка возврата
    - значение по умолчанию: "Не выбрано"
    - при выборе значения "Не выбрано" вид шапки как на _Скрине 3_
    - при выборе значения "Название":
      - появляется поле:
        - название поля: "Текст"
        - тип компонента: текстовое поле
        - значение по умолчанию: null
      - вид шапки как на _Скрине 1_, где по центру выводится значение, указанное в поле **Текст**
    - при выборе значения "Кнопка возврата":
      - появляются 2 поля:
        - Текст
          - название поля: "Текст"
          - тип компонента: текстовое поле
          - значение по умолчанию: null
        -  URL
          - название поля: "URL"
          - тип компонента: текстовое поле
          - значение по умолчанию: null
      -  вид шапки как на _Скрине 2_, где по левому краю выводится значение, указанное в поле **Текст**, а при клике на него осуществляется переход на страницу, указанную в поле **URL**
  
  

![Image](https://user-images.githubusercontent.com/112703510/222161066-0eab428a-5ee4-4402-98e5-9284b5cabd15.png)
_Скрин 1. Вид блока с названием раздела ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A25260&t=M03q7oJFWHyjWkyk-4))_

![Image](https://user-images.githubusercontent.com/112703510/222161296-7dc95d2a-b1f3-4325-8bde-83de36d991fe.png)
_Скрин 2. Вид блока с кнопкой возврата ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A25324&t=M03q7oJFWHyjWkyk-4))_

![Image](https://user-images.githubusercontent.com/112703510/222161522-36dfba1e-e00e-45f9-8619-f07c4c0d6486.png)
_Скрин 3. Вид блока с лого ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17407%3A89265&t=M03q7oJFWHyjWkyk-4))_

![Image](https://user-images.githubusercontent.com/112703510/223382970-0b137a73-feb5-4377-8379-f9abaf067c90.png)
_Скрин 4. Новое поле_

**Comment by klapada** [comment]
После обсуждения пришли к следующему решению:
1) на главных разводящих страницах основных 4х разделов (Частным клиентам/Бизнес-клиентам/О Банке/Экосистема Своё) в Шапке выводить лого и кнопку "Войти" (макет)

2) на всех остальных страницах - кнопку "Вернуться назад", ведущаую на предыдущую страницу (аналогично браузерной) и кнопку "Войти" (макет)
<img width="405" alt="Screenshot 2023-03-20 at 16 17 28" src="https://user-images.githubusercontent.com/112703510/226350467-8c1898e5-7422-4bc4-b1f7-2d907a20f0a9.png">

**Comment by SergeyPilipenko** [comment]
2.3.58-beta проверено в даталайне
