### ISSUE TITLE
[Uni Blocks] Мобильный блок ButtonBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1420]
1) Необходимо реализовать мобильный блок ButtonBlock как на _Скрине_ ниже.

2) Настройки блока аналогичны десктопному.

3) Кнопка занимает всю ширину блока.

4) Если кнопок > 1, то они располагаются друг под другом как на _Скрине_ ниже.

![Image](https://user-images.githubusercontent.com/112703510/222484993-fe272661-026f-4802-8a7b-14a2a91c4bac.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A25260&t=GFevD1zIUkAWripA-4))_

**Comment by SergeyPilipenko** [comment]
2.3.57-beta проверено в даталайне
