### ISSUE TITLE
[Uni Blocks] Мобильный блок RepresentativeOfficeInfo

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1421]
Необходимо реализовать мобильный блок RepresentativeOfficeInfo как на _Скрине_ ниже.

Настройки блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/222642410-2dc2e9f9-9fcc-493c-9936-94acca7956ff.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17538%3A90824&t=OjzPmBFoGubpLXst-4))_

**Comment by Guzlik123** [comment]
2.3.62-beta

Проверено в даталайне
