### ISSUE TITLE
[Uni Blocks] Мобильный блок CarouselCatalogCard

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1424]
Необходимо реализовать мобильный блок CarouselCatalogCard как на _Скрине_ ниже.

Настройки блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/222667466-6dcf40a3-b056-4d1a-8a04-7a210da4f891.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17407%3A99937&t=OjzPmBFoGubpLXst-4))_

**Comment by artem1426** [comment]
Обновлённый мобильный макет
![image](https://user-images.githubusercontent.com/76048968/225864200-f9649a43-7afe-4ac6-bd43-c6d373ddc8fd.png)

**Comment by artem1426** [comment]
![image](https://user-images.githubusercontent.com/76048968/225890092-4dec4fa7-17e1-4c76-9f7c-3fded09c76b6.png)

**Comment by SergeyPilipenko** [comment]
2.3.58-beta проверено в даталайне
