### ISSUE TITLE
[Uni Blocks] Мобильный блок ProductBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1426]
Необходимо реализовать мобильный блок ProductBlock как на _Скринах_ ниже, но только после оптимизации в рамках задачи [#1400](https://github.com/redneckz/wildless-cms-uni-blocks/issues/1400)

Настройки блока аналогичны десктопному за исключением:
- чекбокс "Картинка справа/текст слева" работает несколько иначе:
  - если true, то картинка располагается сбоку справа как на _Скрине 1 и 3_
  - если false, то снизу над кнопками как на _Скрине 2_
- нет подраздела "Кнопка возврата" и всех полей данного подраздела
- нет поля "Количество преимуществ в строке" (поле должно быть удалено из настроек десктопного блока в рамках задачи [#1400](https://github.com/redneckz/wildless-cms-uni-blocks/issues/1400))

![Image](https://user-images.githubusercontent.com/112703510/222702854-2f1eee20-b021-43e0-ad87-a2513968001e.png)
_Скрин 1. Вид блока с картинкой сбоку и цветом иконки = "Цветной" ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A25260&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222704604-01fc6cac-fb0b-4ee2-8645-8b0d5ba30a9c.png)
_Скрин 2. Вид блока с картинкой снизу и цветом иконки = "по умолчанию" ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17566%3A126978&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222706685-97b207b8-92e5-4a45-972c-a1708c76976a.png)
_Скрин 3. Вид блока с картинкой сбоку и без преимуществ ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17239%3A201416&t=OjzPmBFoGubpLXst-4))_

**Comment by Guzlik123** [comment]
2.3.65-beta

Проверено в даталайне
