### ISSUE TITLE
[Uni Blocks] Мобильный блок ProductTile

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1427]
Необходимо реализовать мобильный блок ProductTile как на _Скринах_ ниже, но только после оптимизации в рамках задачи [#1402](https://github.com/redneckz/wildless-cms-uni-blocks/issues/1402)

Настройки блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/222711385-e8eb7867-a4db-4626-b2e8-9f22ea0f2b1f.png)
_Скрин. Вид блока с пунктами и картинкой ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17637%3A117050&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222712407-0254ee1b-fe12-49a2-a086-ebee96310663.png)
_Скрин 2. Вид блока без пунктов ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17637%3A108135&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222712904-444281bc-1cff-49bb-899b-c08b7baa137e.png)
_Скрин 3. Вид блока с пунктами и без картинки ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17239%3A210793&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222713500-ff0f3ed4-d6ed-4c7a-8404-b08fa2f69000.png)
_Скрин 4. Вид блока с пунктами, без картинки и с кнопкой ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17239%3A82810&t=OjzPmBFoGubpLXst-4))_

**Comment by SergeyPilipenko** [comment]
2.3.62-beta проверено в даталайне
