### ISSUE TITLE
[Uni Blocks] Мобильный блок CarouselProductCard

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1428]
Необходимо реализовать мобильный блок CarouselProductCard как на _Скринах_ ниже, но только после оптимизации в рамках задачи [#1403](https://github.com/redneckz/wildless-cms-uni-blocks/issues/1403)

Настройки блока аналогичны десктопному, но нужно добавить новое поле для выбора расположения картинки:
- название поля: "Картинка сверху над текстом"
- тип компонента: чекбокс
- возможные варианты:
  - true (= картинка располагается сверху как показано на _Скрине 1_)
  - false (= картинка располагается снизу над кнопками как на _Скрине 2_)
- значение по умолчанию: false

![Image](https://user-images.githubusercontent.com/112703510/222724795-495b6a94-af0f-4a37-8246-7b9655ff9fea.png)
_Скрин 1. Вид блока с картинкой сверху ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=18020%3A157801&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222818031-a1c11a06-94df-480a-adec-30bfacc23090.png)
_Скрин 2. Вид блока с картинкой снизу и без описания ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17943%3A147032&t=80VZ4l93g795tzEo-4))_

![Image](https://user-images.githubusercontent.com/112703510/222820004-f9ce10a2-56a3-435d-a70f-3c0fed3679fd.png)
_Скрин 3. Вид блока с картинкой снизу и с описанием ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17380%3A91316&t=80VZ4l93g795tzEo-4))_

![Image](https://user-images.githubusercontent.com/112703510/222821252-98d687b7-c67b-4699-a792-a6705a3569c1.png)
_Скрин 4. Вид блока с картинкой снизу и с кнопкой ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17844%3A115989&t=80VZ4l93g795tzEo-4))_

**Comment by Guzlik123** [comment]
2.3.60-beta

Проверено в даталайне
