### ISSUE TITLE
[Uni Blocks] Мобильный блок Carousel

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1429]
1) Необходимо реализовать мобильный блок Carousel.

2) Настройки блока аналогичны десктопному.

3) Вид каруселей с разными карточками:
- CarouselRecommendationCard показан на _Скринах 1.1-1.2_ (макеты десктопного: [без кнопки](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=9643%3A11894389&t=1DBKumAbhIiBpzVm-4) и [с кнопкой](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=7991%3A158693&t=1DBKumAbhIiBpzVm-4))
- CarouselProgramsCard показа на _Скрине 2_ (макет десктопного по [ссылке](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=17078%3A110846&t=jxt7FZVgkLdTE1Vp-4))
- CarouselBankHistoryCard показан на _Скрине 3_  (макет десктопного по [ссылке](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=22504%3A20821&t=5htTNvAACCBjmvFV-4))
  - если в блоке Carousel >1 карточки, то добавляются табы, название которых соответствует Заголовкам карточек, а кол-во табов = кол-ву карточек
- CarouselCatalogCard показан на _Скрине 4_ (макет десктопного по [ссылке](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=8320%3A150862&t=1DBKumAbhIiBpzVm-4))
- CarouselCard показан на _Скрине 5_ (макет десктопного по [ссылке](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=22504%3A20821&t=5htTNvAACCBjmvFV-4))
- CarouselProductCard показан на _Скринах 6.1-6.2_ (макеты десктопного: с картинкой [сверху](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=20663%3A154724&t=1DBKumAbhIiBpzVm-4) и [снизу](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=22628%3A200586&t=1DBKumAbhIiBpzVm-4))
- CarouselTariffsCard показан на _Скрине 7_ (макет десктопного по [ссылке](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=17078%3A113674&t=jxt7FZVgkLdTE1Vp-4))

![Image](https://user-images.githubusercontent.com/112703510/222682532-424bd003-b98b-4142-81f6-8b4a8f7f7d24.png)
_Скрин 1.1. Вид CarouselRecommendationCard без кнопок ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A25260&t=XX8czAZ1IR2j9nrV-4))_

![Image](https://user-images.githubusercontent.com/112703510/222684030-39d32603-288a-4b7c-8bb4-dfc5ac300f7b.png)
_Скрин 1.2. Вид CarouselRecommendationCard с кнопками ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A23511&t=XX8czAZ1IR2j9nrV-4))_

![Image](https://user-images.githubusercontent.com/112703510/222684271-c0c3fc78-eec4-4d7e-931c-bfb8643ac0c8.png)
_Скрин 2. Вид CarouselProgramsCard ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17833%3A200445&t=GFevD1zIUkAWripA-4))_

![Image](https://user-images.githubusercontent.com/112703510/222684478-5bee03ed-066b-4580-94fa-aaa195a4fd55.png)
_Скрин 3. Вид CarouselBankHistoryCard ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17885%3A123518&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222684559-9c3f30e4-f506-456b-a1ae-9fd8647cd68c.png)
_Скрин 4. Вид CarouselCatalogCard ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17407%3A99937&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222684639-c56f85cc-be4f-48b6-a8ce-c19e187a4396.png)
_Скрин 5. Вид CarouselCard ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17844%3A115989&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222724902-92a91eb2-4cc2-43a9-9fa1-a2cb9a112349.png)
_Скрин 6.1. Вид CarouselProductCard с картинкой сверху ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=18020%3A157801&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222817695-b72e9c24-9b45-4c81-8c7a-8277226642d5.png)
_Скрин 6.2. Вид CarouselProductCard с картинкой снизу ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17943%3A147032&t=80VZ4l93g795tzEo-4))_

![Image](https://user-images.githubusercontent.com/112703510/222825387-57ffc5de-1176-4c64-9177-e0a9f4256ade.png)
_Скрин 7. Вид CarouselTariffsCard ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A29042&t=80VZ4l93g795tzEo-4))_

**Comment by SergeyPilipenko** [comment]
2.3.61-beta проверено в даталайне
