### ISSUE TITLE
[Uni Blocks] Мобильный блок SafeDepositRental

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1430]
1) Необходимо реализовать мобильный блок SafeDepositRental как на _Скрине 1_ ниже.

2) Настройки блока аналогичны десктопному.

3) При клике в блоке на кнопку "Офисы на карте" снизу под формой отображается карта с точками офисов как на _Скрине 2_ ниже.

Ссылка на [макет десктопного блока](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=8009%3A288746&t=11z7jipcFXyAIoKZ-4).

![Image](https://user-images.githubusercontent.com/112703510/222829342-259bb578-bd97-4dba-8cf5-3b22fc7d6c82.png)
_Скрин 1. Вид блока без карты ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17407%3A93378&t=80VZ4l93g795tzEo-4))_

![Image](https://user-images.githubusercontent.com/112703510/222828978-ad8d0fb0-4ea6-406d-81f4-ea7866dfee28.png)
_Скрин 2. Виб блока с картой ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17407%3A97423&t=80VZ4l93g795tzEo-4))_

**Comment by Guzlik123** [comment]
Проверено в ИП2.0
