### ISSUE TITLE
[Uni Blocks] Мобильный блок CardTransfer

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1431]
Необходимо реализовать мобильный блок CardTransfer как на _Скрине_ ниже.

Настройки блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/222830874-b24e626b-e49b-45a4-adc9-af1115d739d4.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17407%3A102842&t=80VZ4l93g795tzEo-4))_

**Comment by redneckz** [comment]
- Меняется паддинг и типографика.
- И то и другое лучше всего завязывать на конфигурацию tailwind. То есть надо завести именованный паддинг и поправить настройку типографику для мобильного конфига `mobile/tailwind.config.cjs`
- Перенос символа рубля из поля в label - пока не делать - выглядит странно

**Comment by SergeyPilipenko** [comment]
2.3.57-beta проверено в даталайне
