### ISSUE TITLE
[Uni Blocks] Мобильный блок ApplicationForm (заявка ВЭД)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1432]
1) Необходимо реализовать в мобильном блоке ApplicationForm заявку для ВЭД (вид заявки = "ВЭД") как на _Скринах 1-2_ ниже, но только после доработки десктопной формы в рамках задачи [#1313](https://github.com/redneckz/wildless-cms-uni-blocks/issues/1313)

2) Настройки блока аналогичны десктопному.

3) Валидация полей и отправка заявки по аналогии с десктопом.

4) Вид сообщений при успехе/ошибке после отправки заявки показан на _Скринах 3-4_

![Image](https://user-images.githubusercontent.com/112703510/223066567-a84719b3-c22c-424e-b06d-34111f7b4abb.png)
_Скрин 1. Вид блока с видом заявки = "ВЭД", когда "Валютный контроль" = false ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=18761%3A165331&t=RMrlpnnJfie2DJJ7-4))_

![Image](https://user-images.githubusercontent.com/112703510/223066934-8cc07371-d455-43d8-99c9-262209115270.png)
_Скрин 2. Вид блока с видом заявки = "ВЭД", когда "Валютный контроль" = true ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17833%3A130510&t=RMrlpnnJfie2DJJ7-4))_

![Image](https://user-images.githubusercontent.com/112703510/222677039-02f51a3e-84a8-4a54-aed2-d5814765634d.png)
_Скрин 3. Вывод сообщения при успешной отправке заявки ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17173%3A29253&t=OjzPmBFoGubpLXst-4))_

![Image](https://user-images.githubusercontent.com/112703510/222677221-a2027441-65b7-4af6-83a3-b9adf0dc19c0.png)
_Скрин 4. Вывод сообщения при неуспешной отправке заявки ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=18747%3A165097&t=OjzPmBFoGubpLXst-4))_

**Comment by Guzlik123** [comment]
2.3.63-beta

Проверено в даталайне
