### ISSUE TITLE
[Uni Blocks] Мобильный блок CarouselLinks

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1437]
Необходимо реализовать мобильный блок CarouselLinks как на _Скрине_ ниже.

Настройки блока аналогичны десктопу (макет десктопного блока по [ссылке](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=22504%3A20821&t=PQWJ7nFOEBmjCOzt-4)).

![Image](https://user-images.githubusercontent.com/112703510/223420961-0cb103a9-628a-43a7-b0f3-881eb830d1db.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17885%3A123518&t=QtTjRSVI88WW22B0-4))_

**Comment by Guzlik123** [comment]
2.3.62-beta

Проверено в даталайне
