### ISSUE TITLE
[Uni Blocks] Мобильный блок BonusBenefitsBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1440]
1) Необходимо реализовать мобильный блок BonusBenefitsBlock как на _Скринах_ ниже.

2) Настройки блока аналогичны десктопному:
    - если в блоке у самих бонусов был добавлен Заголовок, то вид как на _Скрине 1_
    - если в блоке у бонусов было добавлено Описание, то вид как на _Скрине 2_

![Image](https://user-images.githubusercontent.com/112703510/223417417-97448634-7d6c-4b18-b2f5-ba3b02b5e0ca.png)
![Image](https://user-images.githubusercontent.com/112703510/223411834-606618bc-e14e-410f-8333-3cc34028194b.png)
_Скрин 1. Вид блока с Заголовком у бонусов ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17943%3A147032&t=q7Sga1TuBiHGiV22-4))_

![Image](https://user-images.githubusercontent.com/112703510/223417554-17113b14-4844-49c6-a2cb-24439cb81377.png)
![Image](https://user-images.githubusercontent.com/112703510/223412335-b33e9c76-5bc1-4a8c-87f7-3096febc753e.png)
_Скрин 2. Вид блока с Описанием у бонусов ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17533%3A93125&t=q7Sga1TuBiHGiV22-4))_

**Comment by SergeyPilipenko** [comment]
2.3.57-beta проверено в даталайне
