### ISSUE TITLE
[Uni Blocks] Мобильный блок Меню

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1441]
1) Необходимо реализовать панель как на _Скрине 1_ ниже, которая будет зафиксирована в нижней части экрана

2) Количество кнопок в панели фиксированное и всегда = 5:
    - кнопка "Меню" не редактируемая и работает следующим образом:
      - при клике открывается всплывающее окно как на _Скрине 2_, в котором:
        - есть названия разделов в виде табов (список соответствует разделам 1го уровня из структуры сайта):
          - Частным клиентам
          - Бизнес клиентам
          - О Банке
          - Экосистема Своё
        - для каждого раздела список подразделов соответствует списку 2го уровня из структуры сайта
        - при клике на подраздел открывается соответствующая страница выбранного подраздела
      - для закрытия меню - клик на "крестик" в правом верхнем углу
    - кнопки слева/справа от "Меню"
      - редактируемые
      - должны задаваться для каждого раздела по отдельности
      - должны иметь следующие настройки:
        - Загрузка картинки
        - Текст на кнопке
        - URL
    

![Image](https://user-images.githubusercontent.com/112703510/223229549-6f80bbe1-83b0-4451-9360-2308e112325e.png)
_Скрин 1. Вид панели ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17347%3A80730&t=QtTjRSVI88WW22B0-4))_

![Image](https://user-images.githubusercontent.com/112703510/223230118-1bf306e6-26e8-421e-ac6e-40fc8d4880e0.png)
_Скрин 2. Вид всплывающего меню_

**Comment by Guzlik123** [comment]
2.3.65-beta

Проверено в даталайне
