### ISSUE TITLE
[Uni Blocks] Изменение текста с контактами в Подвале (Footer)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1474]
Необходимо изменить текст с контактами в Footer согласно _Скрину_ ниже (область выделена красным).

![Image](https://user-images.githubusercontent.com/112703510/225006088-b8af30b6-08b3-4656-b6d8-89bd2b467a5f.png)
_Скрин. Контакты ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=16376%3A105348&t=nR0InPUO6AgqLqgA-4))_

**Comment by SergeyPilipenko** [comment]
2.3.79-beta исправлено в даталайне
