### ISSUE TITLE
e2e. Кабинет редактора. Блок Документы. Менеджер аттачей. Замечания

### ISSUE THREAD

**Issue by SergeyPilipenko** [redneckz/wildless-cms-uni-blocks#1494]
2.3.56-beta
https://10.80.4.9:81/#2447/content%2Ftest%2Fveb-stranica_pokaz1.page.json
Задача: https://github.com/redneckz/temp_wcms/issues/880

1. Если публиковать новую страницу в папку, а не корень, то прикрепленный документ в блоке Документы не сохраняется
2. Если переопубликовать документ из корня в папку, то прикрепленный документ в блоке Документы не сохраняется
3. Размер файла отображается только при первой загрузке в менеджер аттачей и выборе. Если выбирать ранее загруженный файл, то отображается знак ?
4. При выборе файла в менеджере аттачей поле Размер файла становится недоступным, нет возможности при необходимости вывести в блоке размер файла

![image](https://user-images.githubusercontent.com/22083206/225366637-6017b75c-2b38-4d86-bbde-88f8bfb88f8f.png)

**Comment by andreySimonenko** [comment]
Скрыл поле размер файла для прикрепленного документа. Размер файла не будет отображаться в КР (для файла), так как для этого необходимо каждый раз тянуть этот файл. Но будет выводится на портале, так как будет вычисляться на этапе сборки страницы.

**Comment by SergeyPilipenko** [comment]
2.3.61-beta исправлено в даталайне
