### ISSUE TITLE
e2e. Блок Сворачивающаяся секция. Заголовок в 2 строки выравнивается по центру

### ISSUE THREAD

**Issue by SergeyPilipenko** [redneckz/wildless-cms-uni-blocks#1495]
2.3.56-beta
https://10.80.4.9/natural/creditcards/amurskii-tigr#bnf

В блоке Сворачивающаяся секция если Заголовок в 2 строки, то текст выравнивается по центу и уменьшает размер иконки +. Необходимо выравнивание по левому краю

![image](https://user-images.githubusercontent.com/22083206/225368500-c6f67a66-affb-4310-9cdf-d9b1d64aab85.png)

**Comment by Guzlik123** [comment]
2.3.65-beta

Исправлено
