### ISSUE TITLE
e2e. Кабинет редактора. Моб Блок productGallery. В рабочей области кнопки не на всю ширину блока

### ISSUE THREAD

**Issue by Guzlik123** [redneckz/wildless-cms-uni-blocks#1510]
2.3.57-beta

https://10.80.4.9:81/#2447/content%2Fveb-stranica12344-28-02-2023-15-10-03.page.json
Задача: https://github.com/redneckz/wildless-cms-uni-blocks/issues/1337

В КР в в мобильной версии блока кнопка не на всю ширину блока
![image](https://user-images.githubusercontent.com/110792030/225874561-95af73d8-57bc-405c-87d7-ba410ffbc581.png)

**Comment by Irinaristova** [comment]
На данный момент после обсуждения решили оставить отображение кнопки в кр таким, как есть сейчас, поскольку  иначе в мобильном версии ломаются остальные блоки.
