### ISSUE TITLE
[Uni Blocks] Скрывать разделы 2го уровня в Шапке, но показывать их в Подвале

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1511]
Необходимо реализовать возможность скрытия определенных разделов 2го уровня в Шапке, а в Подвале их показывать.

Для этого в Карте сайта для каждого портала (Частные клиенты/Бизнес-клиенты/Экосистема Своё/О Банке) у каждой страницы портала (разделы 2го уровня) нужно добавить новое поле:
- название поля: "Показывать:"
- тип компонента: дропдаун
- возможные значения:
  - Только в Шапке
  - Только в Подвале
  - В Шапке и Подвале
- при выборе значения "Только в Шапке" отображается только в Шапке, а в Подвале скрыт
- при выборе значения "Только в Подвале" отображается только в Подвале, а в Шапке скрыт
- при выборе значения "В Шапке и Подвале" отображается как в Шапке, так и в Подвале

**Comment by SergeyPilipenko** [comment]
2.3.65-beta проверено в даталайне
