### ISSUE TITLE
e2e. Портал. Моб CarouselTariffsCard. Замечания 

### ISSUE THREAD

**Issue by Guzlik123** [redneckz/wildless-cms-uni-blocks#1515]
2.3.57-beta

https://10.80.4.9:81/#2447/content%2Fveb-stranica12344-28-02-2023-15-10-03.page.json

1. В блоке не отображаются добавленные картинки
2. Заголовок должен быть выравнен по левому краю, сейчас по центру
3. После перехода на центральную карточку стрелка окрашивается в зеленый цвет до следующего скролла, при скролле до конца вправо и потом влево так не происходит
4. Не работает настройка "Выравнивание заголовка" в настройке ячеек
5. Когда карточка находится на странице вне блока Карусель у нее не видно боковых рамок (скрин 2)

![image](https://user-images.githubusercontent.com/110792030/226313489-dde3744a-e461-415f-8d1a-314f54977e80.png)
![image](https://user-images.githubusercontent.com/110792030/226330888-30d67924-d20b-4178-92b0-58bd699ffc25.png)

**Comment by Longraf** [comment]
1-. Это из-за Трансформации SVG в растровый формат. На данный момент решение только не использовать SVG в таком кейсе
5-. Карточка не должна находиться вне блока карусель

**Comment by Guzlik123** [comment]
2.3.64-beta

Исправлено
