### ISSUE TITLE
Мобильная всплывающая форма для куки

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1517]
Необходимо реализовать мобильную форму для куки как на _Скрине_ ниже.

![Image](https://user-images.githubusercontent.com/112703510/226338189-b2929003-3f50-4255-88a6-72ea943f36fe.png)
_Скрин. Вид куки ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=18122-146268&t=xGEwXfQabgIXz4jj-4))_

**Comment by SergeyPilipenko** [comment]
2.3.58-beta проверено в даталайне
