### ISSUE TITLE
e2e. Портал. Мобильный блок CarouselCatalogCard. Замечания

### ISSUE THREAD

**Issue by SergeyPilipenko** [redneckz/wildless-cms-uni-blocks#1559]
2.3.58-beta
https://10.80.4.9/natural/payrings#cat
Задача: https://github.com/redneckz/wildless-cms-uni-blocks/issues/1424

1. Вертикальные отступы 24, по  макету 20
2. Размер шрифта Описания 20, по макету 16
3. Размер шрифта суммы 20, па макету 16
4. Кнопка должна быть прижата к низу карточки
5. Если в кнопке указана ссылка на страницу /слаг страницы с таргетом селф, то переход не работает

**Comment by rmrth** [comment]
1. заменил на ближайший именованный отступ в 16px, в мобильном конфиге нет отступа на 20px
3. используется ближайший именованный отступ, который подходит для десктопа и моб с шрифтом 16px
5. будет исправлено в отдельной [задаче](https://github.com/users/redneckz/projects/1/views/28?pane=issue&itemId=24213792)

**Comment by SergeyPilipenko** [comment]
2.3.61-beta исправлено не полностью
https://10.80.4.9/natural/payrings#cat
Не исправлен п4 Кнопка должна быть прижата к низу карточки: кнопки в карточках на разной высоте



![Image](https://user-images.githubusercontent.com/22083206/229650867-92b27752-7377-4029-9548-baa7365a5712.png)

**Comment by SergeyPilipenko** [comment]
2.3.65-beta исправлено в даталайне
