### ISSUE TITLE
e2e. Кабинет редактора. Блок табы. Не переключаются табы с типом таба "группа"

### ISSUE THREAD

**Issue by Guzlik123** [redneckz/wildless-cms-uni-blocks#1598]
2.3.60-beta

При нажатии на другую группу таба в кабинете редактора не просходит переключения между ними 

https://10.80.4.9:81/#3899/content%2Finsurance%2Frko-protection.page.json

**Comment by SergeyPilipenko** [comment]
2.3.61-beta исправлено в даталайне
