### ISSUE TITLE
e2e. Кабинет редактора. Мобильный блок. Не отображается QR код

### ISSUE THREAD

**Issue by Guzlik123** [redneckz/wildless-cms-uni-blocks#1603]
2.3.60-beta

В мобильном блоке не отображается QR код в кабинете редактора и на портале

https://10.80.4.9/business/insurance/farm-animals

**Comment by end0rfin** [comment]
Ошибка не воспроизводится.
https://10.80.4.9/business/insurance/farm-animals#
https://10.80.4.9:81/#3899/content%2Finsurance%2Ffarm-animals.page.json
Проверял здесь:
[Скрин даталайна](https://ibb.co/HhFnLhV)
[Скрин КР](https://ibb.co/m9xqGCc)

**Comment by Guzlik123** [comment]
2.3.65-beta

Исправлено
