### ISSUE TITLE
e2e. Портал. Калькулятор вкладов. Сломан ползунок суммы

### ISSUE THREAD

**Issue by SergeyPilipenko** [redneckz/wildless-cms-uni-blocks#1615]
2.3.61-beta
https://10.80.4.9/natural/deposits/my-moneybox#usl
https://beta.rshb.ru/natural/deposits/my-moneybox#

1. Значение по умолчанию 20000, при этом ползунок в крайнем левом положении на мин суммы
2. При измении сумм ползунком, он улетает в крайнее правое положение

**Comment by andreySimonenko** [comment]
Проблема возникла из-за дробного значения указанного для минимально возможной суммы. Договорились не использовать дробные значения для задания диапозонов.
