### ISSUE TITLE
[Uni Blocks] Доработка калькулятора депозитов для бизнеса (Calculator)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1630]
Необходимо в блоке Calculator для "Калькулятора вкладов - бизнес" внести следующие изменения:

#### 1) В настройках блока добавить 2 новых поля:
- Для возможности выравнивания всех вкладок:
  - название поля: "Выравнивание вкладок"
  - тип компонента: дропдаун
  - возможные значения:
    - По левому краю
    - По центру
  - значение по умолчанию: "По левому краю"
  - выбранное значение в дропдауне применяется сразу ко всем вкладкам, если их >1
  - на _Скрине 2_ ниже показан вариант выравнивания "По центру"
- Для выбора ставок для ЮЛ или ИП:
  - название поля: "Ставки для:"
  - тип компонента: дропдаун
  - возможные значения:
    - ЮЛ
    - ИП
  - значение по умолчанию: null
  - при выборе ЮЛ или ИП становится доступно поле "Адрес справочника"
  - если в дропдауне ничего не выбрано, то поле "Адрес справочника" скрыто

![Image](https://user-images.githubusercontent.com/112703510/231490610-2dc0be20-af16-4e37-bafc-28f1380d4c57.png)
_Скрин 1. Настройки блока_

#### 2) В блоке скорректировать верстку в части расположения радио как на _Скрине 2_ ниже, а также убрать чекбокс "ИП / малое предприятие"

![Image](https://user-images.githubusercontent.com/112703510/230345439-bcceebca-fed7-4c9e-80b1-3dc53e3946d5.png)
_Скрин 2. Вид блока ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=23121-93511&t=eKpB7F1UVsB4uDMN-4))_

**Comment by Guzlik123** [comment]
2.3.65-beta

Проверено в даталайне
