### ISSUE TITLE
[Uni Blocks] Доработка подборщика вкладов в части срока вклада (DepositFiltration)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1642]
Необходимо в блоке DepositFiltration реализовать следующее:

1) В настройках вложенной продуктовой плитки в подразделе "Срок":
    - добавить новое поле для возможности выбора справочника, а именно дропдаун "Адрес справочника" (аналогичное поле как в настройках блока Calculator)
    - убрать поля "Минимум" и "Максимум" для ввода диапазона срока

2) В настройках блока DepositFiltration в подразделе "Поле ввода срока" убрать поля "min" и "max"

3) Из справочников, привязанных ко всем вложенным продуктовым плиткам, должны подтягиваться для инпута "Срок" уникальные значения срока в месяцах в виде точек как на _Скрине_ ниже (по аналогии с инпутом "Срок" в Калькуляторе вкладов)

![Image](https://user-images.githubusercontent.com/112703510/231000842-785b7b15-c0c2-43ce-a161-27be473e5fdb.png)

4) При фильтрации отображаются только те продуктовые плитки, у которых выбранный срок присутствует в справочнике (остальные выбранные параметры также учитываются при фильтрации, но по ним логика не меняется)

**Comment by Guzlik123** [comment]
2.3.65-beta

Проверено в даталайне
