### ISSUE TITLE
[Uni Blocks] Мобильный блок ErrorBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1643]
Необходимо реализовать мобильный блок ErrorBlock как на _Скрине_ ниже.
Макет десктопного блока по [ссылке](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=23898-175881&t=SPsbh8i6yRiDJthB-4).

Настройки мобильного блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/230616861-8b9877fc-73dc-4c76-b06e-e2c269ee5aa0.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17943-127990&t=rMEeokccYV6cAU5V-4))_

**Comment by Longraf** [comment]
Размер desctop шрифта изменён на 250px и mobile = 150px согласовано с Эльдаром

**Comment by SergeyPilipenko** [comment]
2.3.63-beta проверено в даталайне
