### ISSUE TITLE
[Uni Blocks] Мобильный блок ErrorBlock

### ISSUE THREAD

**Issue by SergeyPilipenko** [redneckz/wildless-cms-uni-blocks#1645]
Необходимо реализовать мобильный блок ErrorBlockкак на Скрине ниже.

Настройки блока аналогичны десктопному.

Десктоп
![image](https://user-images.githubusercontent.com/22083206/230799198-458672d5-485f-4121-8806-f97f206c673f.png)

Мобильный [Макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17943-128062&t=i80RXuZHkSGLMbOO-4)
![image](https://user-images.githubusercontent.com/22083206/230799213-5a12ff25-8640-4cf2-8d9b-55801796110f.png)

**Comment by klapada** [comment]
Закрываю, т.к. уже заведена задача по реализации моб блока Ошибка - https://github.com/redneckz/wildless-cms-uni-blocks/issues/1643
