### ISSUE TITLE
e2e. Портал. Мобильный блок CarouselLinks. Количество ссылок в столбце

### ISSUE THREAD

**Issue by Guzlik123** [redneckz/wildless-cms-uni-blocks#1655]
2.3.62-beta

Задача: https://github.com/redneckz/wildless-cms-uni-blocks/issues/1437

В мобильном режиме в одном столбце должно быть не более трех ссылок, остальные должны переносится в следующие, сейчас вот так ( скрин ниже ) 

![image](https://user-images.githubusercontent.com/110792030/230922349-e23a18c2-bf39-42b3-879b-422a3aa001a4.png)

**Comment by SergeyPilipenko** [comment]
2.3.63-beta исправлено в даталайне
