### ISSUE TITLE
[Uni Blocks] Мобильный блока Подборщик ипотек (MortgageFiltration)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1662]
Необходимо реализовать мобильный блок MortgageFiltration как на _Скрине_ ниже.

Настройки блока аналогичны десктопному.

Названия полей как в десктопе.

Макет десктопного блока по [ссылке](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=20027-171007&t=pEDidBUoM41gZQZT-4).

![Image](https://user-images.githubusercontent.com/112703510/231147305-5231f6b5-857e-4412-a8c0-6b6837c968a4.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=17689-106786&t=RrVOicI1e0wc3lLs-4))_

**Comment by SergeyPilipenko** [comment]
2.3.63-beta проверено в даталайне
