### ISSUE TITLE
e2e. Пример основного сайта. Портал. Мобильный режим. Не работает переход по якорной ссылке таба Тарифы и Документы

### ISSUE THREAD

**Issue by Guzlik123** [redneckz/wildless-cms-uni-blocks#1694]
2.3.63-beta

При переходе через таб Тарифы и Документы происходит скролл по якорной ссылке  но после переключения в моб режим переход по табу Тарифы и Документы перестает работать

https://10.80.4.9/natural/creditcards/svoya#tariffs

**Comment by end0rfin** [comment]
Проверил указанный адрес.
Переход по "Тарифам и документам" осуществляется корректно.
На данный момент ошибка исправлена.

**Comment by SergeyPilipenko** [comment]
2.3.65-beta исправлено в даталайне
