### ISSUE TITLE
e2e. Мобильный блок ApplicationForm. Замечания. Поменять расположения полей в моб версии блока

### ISSUE THREAD

**Issue by Guzlik123** [redneckz/wildless-cms-uni-blocks#1699]
2.3.63-beta

1.  В моб версии блока Форма заявки "Кредит" поля настройки Данные организации должны идти в следующей последовательности : 
- Наименование организации
- Годовая выручка
- ИНН
- Контактное лицо
- Телефон
- Электронная почта

2.   В моб версии блока Форма заявки "Эквайринг" поменять местами поля настроек ИНН и Контактное лицо

**Comment by SergeyPilipenko** [comment]
2.3.65-beta исправлено в даталайне
