### ISSUE TITLE
[Uni Blocks] Новый блок с данными по депозитарию

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1732]
Необходимо реализовать новый блок для вывода информации по депозитарию как на _Скрине_ ниже, который состоит из:
- Списка документов:
  - выводимые данные в виде таблицы
    - "Дата" = дате загрузки документа на сайт
    - "Тема" = названию документа
  - сортировка списка по дате по убыванию
- Пагинации
  - логика работы аналогична как на странице Мвидео - https://www.mvideo.ru/televizory-i-cifrovoe-tv-1/televizory-65?from=under_search
  - кол-во документов на одной странице = 10

Фильтрация по документам и выбор кол-ва записей на странице будут реализованы в рамках отдельной задачи.

![Image](https://user-images.githubusercontent.com/112703510/234912836-62e1c638-0014-41d6-80ee-27329b3bdd77.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?type=design&node-id=23281-124831&t=xiAz1ovzdgLtsXdC-4))_

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
