### ISSUE TITLE
[Uni Blocks] Вывод сообщения об ошибке в ApplicationForm

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1737]
Необходимо в блоке ApplicationForm выводить сообщение об ошибке как на Скрине ниже, если с сервера пришел ответ не 200 ОК.

![Image](https://user-images.githubusercontent.com/112703510/234791944-2dc2e5f0-ac46-4795-96ee-441cff1eb419.png)
_Скрин. Сообщение об ошибке ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=19434-36465&t=StLyw67Q2kFoc0mD-4))_

**Comment by SergeyPilipenko** [comment]
2.3.79-beta проверено в даталайне
