### ISSUE TITLE
Новые требования к BaseTile

### ISSUE THREAD

**Issue by Longraf** [redneckz/wildless-cms-uni-blocks#1758]
Добавить настройку «Второстепенная картинка» (картинок в фоне больше нет)
В мобильной версии основная картинка не переносится и остаётся всегда справа (при наличии настройки "Изображение всегда справа"
В  основная картинка сжимается до 50% своей ширины далее переносится в область между контентом и кнопками
Второстепенные картинки при сжатии более 50% исчезают
Переход  с ПК версии на мобильную происходит при ширине 1024px 
Для мобильной версии отбивка серая исчезает
Если флаг "Изображение всегда справа" не выставлен , то работают общие правила сжатия и переноса картинки
При вкл настройке «Изображение всегда справа» картинка также сжимается до 50%, только после не перетекает вниз

**Comment by SergeyPilipenko** [comment]
2.3.66-beta проверено в даталайне
