### ISSUE TITLE
e2e. Мобильная версия портала. Бета. Мобильное меню

### ISSUE THREAD

**Issue by Guzlik123** [redneckz/wildless-cms-uni-blocks#1769]
Мобильное меню прижато к самому низу страницы на всех порталах
![image](https://user-images.githubusercontent.com/110792030/236213196-80076d9b-af2e-4947-8923-f56dfa950b07.png)

**Comment by SergeyPilipenko** [comment]
2.3.65-beta исправлено в даталайне
