### ISSUE TITLE
e2e. Кабинет редактора. Блок Подборщик вкладов. Замечания

### ISSUE THREAD

**Issue by Guzlik123** [redneckz/wildless-cms-uni-blocks#1770]
2.3.65-beta

1. В настройках вложенной продуктовой плитки поле "Адрес справочника" должно быть дропдаун, сейчас текстовое поле (скрин 1) 
2. В настройках вложенной продуктовой плитки убрать поля "Минимум" и "Максимум" для ввода диапазона срока
3. В настройках блока DepositFiltration в подразделе "Поле ввода срока" убрать поля "min" и "max"

![image](https://user-images.githubusercontent.com/110792030/236194105-c13cd05f-dc41-49c4-a1c8-bb5f6806c9e4.png)

**Comment by KolyaBlacK** [comment]
1 пункт пока нельзя выполнить
