### ISSUE TITLE
Фильтры в блоке депозитарий (Depository)

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#1782]
Необходимо реализовать фильтрацию для блока Depository как на _Скрине 1_ ниже.

1) По умолчанию в фильтре все поля пустые, поэтому в списке документов отображаются все записи
2) В календаре сделать аналогичную логику как в сбере - https://www.sberbank.ru/ru/person/investments/depository/cos?minDate=2023-04-07&maxDate=2023-05-11
Если в поле "от" выбирается дата, то в поле “до” в календаре нельзя выбрать дату меньше даты "от" или наоборот при выборе даты "до" в календаре "от" нельзя выбрать дату больше, чем выбрана в "до"
3) При клике на "Очистить фильтры" очищаются все поля: поисковая строка, "Период с" и "Период до"
4) Если при фильтрации нет ни одного подходящего варианта, то отображается сообщение как на _Скрине 2_ ниже.

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/4d9140b5-63f0-4c2c-acf5-0d6a09f43a80)
_Скрин 1. Фильтрация ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?type=design&node-id=24302-120859&t=vqFeGkBsCKBTgqz9-4))_

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/4ea13935-377e-4ed7-8b2f-68ec75f4e820)
_Скрин 2. Нет подходящих вариантов ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?type=design&node-id=24373-117564&t=vqFeGkBsCKBTgqz9-4))_

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
