### ISSUE TITLE
e2e. Кабинет редактора. Карточка рекомендаций. Лишняя настройка Выделить карточку

### ISSUE THREAD

**Issue by SergeyPilipenko** [redneckz/wildless-cms-uni-blocks#1796]
2.3.65-beta
https://10.80.4.9:81/#15162/content%2Fcreditcards%2Flgotnaya.page.json

В Карточке рекомендаций лишняя настройка Выделить карточку, данная настройка для карточки тарифной карусели

![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/22083206/692b512a-975a-4d6f-89f8-3f8728d230bc)

**Comment by Irinaristova** [comment]
Это общая настройка в карусели сделана для всех карточек, чтобы можно было любой карточке проставить эту опцию. Этот рефакторинг был согласован с Сашей.

**Comment by SergeyPilipenko** [comment]
оставляем настройку
