### ISSUE TITLE
[Uni Blocks] Мобильная блок OfficesAtmsMap

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1802]
Необходимо реализовать мобильный блок OfficesAtmsMap:
- вид для офисов как на _Скрине 1_ ниже
- вид для банкоматов как на _Скрине 2_.

Настройки блока аналогичны десктопному.

![Image](https://user-images.githubusercontent.com/112703510/237980948-01616def-3a29-4020-ae0a-1a557579d443.png)
_Скрин 1. Вид блока с офисами ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?type=design&node-id=21247-160630&t=d69JBXKRziaxQwGc-4))_

![Image](https://user-images.githubusercontent.com/112703510/237981117-1134b352-eb8a-4f9a-83bb-126dc4389701.png)
_Скрин 2. Вид блока с банкоматами ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?type=design&node-id=21247-161914&t=d69JBXKRziaxQwGc-4))_

**Comment by SergeyPilipenko** [comment]
2.3.85-beta проверено
