### ISSUE TITLE
e2e. Кабинет редактора. Блок Шаги. Выравнивание заголовка

### ISSUE THREAD

**Issue by Guzlik123** [redneckz/wildless-cms-uni-blocks#1807]
2.3.65-beta

Не работает выравнивание заголовка

![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/110792030/291db5b4-9ffa-4030-af5a-7dc40948e554)
![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/110792030/a3eb57e4-7350-48be-9a01-3fa3d5297b2f)

**Comment by SergeyPilipenko** [comment]
2.3.74-beta не актуально, избавились от настройки
