### ISSUE TITLE
[Bug] Ошибка в визуальном отображении названия блока внутри карусели на странице Контакты и реквизиты

### ISSUE THREAD

**Issue by Lickspitty** [redneckz/wildless-cms-uni-blocks#1839]
На странице Контакты и реквизиты (https://beta.rshb.ru/about/contacts#), Урегулирование задолженности не влезает в формат ячейки. Прошу сделать так, чтобы он влезал в формат.

Скрин и тест делал с десктопа.

Поправить надо до 26.05.23.

![Image](https://github.com/redneckz/temp_wcms/assets/117666273/cff0e2dd-a241-4ebb-b8c8-723d318440b8)

**Comment by Lickspitty** [comment]
@Guzlik123 @SergeyPilipenko посмотрите плиз, всё ли корректно заведено. Если что-то некорректно, прям тут пишите в комментариях

**Comment by andreySimonenko** [comment]
уменьшил шрифт у заголовка карточки
