### ISSUE TITLE
[Bug] Ошибка в отображении информации внутри блоков на странице "Раскрытие информации"

### ISSUE THREAD

**Issue by Lickspitty** [redneckz/wildless-cms-uni-blocks#1840]
На странице Раскрытие информации (https://beta.rshb.ru/about/reports-conclusion#) у половины блоков названия блоков и картинка не оцентрованы.

Прошу сделать так, чтобы они все были в едином формате.

Скрин и тест делал с десктопа.

Поправить надо до 26.05.23. Прошу отписаться по дате когда можно будет протестить.

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/117666273/05e270e4-17e3-42d0-993a-864ef0165073)

**Comment by Lickspitty** [comment]
@Guzlik123 @SergeyPilipenko посмотрите плиз, всё ли корректно заведено. Если что-то некорректно, прям тут пишите в комментариях

**Comment by andreySimonenko** [comment]
Поправили в рамках другой задачи

**Comment by Guzlik123** [comment]
2.3.73-beta

Исправлено
