### ISSUE TITLE
[Bug, e2e] Разъехались блоки рекомендаций на клауде на мобилке

### ISSUE THREAD

**Issue by Stanrshb** [redneckz/wildless-cms-uni-blocks#1843]
на примере https://beta.rshbcloud.ru/natural/debetcards/molodejnaya# 
Воспроизводить на мобилке

![Image](https://user-images.githubusercontent.com/132673589/239913135-49e27061-77c8-4340-8e18-bdd15eb4c1c4.png)

**Comment by Guzlik123** [comment]
2.3.73-beta

Исправлено
