### ISSUE TITLE
[Uni Blocks] Рефакторинг иконок

### ISSUE THREAD

**Issue by Longraf** [redneckz/wildless-cms-uni-blocks#1846]
Удалить неиспользуемые иконки. 
Убрать однотипные иконки
![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/32570545/2e775930-1c2c-4350-9905-86e030f99409)
![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/32570545/ba07568a-dbbd-43c2-87f1-555cc922beec)
![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/32570545/b224df52-2ac8-424a-9cf4-b6bc66668298)
Так же удалить все иконки которые на данный момент нигде не используются
Согласованно с Ксенией и Эльдаром

**Comment by Guzlik123** [comment]
2.3.75-beta

Проверено
