### ISSUE TITLE
[Bug] Ошибка в отображении информации внутри блоков на странице "Кредиты для ИП"

### ISSUE THREAD

**Issue by Lickspitty** [redneckz/wildless-cms-uni-blocks#1850]
На странице Кредиты для ИП (https://beta.rshb.ru/business/credits#), некорректно отображается инфа в блоках.

Как выглядит сейчас: 

![Image](https://github.com/redneckz/temp_wcms/assets/117666273/cc814d3f-9831-4c1b-bb19-0f523b22a5fa)

Как должно выглядеть:

![Image](https://github.com/redneckz/temp_wcms/assets/117666273/b1a0462d-c95b-419b-934f-a9d2deeb9784)

Скрин и тест делал с десктопа.

Поправить надо до 26.05.23. Прошу отписаться по дате когда можно будет протестить.

**Comment by Lickspitty** [comment]
@Guzlik123 @SergeyPilipenko посмотрите плиз, всё ли корректно заведено. Если что-то некорректно, прям тут пишите в комментариях

**Comment by end0rfin** [comment]
1. На панели  редактирования блока в "хлебных крошках" надо выбрать родительский компонент "Вертикальный компоновщик" (VerticalLayout). https://ibb.co/Z2VzBr0
2. В настройках необходимо снять галку "Отступы вложенных компонентов" - это уберёт внутренние отступы у вложенных компонентов. https://ibb.co/VmFnF92
3. Отступ внутри блока "Вертикальный компоновщик" (VerticalLayout) регулируется в выпадающем списке поля "Внутренний отступ". https://ibb.co/VmFnF92
4. Для добавления отступа между вложенным компонентами необходимо выбрать необходимое значение в выпадающем списке поля "Отступ между компонентами".  https://ibb.co/dty4YPr
5. Для позиционирования картинки над текстов внутри "Карточки продуктовой карусели" необходимо отметить пункт "Картинка сверху над текстом" (предварительно выбрав компонент "Карточка продуктовой карусели"). https://ibb.co/P5tdg0Y

**Comment by Guzlik123** [comment]
2.3.73-beta

Исправлено
