### ISSUE TITLE
[Bug] Ошибка в отображении информации внутри Депозитов

### ISSUE THREAD

**Issue by Lickspitty** [redneckz/wildless-cms-uni-blocks#1853]
На страницах Депозитов:
https://beta.rshb.ru/business/deposits#
https://beta.rshb.ru/business/deposits/stable
https://beta.rshb.ru/business/deposits/operative

1) Текст название депозита наезжает на картинку процента
2) В тексте Расчёт является предварительным. Актуальная процентная ставка доступна в ДБО "Свой Бизнес" (необходимо закрыть кавычки)\
3) баг с калькулятором депозитов - табы отображаются некорректно в среде Cloud. Отсутствует название таба. 

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/117666273/38e33461-3075-4e6c-87f5-12f41f6f565b)

Как должно быть:

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/117666273/a1a42981-4268-433e-af56-6fad77bc47c2)

Скрин и тест делал с десктопа.

Поправить надо сегодня. Прошу отписаться по дате когда можно будет протестить.

**Comment by Mikage777** [comment]
1. Исправлено

**Comment by Guzlik123** [comment]
2.3.73-beta

Исправлено
