### ISSUE TITLE
[Bug, e2e] На проме на beta.rshb.ru пропали картинки!!!

### ISSUE THREAD

**Issue by Stanrshb** [redneckz/wildless-cms-uni-blocks#1857]
![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/132673589/585259a4-025d-4492-96e1-6369bc1ea498)

**Comment by Mikage777** [comment]
Починили.

**Comment by Guzlik123** [comment]
2.3.73-beta

Исправлено
