### ISSUE TITLE
[Bug, e2e] Разъехалась структура в филиалах

### ISSUE THREAD

**Issue by Lickspitty** [redneckz/wildless-cms-uni-blocks#1864]
Ссылка: https://10.80.4.9/branches/tumen

Заголовки с иконками должны быть слева, основной текст справа, разделители пропали, у заголовков и текста разные стили текста. На скрине мобильная версия, только в ней без иконок еще.

Скрин ошибки:

![Image](https://github.com/redneckz/temp_wcms/assets/117666273/b5900ee7-adda-4f18-b4d8-e5bb9ff28b57)

Как должно быть:

![Image](https://github.com/redneckz/temp_wcms/assets/117666273/feb1df40-7650-4e40-82b5-002a9c53bcca)

**Comment by SergeyPilipenko** [comment]
2.3.74-beta исправлено в даталайне
