### ISSUE TITLE
[Bug] Дать клиенту возможность вернуться на прежнюю версию сайта

### ISSUE THREAD

**Issue by Stanrshb** [redneckz/wildless-cms-uni-blocks#1865]
надо добавить в футер  (в самый конец, после "Мобильное приложение" ссылку "Вернуться на прежнюю версию сайта". По клику - 
1) переход на [old.rshb.ru](http://old.rshb.ru/) и 
2)очистка кэша,

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/132673589/1b21cab9-23bf-4515-a3a8-b6e54efb8231)

**Comment by Guzlik123** [comment]
Проверено
