### ISSUE TITLE
[Uni Blocks] Доработка мобильного Footer (позиционирование элементов)

### ISSUE THREAD

**Issue by Longraf** [redneckz/wildless-cms-uni-blocks#1906]
В мобилке поменяны местами текст и картинки. Теперь однообразно с desctop версией
[Макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?type=design&node-id=17943-140688&t=6XOshvLLbYnrJb6R-4)
![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/32570545/176b4bda-73d5-4068-af82-5c9c62bd5e76)

**Comment by end0rfin** [comment]
Реализовано в данном пулреквесте
https://github.com/redneckz/wildless-cms-uni-blocks/pull/1912

**Comment by SergeyPilipenko** [comment]
2.3.73-beta проверено в даталайне
