### ISSUE TITLE
[Uni Blocks] Кастомный блок для вывода новостей по аналитике в виде карточек тарифной карусели

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1951]
1) Необходимо реализовать кастомный блок для новостей, в котором будут выводиться новости в виде карусели как на _Скрине 1_  или как на _Скрине 3_ ниже

2) Для отображения новости используется карточка тарифной карусели (CarouselTariffsCard)

3) Для новости подкатегории "Инвестиционные идеи" список лейблов под кнопкой фиксированный и у всех новостей данной подкатегории одинаковый (пп.3-4 на _Скрине 1_), а значения подтягиваются из справочника конкретной новости (соответствие полей справочника и куда в карточке необходимо подтянуть это значение показано на _Скринах 1-2_ ниже)

4) Для новости подкатегории "Завтрак с РСХБ-Инвестиции" список лейблов под кнопкой фиксированный и у всех новостей данной подкатегории одинаковый (п.3 на _Скрине 3_), а значения подтягиваются из справочника конкретной новости (соответствие полей справочника и куда в карточке необходимо подтянуть это значение показано на _Скринах 3-4_ ниже)

5) В настройках блока необходимы следующие поля:
    - **Новости**
      - вид компонента: селект
      - возможные значения (список папок из портала "Новости"):
        - analyse-idea
        - analyse-daily
      - значение по умолчанию: пусто
      - плейсхолдер: "Выберите папку"
      - в папке размещаются справочники новостей (1 справочник = 1 новость) и из справочников выбранной папки подтягиваются данные для каждой новости
    - **Количество показываемых новостей**
      - вид компонента: числовое поле
      - значение по умолчанию: пусто
      - при указании значения > 0 в списке отображается заданное кол-во карточек самых свежих новостей, данные для которых берутся из последних созданных справочников (при указании "0" в списке не отображается ни одна карточка, а если поле пустое, то выводятся все карточки, которые есть в папке)

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/57286f28-62e1-4292-b665-6f799ba4bb7a)
_Скрин 1. Вид карточки для новости "Инвестиционные идеи"_

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/918e4c1e-0c5f-47c0-ae3c-7888fbff9a8d)
_Скрин 2. Справочник новости "Инвестиционные идеи"_

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/9e3f1ed4-a7b2-49b3-a5d4-8d34efb0799d)
_Скрин 3. Вид карточки для новости "Завтрак с РСХБ-Инвестиции"_

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/7fc90a44-2cbe-438c-bebf-dd640217c51b)
_Скрин 4. Справочник новости "Завтрак с РСХБ-Инвестиции"_

**Comment by SergeyPilipenko** [comment]
2.3.90-beta проверено в даталайне
