### ISSUE TITLE
[Uni Blocks] Доработка формы заявки по эквайрингу (ApplicationForm)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1952]
Необходимо внести следующие изменения в блоке ApplicationForm для заявки "Эквайринг" в поле "Адрес":
- добавить возможность поиска по аналогии с полем "Филиал" в заявке "Бизнес-карта"
- переименовать поле с "Адрес" на "Филиал"
- переименовать плейсхолдер с "Выберите адрес" на "Выберите филиал"

**Comment by Guzlik123** [comment]
2.3.86-beta

Проверено
