### ISSUE TITLE
e2e. natural, портал. Проблема с блоком RollupItem.

### ISSUE THREAD

**Issue by lis42000** [redneckz/wildless-cms-uni-blocks#1962]
https://beta.rshbcloud.ru/natural/loans#

![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/52430705/f954730f-dd4e-4db6-892c-801e79aad0f3)
![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/52430705/3ddee25b-efa3-42c6-8e97-7dc32cedfe6d)

**Comment by SergeyPilipenko** [comment]
2.3.74-beta исправлено
