### ISSUE TITLE
Мобильная версия разводящей страницы

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1985]
Необходимо реализовать мобильную версию разводящей страницы как на _Скрине_ ниже ([макет](https://www.figma.com/file/EKNu51bGMsBpKA57JcltxH/%E2%AD%90%EF%B8%8F-RSHB---%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F?type=design&node-id=21582-163970&t=qvMaHpyE7xSrb8kV-4)).

![Image](https://user-images.githubusercontent.com/112703510/246861283-86f28b81-a539-454e-9e6f-6b2824bf124a.png)

**Comment by SergeyPilipenko** [comment]
2.3.85-beta проверено в даталайне
