### ISSUE TITLE
[Uni Blocks] Кастомный блок для вывода новостей по аналитике в виде списка новостей

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#1992]
1) Необходимо реализовать кастомный блок для новостей, в котором будут выводиться новости в виде списка как на _Скрине 1_  ниже.

2) Для отображения новости используется вид как на портале Новостей (/news), но еще с описанием новости (соответствие полей справочника и куда в карточку новости необходимо подтянуть это значение показано на _Скринах 1-2_ ниже)

3) В настройках блока необходимы следующие поля:
    - **Новости**
      - вид компонента: селект
      - возможные значения (список папок с портала "Новости"):
        - analyse-weekly
        - analyse-dmarket
        - analyse-imarket
      - значение по умолчанию: пусто
      - плейсхолдер: "Выберите папку"
      - в папке размещаются справочники новостей (1 справочник = 1 новость) и из справочников выбранной папки подтягиваются данные для каждой новости
    - **Количество показываемых новостей**
      - вид компонента: числовое поле
      - значение по умолчанию: пусто
      - при указании значения > 0 в списке отображается заданное кол-во карточек самых свежих новостей, данные для которых берутся из последних созданных справочников (при указании "0" в списке не отображается ни одна карточка, а если поле пустое, то выводятся все карточки, которые есть в папке)

![Image](https://user-images.githubusercontent.com/112703510/247096692-ac6f0374-153e-46c5-b065-ac0801109f17.png)
_Скрин 1. Вид списка новостей ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?type=design&node-id=25195-41233&t=gOjM4OY1dHXxkNYj-4))_

![Image](https://user-images.githubusercontent.com/112703510/247096877-8cbe4eac-7120-4819-96d4-73d29cfafe1a.png)
_Скрин 2. Справочник новости_

**Comment by SergeyPilipenko** [comment]
2.3.90-beta проверено в даталайне
