### ISSUE TITLE
[UniBlocks] В подборщике вкладов в фильтрах можно выбрать только одну валюту (DepositFiltration)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#2031]
В блоке DepositFiltration для категории фильтров "Валюта":
- изменить мультивыбор на одиночный выбор
- при включении 2го варианта, 1й выключается
- в настройках плитки должна остаться возможность добавления нескольких валют

![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/0710d9c5-bf26-41e9-bcf7-60182ae3685e)

**Comment by Guzlik123** [comment]
2.3.76-beta

Исправлено
