### ISSUE TITLE
Создать новые цветовые палитры для Премиум и Ультра

### ISSUE THREAD

**Issue by Stanrshb** [redneckz/wildless-cms-uni-blocks#2041]
Добавить 2 новые цветовые палитры в настройки страницы в поле "Цветовая палитра":
- Премиум
- Ультра
<img width="453" alt="Screenshot 2023-07-06 at 11 57 58" src="https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/28ce5949-8b2c-45fd-9e4d-bb9516157e7e">

![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/c6157c0d-2c1e-408e-a20b-2f5fc1f37411)
_Скрин. Цветовые палитры ([макет](https://www.figma.com/file/s9DhyzlOx3msQKHEL4svNL/%E2%AD%90%EF%B8%8F-RSHB---%D0%9F%D1%80%D0%B5%D0%BC%D0%B8%D1%83%D0%BC?type=design&node-id=25939-126094&mode=design&t=e7j0NBCSdGhnQu13-4))_

**Comment by SergeyPilipenko** [comment]
2.3.76-beta проверено в даталайне
