### ISSUE TITLE
[Новости] Новое направление новостей "Премиум/Ультра"

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#2120]
1) Необходимо в настройках новостей на портале Новости добавить новое направление - "Премиум/Ультра" (_Скрин 1_)
2) Реализовать страницу как на _Скрине 2_ для вывода новостей и акций
3) На странице на вкладке "Акции" выводятся те новости, у которых в настройках в КР активирован чекбокс "Акция". Все остальные новости отображаются на вкладке "Новости"

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/2456f149-42ab-4f43-8ad2-77f8a85f8cb9)
_Скрин 1. Настройки нового направления_

![Image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/112703510/40ea54bd-88d6-4b3e-a27c-f56bb87efb29)
_Скрин 2. Вид страницы с новостями ([макет](https://www.figma.com/file/s9DhyzlOx3msQKHEL4svNL/%E2%AD%90%EF%B8%8F-RSHB---%D0%9F%D1%80%D0%B5%D0%BC%D0%B8%D1%83%D0%BC?type=design&node-id=26850-8563&mode=design&t=VQ1oobgo9LoiyZso-4))_

**Comment by SergeyPilipenko** [comment]
2.3.90-beta проверено
