### ISSUE TITLE
[Uni Blocks] Доработка блока Калькулятор в части градиента у ставки (Calculator)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#2124]
В блоке Calculator для всех видов калькулятора реализовать следующую логику градиента для отображения ставки:
- сверху - переменная основного цвета выбранной на странице цветовой палитры
- снизу - зашитый в коде цвет, одинаковый для всех (hex F6DB7D)

![Image](https://user-images.githubusercontent.com/112703510/257558288-8a67cbc6-2bcb-4e81-af83-16b347ade300.png)
_Скрин 1. Вид ставки для Частных клиентов ([макет](https://www.figma.com/file/s9DhyzlOx3msQKHEL4svNL/%E2%AD%90%EF%B8%8F-RSHB---%D0%9F%D1%80%D0%B5%D0%BC%D0%B8%D1%83%D0%BC?type=design&node-id=26924-18011&mode=design&t=pK86vwvokUHDl2ky-4))_

![Image](https://user-images.githubusercontent.com/112703510/257558372-6fcc5661-e052-4ec2-b1f1-629f744e7195.png)
_Скрин 2. Вид ставки для Ультра ([макет](https://www.figma.com/file/s9DhyzlOx3msQKHEL4svNL/%E2%AD%90%EF%B8%8F-RSHB---%D0%9F%D1%80%D0%B5%D0%BC%D0%B8%D1%83%D0%BC?type=design&node-id=26924-17590&mode=design&t=pK86vwvokUHDl2ky-4))_

**Comment by SergeyPilipenko** [comment]
2.3.89-beta проверено в даталайне
