### ISSUE TITLE
[Uni Blocks] Добавление юаней в блок курсов обмена валют (ExchangeRateTile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#2165]
1) Необходимо добавить вывод еще одного курса обмена валют - юани (_Скрин_ ниже)
2) Также добавить в полях "Хочу продать" и "Получу":
    - в селекте новое значение "CNY"
    - возможность рассчитывать юани по отношению к другим валютам и наоборот (по аналогии с долларом или евро)
3) Если для выбранного филиала отсутствует информация по курсу юаня, то не отображается:
    - курс валют по юаням
    - значение "CNY" в селекте в полях "Хочу продать" и "Получу"

![Image](https://user-images.githubusercontent.com/112703510/261997962-667f2ac4-1186-4ab5-927d-cd4c11376cf7.png)
_Скрин. Вид блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?type=design&node-id=7991-158693&mode=design&t=QPFSr0CTtmQrkrpb-4))_

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
