### ISSUE TITLE
[UniBlocks] Блок с табами

### ISSUE THREAD

**Issue by dimanoid-master** [redneckz/wildless-cms-uni-blocks#248]
Согласован дизайн нового блока, содержащего табы. Пример отображения:
![Image](https://user-images.githubusercontent.com/111270951/185904060-a29690c1-7540-450d-b011-79e940cccd50.png)

Блок будет присутствовать на каждой странице продуктов Банка.

По умолчанию блок должен содержать 3 вкладки. Ширина вкладок одинаковая, вместе они будут занимать всю ширину страницы. Возможно добавление вкладок (**уточнить максимально возможное их количество**), в этом случае ширина каждой должна пропорционально уменьшиться. Каждая вкладка содержит следующие поля:

- Название (поле ввода текстовой информации)
- Якорь (поле ввода текстовой информации)

Якорь должен соответствовать блоку, с которым связана вкладка.

При добавлении блока с табами необходимо добавить минимум 3 блока, имеющих заполненные поля для якорных ссылок и соответствующих вкладкам блока с табами.

Логика поведения: при открытии страницы продукта банка блок с табами должен располагаться под блоком зеленого цвета (с названием, описанием и преимуществом продукта):
![Image](https://user-images.githubusercontent.com/111270951/185945352-ed022a2b-dcee-406a-841e-dd2183d63f43.png)
Первая вкладка блока табов должна быть выделена зеленым цветом, ей должен соответствовать первый блок, идущий на странице после блока с табами (в примере на скрине выше - это Калькулятор).
По клику лкм на названии другой вкладки должен произойти скролл страницы к началу блока, соответствующего этой вкладке (по якорной ссылке). Название выбранной вкладки должно окраситься в зеленый цвет (зеленым цветом выделяется только активная вкладка)
Сам блок с табами должен также сместиться и отобразиться над блоком, к которому был выполнен скролл.
Если пользователь самостоятельно скроллит страницу БЕЗ клика на название вкладки - вышеописанные действия с блоком табов должны также производиться, т.е. при достижении следующего блока страницы блок с табами отображается над этим блоком, соответствующая вкладка блока табов меняет цвет на зеленый.

**Comment by Mikage777** [comment]
Из обсуждения логики поведения компонента 29.08.2022 было решено

1. табы прибить к потолку в момент сролла при достижении позиции этих табов вместо того, чтобы прикреплять их к отдельным блокам в момент скроллинга, дабы избежать "дергания" контента (из-за того что эти табы будут "врезаться" между компонентами при прокрутке)
2. Чтобы избежать излишней валидации при вставке блока табов в кабинете редактора, и удовлетворить требованию задачи по "блок с табами должен располагаться под блоком зеленого цвета" решено считать табы частью продуктового блока, который в зависимости от настроек, будет включаться/выключаться

**Comment by lis42000** [comment]
В данный момент для поддержки якоря для всех компонентов, во все компоненты вручную на верхний уровень было добавлено поле id. Автоматизировать данный процесс не удалось так как при добавлении обёртки над компонентами, которые рендерятся через декоратор, начинаются проблемы со стилями из-за появления лишней прослойки. 
Данную проблему нужно будет решить в рамках рефакторинга.

**Comment by dimanoid-master** [comment]
**!!!Уточнение по состоянию на 31.08.2022!!!**

Актуальный на данный момент дизайн доступен по ссылке:
https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_Основной_сайт-(Частным-клиентам)?node-id=8037%3A316982

Не во всех вкладках блока табов может быть указана якорная ссылка на блок текущей страницы. В примере ниже
![Image](https://user-images.githubusercontent.com/111270951/187706807-2ca1e625-9f81-4f03-9b7b-ff941f42e5f9.png)
вкладки "Урожай" и "Тарифы" должны содержать ссылки на другие страницы.

Необходима доработка полей для редактирования вкладок блока табов. Каждая вкладка содержит следующие поля:
- Заголовок: текстовое поле, обязательное
- URL (href): текстовое поле, обязательное (может быть указана ссылка на другую страницу или якорь блока текущей страницы)
- Таргет (target) (стандартный селектор с вариантами открытия ссылки, необязательный)

Вкладки блока, в которых указана ссылка на другую страницу, не смогут становиться активными на этой странице, т.к. они не будут участвовать в скролле.

Поведение вкладок блока, в которых указан якорь блока текущей страницы, остается без изменений.
