### ISSUE TITLE
[Uni Blocks] Калькулятор

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#331]
### Блок калькулятора.

В новом дизайне имеются три вида калькулятора:

1. Кредитный калькулятор

![Image](https://user-images.githubusercontent.com/5903264/188450629-92fdf3aa-8da5-453b-ada9-b6d3a80f7cce.png)

2. Калькулятор для вклада
С возможностью выбора валюты, так и без

![Image](https://user-images.githubusercontent.com/5903264/188450958-8308d940-493b-4746-815b-cc9b9f9b8363.png)

![Image](https://user-images.githubusercontent.com/5903264/188451246-6c22c9bc-9821-4239-8605-21f6a20ed581.png)

3. Ипотечный калькулятор

![Image](https://user-images.githubusercontent.com/5903264/188451642-70907595-2109-40b4-ba88-bc41ab476b54.png)

**Из того что известно:** 

У каждой вкладке помимо указания справочника, также указывается один из этих трех типов калькулятора. Вкладок может быть много, так много, что они могут не помещаться в ширину компонента. Поэтому нужен скролл по типу галереи. По нажатию на кнопку вправо будет прокручиваться только вкладки. После прокрутки появится кнопка "влево".
Если вкладка одна, то ее отображать не нужно.

**Comment by Longraf** [comment]
Ещё есть бонусы 
![image](https://user-images.githubusercontent.com/32570545/188454129-2075cee4-5c10-48b6-a5b5-3f51bc08bfc9.png)

**Comment by dimanoid-master** [comment]
**Уточнения после обсуждения**

Калькуляторы могут быть для расчета параметров:
- Кредитов
- Вкладов
- Ипотеки
- Бонусов

Все вышеперечисленные виды калькуляторов **могут опционально содержать вкладки**, кроме калькулятора Бонусов (он всегда без вкладок).

На Главной странице (Частным лицам) блок "Калькулятор" **всегда должен содержать вкладки**, которых будет ровно три: Кредит, Вклад и Ипотека:
![Image](https://user-images.githubusercontent.com/111270951/188471307-4aef2df2-7376-4899-8dce-d61b6778df1a.png)
В каждую из этих вкладок будет добавляться "главный" продукт соответствующей группы продуктов, некий "флагманский продукт", т.е. какой-то определенный Кредит, Вклад и Ипотека.
Стрелок для скролла вкладок здесь не будет, т.к. число вкладок фиксированное.

На разводящей странице группы продуктов (Кредитов, Вкладов и Ипотек) блок "Калькулятор" **всегда должен содержать вкладки**:
Кредиты
![Image](https://user-images.githubusercontent.com/111270951/188471750-f5a1f75a-5ab5-437b-86b1-bef83a1baff0.png)
Вклады
![Image](https://user-images.githubusercontent.com/111270951/188471905-7b0cc463-c17e-4220-8b2c-aead945990f4.png)
Ипотека
![Image](https://user-images.githubusercontent.com/111270951/188472145-e7377c2b-b2f1-48f1-b42b-47ad2065cc69.png)
**Число этих вкладок должно быть равно количеству продуктов данной продуктовой группы**.
Внутри каждой вкладки будет добавляться конкретный продукт из данной категории, соответствующий заголовку вкладки.
Должны присутствовать кнопки-"стрелки" для скролла вкладок, как описано в самой задаче.

На страницах конкретных банковских продуктов (определенного Кредита, Вклада и Ипотеки) блок "Калькулятор" **никогда не будет иметь вкладок** (подразумевается калькулятор для продукта, который в данный момент просматривает пользователь).
Калькулятор Бонусов также не будет иметь вкладок.

Градиентные шрифты в текущей реализации считать картинками.

Для кредитного калькулятора **игнорировать кнопки "+" и "-"**, присутствующие в макетах (это предварительный вариант, от которого с большой вероятностью откажутся).

**Comment by klapada** [comment]
Небольшие изменения в части калькуляторов:
1) Кнопки "Подробные условия" пока не будет
2) Обновленный макет калькулятора для кредитов (добавлены 3 чекбокса) ([Ссылка на макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=10894%3A108726))
<img width="808" alt="Screenshot 2022-09-06 at 15 06 56" src="https://user-images.githubusercontent.com/112703510/188631247-c8aceeaa-cec7-432a-aa89-657fbbe79364.png">
3) Поле "Ежемесячный платеж" без кнопок "+" и "-" ([Ссылка на макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7906%3A222227)) 
<img width="177" alt="Screenshot 2022-09-06 at 15 16 20" src="https://user-images.githubusercontent.com/112703510/188632837-04ed123e-1643-438c-acb3-4ab489a58889.png">

**Comment by klapada** [comment]
Логика работы калькулятора кредитов:

строки_таблицы //массив, содержащий строки таблицы (каждый элемент массива - отдельный объект со своими полями) - у каждого продукта свой массив

//Переменные, которые пользователь вводит самостоятельно:
bool зарплатник
bool бюджетник
bool страховка
int сумма
int срок //в месяцах
тип_платежа (аннуитетный/диффиренцированный)

//Переменные, которые нужно расчитать:
float ставка
int платеж //ежемесячный

//При изменении любого значения пользовательских переменных:

//1. Расчет процентной ставки:

`счетчик (а = 0, а < длина (строки_таблицы), а++)
{
	если строки_таблицы[а].зарплатник == зарплатник И 
	строки_таблицы[а].бюджетник == бюджетник
	{
		мин_сумма_калькулятора = строки_таблицы[а].мин_сумма_калькулятора
		макс_сумма_калькулятора = строки_таблицы[а].макс_сумма_калькулятора
		мин_срок_калькулятора = строки_таблицы[а].мин_срок_калькулятора
		макс_срок_калькулятора = строки_таблицы[а].макс_срок_калькулятора
		если строки_таблицы[а].мин_сумма >= сумма И
		строки_таблицы[а].макс_сумма <= сумма
		{
			если страховка
				ставка = строки_таблицы[а].ставка_со_страховкой
			иначе
				ставка = строки_таблицы[а].ставка_без_страховки
		}
}`

//2. Расчет ежемесячного платежа:

i = ставка/1200 (коэффициент для расчета аннуитетного платежа)

`если тип_платежа == аннуитетный
	платеж = сумма * (i + i/((1+i)^срок - 1) //аннуитетный платеж
иначе
	платеж = сумма/срок + сумма*ставка/12 //дифф. платеж (за первый месяц)`

**Comment by klapada** [comment]
В калькуляторе по ипотеке всего используется 4 чекбокса, но их отображение зависит от конкретной программы. Ниже представлены текущие названия программ и список тех чекбоксов, которые по ней должны отображаться:
1)	Ипотечные каникулы для А101
 
<img width="356" alt="Screenshot 2022-09-07 at 14 37 25" src="https://user-images.githubusercontent.com/112703510/188872817-54271788-6d0f-4e71-a24e-fa390789cbd2.png">

2)	Ипотека без первоначального взноса (как в п.1)
3)	Сельская ипотека
 
<img width="213" alt="Screenshot 2022-09-07 at 14 39 09" src="https://user-images.githubusercontent.com/112703510/188872875-515c0fd9-cc70-4c75-9d23-57c55a61ad6b.png">

4)	Ипотечное жилищное кредитование (как в п.1)
5)	Специальные ставки на объекты ГК ПИК (как в п.1)
6)	Ипотека по 2 документам (как в п.1)
7)	Молодая семья и материнский капитал (как в п.1)
8)	Рефинансирование ипотеки для граждан РФ, имеющих детей 
<img width="527" alt="Screenshot 2022-09-07 at 14 42 14" src="https://user-images.githubusercontent.com/112703510/188872925-0a00055d-e084-4e1c-9555-eaac81af306b.png">

9)	Рефинансирование ипотеки (как в п.1)
10)	Дальневосточная ипотека (как в п.3)
11)	Специальное предложение А101 (как в п.3)
12)	Ипотека с господдержкой для семей с детьми (как в п.8)
13)	Ипотека с господдержкой (как в п.8)
14)	Ипотека на покупку нежилой недвижимости (как в п.1)

**Comment by Longraf** [comment]
Шаблон страницы калькуляторов сделан на основе "Кредитного калькулятора" т.к. сейчас маеты разных калькуляторов отличаются, по отступам, выравниваниям и ширинам блоков

**Comment by klapada** [comment]
1) По калькулятору для вклада
Имеет формы для пользователя:
- сумма вклада
- срок вклада

Вывод калькулятора:
- процентная ставка
- доход (сумарный за весь срок)
- сумма в конце срока


Логика работы: 

Процентная ставка зависит от показателей которые изменяет пользователь (сумма вклада, срок вклада) - и берется из справочника

Расчет такой:
доход = сумма вклада * процентная ставка * срок вклада / 1200
сумма в конце срока = сумма вклада + доход

2) По ипотечному калькулятору
[Ипотечный_калькулятор_v28_20220907_140635.pdf](https://github.com/redneckz/wildless-cms-uni-blocks/files/9573440/_._v28_20220907_140635.pdf)

**Comment by klapada** [comment]
1. Пример справочника для калькулятора по кредитам
[Пример таблицы ставок.xlsx](https://github.com/redneckz/wildless-cms-uni-blocks/files/9575044/default.xlsx)

2. Пример справочника для калькулятора вкладов
[Пример справочника для калькулятора вклада.xlsx](https://github.com/redneckz/wildless-cms-uni-blocks/files/9575050/default.xlsx)

**Comment by klapada** [comment]
Обновленный макет по калькулятору кредитов (добавлен выбор типа платежа) (ссылка на [макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=12298%3A137249))
<img width="770" alt="Screenshot 2022-09-16 at 10 10 16" src="https://user-images.githubusercontent.com/112703510/190579586-c132bfe0-354d-4966-b011-6d2157228d70.png">

Обновленный макет по калькулятору вкладов (добавлен выбор выплаты процентов) (ссылка на [макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=12298%3A138798))
<img width="770" alt="Screenshot 2022-09-16 at 10 10 47" src="https://user-images.githubusercontent.com/112703510/190579820-e6699869-3179-4999-bb1f-3f96ad5d93bf.png">

**Comment by klapada** [comment]
Изменен дизайн калькулятора вкладов ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=13420%3A166551)): 
- добавлен радиобаттон для выбора способа оформления вклада - в офисе/дистанционно
- перенесен радиобаттон по выплате процентов
<img width="687" alt="Screenshot 2022-09-26 at 17 53 28" src="https://user-images.githubusercontent.com/112703510/192310296-a445fd81-e8f8-4f19-bd14-20e6c3945080.png">
