### ISSUE TITLE
[Uni Blocks] Блок бонусов

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#333]
**Блок бонусов**

![Image](https://user-images.githubusercontent.com/5903264/188468538-361be0c9-c6e8-4b76-9b93-71c09b6c6fd9.png)

https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=2168%3A109216

**Comment by end0rfin** [comment]
Ссылка на сам блок.
https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=9990%3A172691

**Comment by klapada** [comment]
1) Необходимо добавить новый блок Бонусы, у которого есть следующие настройки (Скрин ниже):
- Заголовок
  - тип: текстовое поле
  - значение по умолчанию: "Начисление баллов"
- Описание
  - тип: текстовое поле
  - значение по умолчанию: "Описание"
- Список плиток
  - Плитка 1
    - Заголовок
      - тип: текстовое поле
      - значение по умолчанию: "Плитка 1"
    - Описание
      - тип: текстовое поле
      - значение по умолчанию: "Описание плитки 1"
    - Количество баллов
      - тип: числовое поле
      - значение по умолчанию: 1
    - Наименование
      - тип: текстовое поле
      - значение по умолчанию: "балл"
- Добавить плитку
  - тип: кнопка
  - при клике добавляется еще один подраздел "Плитка N" с аналогичными полями, как у Плитки 1
2) Логика добавления плиток:
- Одна плитка в блоке занимает всю строку, т.е. 12 колонок
- Если добавляется 2я плитка, то каждая из 2х плиток занимает по 1/2 ширины строки, т.е. по 6 колонок
- При удалении одной из 2х плиток оставшаяся плитка опять занимает 12 колонок
- При добавлении 3й плитки она встает под 2мя плитками и занимает всю ширину строки, т.е. 12 колонок
- Если добавить 4ю плитку, то результат аналогичный, как при добавлении 2й плитки
- Ограничений по кол-ву добавляемых плиток нет
- Удалить единственную плитку нельзя
<img width="317" alt="Screenshot 2022-09-06 at 17 59 23" src="https://user-images.githubusercontent.com/112703510/188668787-2938164a-af27-4244-b860-322c5e0ad73e.png">

**Comment by Longraf** [comment]
У компонента бонус был уникальный шрифт (слово "баллов") 44px согласовал с Эльдаром изменение шрифта на 40px
