### ISSUE TITLE
[Uni Blocks] Доработка компонента Плитка (Tile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#344]
Необходимо для компонента Tile добавить новую настройку для возможности изменения размера шрифта:
- название поля: "Тип заголовка"
- тип поля: дропдаун
- возможные варианты: "h2" (=32px) и "h3" (=28px)
- по умолчанию: "h3"

![Image](https://user-images.githubusercontent.com/112703510/188652291-0c721929-926d-4a69-abb8-e403967666bd.png)

**Comment by Irinaristova** [comment]
уже реализован функционал

**Comment by klapada** [comment]
Договорились, что в поле "Тип заголовка":
- возможные варианты: h1/h2/h3/h4/h5
