### ISSUE TITLE
[Uni Blocks] Добавление кнопки "Скрыть" в блок Таблица тарифов (TariffsTable)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#352]
Необходимо в блоке Таблица тарифов (TariffsTable) в настройках добавить новое поле для возможности скрытия/разворачивания строк с описанием по тарифу (по аналогии, как у блока Сравнительная таблица (ComparisonTable)):
- название поля: "Отображать заданное количество строк"
- тип: числовое поле
- значение по умолчанию: null
- при вводе значения > 0 в блоке отображается кнопка "Скрыть" согласно Скрину 1 ниже
  - при клике на "Скрыть":
    - нижние строки скрываются и отображается столько первых строк, сколько задано в поле "Отображать заданное количество строк"
    - кнопка "Скрыть" меняется на "Развернуть" согласно Скрину 2 ниже

Скрин 1. Кнопка "Скрыть" ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=11165%3A158735))

![Image](https://user-images.githubusercontent.com/112703510/189072656-86930799-4cee-40a8-a074-d7b409dad460.png)

Скрин 2. Кнопка "Развернуть" ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=9990%3A142899))

![Image](https://user-images.githubusercontent.com/112703510/189073040-58577a24-990b-4988-b7e4-f78af6a08757.png)

**Comment by SergeyPilipenko** [comment]
2.3.16-beta проверено
