### ISSUE TITLE
[Uni Blocks] Доработка блока Курсы валют (ExchangeRateTile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#356]
Необходимо доработать блок Курсы валют (ExchangeRateTile) согласно обновленному дизайну ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=8481%3A150327))

Описание полей и логика работы блока:
- Поле "У меня есть":
  - тип: числовое поле
  - мин. значение: 0
  - ввести можно только целое число
  - по умолчанию:
    - выбрана валюта = Рубль RUB
    - сумма = 1000
  - под полем выводится: "1 RUB = {сумма в долларах за 1 руб по текущему курсу, округленная до десятитысячных} USD"  (например "1 RUB = 0,0149 USD")
- По полю "Хочу приобрести":
  - тип: числовое поле
  - мин. значение: 0
  - ввести можно только целое число
  - по умолчанию:
    - выбрана валюта = Доллар США USD
    - сумма = 1000 / {курс доллара}
      - значение суммы округляется до сотых
  - под полем выводится: "1 USD = {сумма в рублях за 1 долл по текущему курсу, округленная до сотых} RUB"  (например "1 USD = 67,23 RUB")
- При клике в поле, если там отображается сумма в долях, происходит округление этой суммы до целого значения по правилам округления
- При изменении суммы в одном поле происходит моментальный перерасчет суммы в другом
- Если изменяется выбранная валюта, то под полем также происходит перерасчет значения за 1 у.е.
- В дропдауне для выбора валюты есть следующие значения:
  - Рубль RUB
  - Доллар США USD
  - Евро EUR

**Пока вопрос открытый по тому, откуда брать значения по актуальному курсу валют.**

![Image](https://user-images.githubusercontent.com/112703510/189089168-a499fce7-b93d-401c-be95-347e02f7339e.png)

**Comment by Mikage777** [comment]
Уточнить у @klapada актуальность этой задачи.

**Comment by klapada** [comment]
Задача больше не актуальна
