### ISSUE TITLE
[Uni Blocks] Новый блок Каталог

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#373]
Необходимо реализовать новый блок "Каталог" для возможности добавления галереи товаров.
В панели настроек нового блока должны быть доступны следующие поля:
- Заголовок
  - тип: текстовое поле
  - значение по умолчанию: "Каталог"
- Описание
  - тип: текстовое поле
  - значение по умолчанию: "Описание"
- Отображать элементы в моб. версии
  - тип: дропдаун
  - возможные значения: "Вертикально"/"Горизонтально"
  - значение по умолчанию: "Горизонтально"
- Список карточек
  - Карточка
    - Заголовок
      - тип: текстовое поле
      - значение по умолчанию: "Заголовок карточки"
    - Описание
      - тип: текстовое поле
      - значение по умолчанию: "Описание карточки"
    - Доступные цвета
      - тип: дропдаун
      - возможные значения: "Белый"/"Черный"
      - значение по умолчанию: null
      - плейсхолдер: "Выберите цвет"
      - можно удалить/переместить, если кол-во полей > 1
    - Добавить цвет
      - тип: кнопка
      - при клике добавляется еще одно поле для выбора доступного цвета
    - Цена в рублях
      - тип: числовое поле
      - значение по умолчанию: null
    - Кнопка
      - Текст
        - тип: текстовое поле
        - значение по умолчанию: "Подробнее"
      - URL
        - тип: текстовое поле
        - значение по умолчанию: null
      - Переход по ссылке
        - тип: дропдаун
        - возможные значения: "В текущей вкладке"/"В новой вкладке"
        - значение по умолчанию: "В текущей вкладке"
      - Цвет кнопки
        - тип: дропдаун
        - возможные значения: "Основной"/"Второстепенный"/"Link"
        - значение по умолчанию: "Основной"
      - Закругленные углы
        - тип: чекбокс
        - значение по умолчанию: false
    - Изображение
      - Выбор файла для загрузки
        - тип: кнопка
        - при клике открывается проводник для выбора файла
      - Альтернативное описание
        - тип: текстовое поле
        - значение по умолчанию: null
        - плейсхолдер: "Альтернативное текстовое описание изображения"
      - Текст подсказки
        - тип: текстовое поле
        - значение по умолчанию: null
        - плейсхолдер: "Текст подсказки"
      - Основной формат
        - Формат
          - тип: дропдаун
          - возможные варианты: jpeg/jpg/png/gif/webp/heif/avif
          - значение по умолчанию: webp
        - Ширина
          - тип: числовое поле
          - значение по умолчанию: 230
        - Высота
          - тип: числовое поле
          - значение по умолчанию: 230
        - Дополнительные форматы
          - Добавить формат
            - тип: кнопка
            - при клике добавляются поля Формат, Ширина и Высота
            - дополнительный формат можно удалить
  - Добавить карточку
    - Тип: кнопка
    - при клике добавляется еще один подраздел Карточка с полями описанными выше (новая карточка с полями появляется в начале списка, т.е. сдвигает вниз уже созданные карточки)
  - карточку можно удалить/переместить, если кол-во карточек > 1

Скрин 1. Вид нового блока
![Image](https://user-images.githubusercontent.com/112703510/189301062-e8d32997-4cda-48cd-a6f8-0469b24576d9.png)

Скрин 2. Настройки блока
![Image](https://user-images.githubusercontent.com/112703510/189358649-86415030-52d7-4137-9779-6a42e24a393d.png)

**Comment by Longraf** [comment]
В макете нет описания. Согласовал с Эльдаром такое поведение (оно уже используется в проекте)
Заголовок 32/40
Отступ 12
Описания 18/24
