### ISSUE TITLE
[Портал] Добавить анимацию на разводящую страницу

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#382]
По ховеру на одну из колонок, должна происходить анимация "раскрытия" колонки. Также потребуется дополнить интерфейс (и схему) для того чтобы принимать ссылки для кнопок.

![Image](https://user-images.githubusercontent.com/5903264/189649140-673fa43c-f993-404d-9073-96f4a5aebe3a.png)

https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7847%3A158184

**Comment by Grimitsu** [comment]
Добавлена анимация по текущему дизайну в фигме под 1920х1080.
Жду отмашки от Эльдара, когда будет утверждённый дизайн под другие брейкоинты

**Comment by SergeyPilipenko** [comment]
2.3.16-beta проверено
