### ISSUE TITLE
[Uni Blocks] Блок "BonusBenefitsBlock"

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#383]
Блок похож на BenefitsBlock, за малым исключением. Разницу можно увидеть на скрине, думаю в описании не нуждается особо.

![Image](https://user-images.githubusercontent.com/5903264/189657753-2a1eb647-6fab-4a72-9eb1-044efe754370.png)

https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7930%3A154104

**Comment by Mikage777** [comment]
в заивисимости от ширины блока (col-span-*) менять максимальное количество преимуществ в строке. Например:

col-span-12 - 4 в строке
col-span-8 - 3 в строке
col-span-4 и менее - 2 в строке

**Comment by SergeyPilipenko** [comment]
проверено

**Comment by Longraf** [comment]
Согласовал с Эльдаром изменения отступа с 34px до `32px` между описанием и преимуществами

**Comment by Longraf** [comment]
Согласовал с Эльдаром изменения отступа с 34px до 32px между описанием и преимуществами
