### ISSUE TITLE
[Uni Blocks] Новый блок Аренда сейфовых ячеек

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#384]
Необходимо реализовать новый блок Аренда сейфовых ячеек с использованием справочника ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=9187%3A2027773)).
Логика работы полей следующая:
- Город
  - тип: дропдаун
  - возможные значения: {список значений из справочника}
  - значение по умолчанию: {город в зависимости от локации пользователя}
- Отделение
  - тип: дропдаун
  - возможные значения: {список значений из справочника}
  - значение по умолчанию: null
  - плейсхолдер: "Выберите отделение"
- Срок аренды
  - тип: слайдер
  - мин. значение: 1
  - макс. значение: 365
  - единица измерения: день
  - значение по умолчанию: 26
  - в поле можно ввести число вручную
- Размер ячейки
  - тип: дропдаун
  - возможные значения: {список значений из справочника}
  - значение по умолчанию: {любое значение из справочника}
- Параметры ячейки, мм (ВхШхД)
  - тип: дропдаун
  - возможные значения: {список значений из справочника}
  - значение по умолчанию: {любое значение из справочника, соответствующее выбранному значению в поле Размер ячейки}
- Тип договора
  - тип: радио
  - возможные значения: "Простое хранение"/"Сделка с недвижимостью"
  - значение по умолчанию: "Сделка с недвижимостью"
- Аренда за
  - тип: строка
  - значение: равно выбранному кол-ву дней в поле "Срок аренды"
- Цена
  - тип: строка
  - значение: расчет значения по формуле = {TariffValue} * {кол-во выбранных дней аренды в поле "Срок аренды"}, где TariffValue - это список из 4х коэффициентов, полученный от ЦФТ, выбор которого зависит от кол-ва дней аренды, а именно:
    - если в поле "Срок аренды" выбрано <= 30 дней, то берется TariffValue, соответствующий TariffType = 1
    - если в поле "Срок аренды" выбрано  > 30, но <=90 дней, то берется TariffValue, соответствующий TariffType = 2
    - если в поле "Срок аренды" выбрано  > 90, но <=180 дней, то берется TariffValue, соответствующий TariffType = 3
    - если в поле "Срок аренды" выбрано  > 180, но <=365 дней, то берется TariffValue, соответствующий TariffType = 4
  - значение изменяется каждый раз при изменении параметров, влияющих на ее расчет
- Офисы на карте
  - тип: кнопка
  - при клике под блоком отображается карта с офисами как на Скрине 2.

Скрин 1. Блок Аренда сейфовых ячеек
![Image](https://user-images.githubusercontent.com/112703510/189360600-99755088-bf23-4f5d-ac1b-33370c1dc21e.png)

Скрин 2. Офисы на карте
![Image](https://user-images.githubusercontent.com/112703510/189591085-aa5c5636-c84f-41ff-95c4-58de1ec7393a.png)

**Comment by klapada** [comment]
Уточнение: в поле **Параметры ячейки, мм (ВхШхД)** в дропдауне выводить только те значения, которые соответствуют выбранному значению в поле **Размер ячейки**

**Comment by Guzlik123** [comment]
2.3.26-beta
Проверено

**Comment by klapada** [comment]
Дополнение к логике работы поля **Офисы на карте** в блоке:
  - при клике:
    - если поле **Отделение** пустое, то под блоком отображается карта со всеми точками офисов выбранного города, у которых safeBoxCases не null
    - если в поле **Отделение** выбрано конкретное значение, то на карте отображается точка с выбранным офисом
