### ISSUE TITLE
[Uni Blocks] Доработка блока Продуктовая плитка (ProductTile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#385]
Необходимо в настройках блока Продуктовая плитка добавить новое поле согласно описанию и Скринам 1-2 ниже:
- название поля: "Дополнительное описание"
- тип: текстовое поле
- значение по умолчанию: null

Скрин 1. Отображение текста в блоке ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=8615%3A14021972))
![Image](https://user-images.githubusercontent.com/112703510/189674174-d5b78ee5-3142-499e-9f4e-ce27a6328dee.png)

Скрин 2. Новое поле в настройках блока
![Image](https://user-images.githubusercontent.com/112703510/189673638-73d9221d-6102-4f71-89ac-1627e1c96e29.png)

**Comment by SergeyPilipenko** [comment]
2.3.16-beta проверено
