### ISSUE TITLE
[Uni Blocks] Доработка блока Аккордеон (Accordion)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#386]
Необходимо в блоке Аккордеон добавить новое поле согласно описанию ниже для возможности выравнивания заголовка всего блока:
- название поля: "Выравнивание заголовка"
- тип: дропдаун
- возможные значения: "по левому краю"/"по центру"/"по правому краю"
- значение по умолчанию: "по центру"

![Image](https://user-images.githubusercontent.com/112703510/189676030-9798c761-c9a9-4dce-b007-ee5664541b76.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
