### ISSUE TITLE
[Uni Blocks] Доработка кнопок

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#387]
В кнопках теперь есть возможность отображать иконку справа 

![Image](https://user-images.githubusercontent.com/5903264/189678584-9668683e-98ba-4b4c-8a3a-d0079f2a9cbb.png)

https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=8227%3A163237

**Comment by SergeyPilipenko** [comment]
проверено 2.3.21-beta
