### ISSUE TITLE
[Uni Blocks] Блок выбора страховой суммы (InsuranceAmountBlock)

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#388]
Реализовать блок выбора страховой суммы.
Механика скролла как в галерее. По щелчку на элемент ставится галочка в его верхнем правом углу, обводка становится зеленой. С других элементов обводка и галочка снимаются. Ссылка на кнопке меняется на ту, что была "привязана" к этому элементу. Минимум 2 элемента, первый по-умолчанию "выбран"

![Image](https://user-images.githubusercontent.com/5903264/189679524-643d735c-6269-429b-b8eb-f418dce969bd.png)

https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7907%3A173361

**Comment by klapada** [comment]
В этом блоке еще должна быть возможность добавления табов под заголовком (вид настроек показан на Скрине 2 п.2):
- можно добавить любое кол-во вкладок
- можно удалять вкладки
- названия вкладок можно менять местами, если их кол-во > 1

У каждой плитки, помимо полей для ввода текста, суммы и выбора картинки (пп.3-5 на Скрине 2), есть еще следующие поля:
- URL
  - тип: текстовое поле
  - значение по умолчанию: null
  - значение поля используется в момент клика на кнопку в блоке для перехода на нужную страницу (зависит от выбранной плитки в момент клика)
- Вкладка
  - тип: дропдаун
  - возможные значения: {список названий всех добавленных вкладок}
  - значение по умолчанию: {любое значение из списка названий вкладок}
  - если нет ни одной добавленной вкладки, то поле пустое и неактивно

Скрин 1. Вид блока
<img width="618" alt="Screenshot 2022-09-13 at 09 05 57" src="https://user-images.githubusercontent.com/112703510/189855504-336daa40-400c-4907-85b2-7c1aa39d4462.png">

Скрин 2. Настройки блока
<img width="111" alt="Screenshot 2022-09-13 at 11 36 14" src="https://user-images.githubusercontent.com/112703510/189855550-fca21c03-2d87-4c09-a82c-95606fd7a102.png">

**Comment by SergeyPilipenko** [comment]
проверено
