### ISSUE TITLE
[Uni Blocks] Доработка блока Мобильное приложение (MobileAppTile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#401]
Необходимо доработать блок MobileAppTile и в его настройках реализовать следующее:
1) Возможность добавления описания в виде списка
  - до подраздела Кнопки изменить порядок полей, а также добавить новые поля согласно Скрину 2 ниже
    - Пункт 1 списка
      - тип: текстовое поле
      - значение по умолчанию: "Пункт 1"
    - Пункт 2 списка
      - тип: текстовое поле
      - значение по умолчанию: "Пункт 2"
    - Пункт 3 списка
      - тип: текстовое поле
      - значение по умолчанию: "Пункт 3"
    - Пункт 4 списка
      - тип: текстовое поле
      - значение по умолчанию: "Пункт 4"
    - Добавить пункт
      - тип: кнопка
      - при клике добавляется пустое поле еще одного пункта списка
  - если заполнено хотя бы одно поле с пунктом списка, то отображать пункты списка и скрывать текст "Наведите камеру телефона на QR-код и скачайте приложение"
        - в противном случае отображать текст "Наведите камеру телефона на QR-код и скачайте приложение"
  - Переименовать поле "Описание" в "Описание (моб.)"
2) Возможность добавления изображения
![Image](https://user-images.githubusercontent.com/112703510/189924018-86c977b3-1ee3-493b-8c87-b62753dbb884.png)

3) Возможность изменения цвета блока
  - название поля: "Цвет блока"
  - тип: дропдаун
  - возможные значения: "Основной"/"Второстепенный"
  - значение по умолчанию: "Основной"

Скрин 1. Вид блока
![Image](https://user-images.githubusercontent.com/112703510/189874608-58b5db8f-6527-4834-9be4-f1af9156ee8e.png)

Скрин 2. Настройки блока
<img width="156" alt="Screenshot 2022-09-13 at 17 32 34" src="https://user-images.githubusercontent.com/112703510/189929608-f9182cd8-9cc0-4fa7-a879-e6d142dddd79.png">

**Comment by klapada** [comment]
Ссылка на [макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7930%3A154104)

**Comment by SergeyPilipenko** [comment]
ппроверено
