### ISSUE TITLE
[Uni Blocks] Новый блок по Страхованию

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#407]
Необходимо реализовать новый блок по страховым рискам и продуктам со следующими настройками (Скрин 4):
- Заголовок
  - тип: текстовое поле
  - значение по умолчанию: "Страховые риски и продукты"
- Описание
  - тип: текстовое поле
  - значение по умолчанию: "Описание"
- Список
  - Пункт списка
    - тип: текстовое поле
    - значение по умолчанию: "Пункт 1"
  - Выбрать иконку из списка
    - тип: кнопка
    - при клике открывается модальное окно для выбора иконки из списка
  - Добавить пункт
    - тип: кнопка
    - при клике добавляются поля для еще одного пункта списка (текст + иконка)
- Страховая сумма
  - тип: числовое поле
  - значение по умолчанию: 500000
  - если поле пустое, то в блоке не отображается
- Ежемесячный лимит
  - тип: числовое поле
  - значение по умолчанию: null
  - если поле пустое, то в блоке не отображается
- Изображение
  - Выбор файла для загрузки
    - тип: кнопка
    - при клике открывается проводник для выбора файла
  - Альтернативное описание
    - тип: текстовое поле
    - значение по умолчанию: null
    - плейсхолдер: "Альтернативное текстовое описание изображения"
  - Текст подсказки
    - тип: текстовое поле
    - значение по умолчанию: null
    - плейсхолдер: "Текст подсказки"
  - Основной формат
    - Формат
      - тип: дропдаун
      - возможные варианты: jpeg/jpg/png/gif/webp/heif/avif
      - значение по умолчанию: null
    - Ширина
      - тип: числовое поле
      - значение по умолчанию: null
    - Высота
      - тип: числовое поле
      - значение по умолчанию: null
    - Дополнительные форматы
      - Добавить формат
        - тип: кнопка
        - при клике добавляются поля Формат, Ширина и Высота
        - дополнительный формат можно удалить

Скрин 1. Несколько пунктов списка и одно поле
![Image](https://user-images.githubusercontent.com/112703510/189947895-b7309f53-a30a-49a4-a524-c1ae2c0c3f1b.png)

Скрин 2. Один пункт списка и одно поле
![Image](https://user-images.githubusercontent.com/112703510/189948009-4e9f86d0-d67a-4b4d-845e-ce442eb6363b.png)

Скрин 3. Несколько пунктов списка и 2 поля
![Image](https://user-images.githubusercontent.com/112703510/189948091-4abfd758-6888-4331-ae6e-9d38b19e0c66.png)

Скрин 4. Настройки блока
![Image](https://user-images.githubusercontent.com/112703510/189952469-ee1a6454-1da5-4edb-8c03-9fd20bd23a3f.png)

**Comment by Longraf** [comment]
[Макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7907%3A172866)

**Comment by SergeyPilipenko** [comment]
2.3.16-beta проверено
