### ISSUE TITLE
[Uni Blocks] Добавить логику подсчета в блок курсов валют

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#409]

**Comment by klapada** [comment]
- Если хочу продать в RUB и купить USD/EUR, то значение в поле "Получу" = {значение из поля “Хочу продать”} / {курс EUR/USD, выбранной в поле “Получу”, значение которого берется из поля "Продать"}
  - например: хочу продать 1000 руб и получить Евро (курс беру из скрина ниже), то в поле "Получу" будет значение = 1000 / 92,80
- Если хочу продать в EUR/USD и получить RUB, то значение в поле "Получу" = {значение из поля “Хочу продать”} * {курс EUR/USD, выбранный в поле “Хочу продать”, значение которого берется из поля "Купить"}
  - например: хочу продать 100 USD и получить RUB (курс беру из скрина ниже), то в поле "Получу" будет значение = 100 * 73,75
- Если меняю значение в поле "Получу", у которого выбрана валюта EUR/USD, то значение в поле "Хочу продать" = {значение из поля "Получу"} * {курс EUR/USD, выбранный в поле "Получу", значение которого берется из поля "Продать"}
  - например: в поле "Получу" меняю значение с 10 EUR на 12 EUR, то в поле "Хочу продать" в RUB будет значение = 12 * 92,80
- Если меняю значение в поле "Получить", у которого выбрана валюта RUB, то значение в поле "Хочу продать" = {значение из поля "Получу"} / {курс EUR/USD, выбранный в поле "Хочу продать", значение которого берется из поля "Купить"}
  - например: в поле "Получу" меняю значение c 1000 RUB на 2000 RUB, то в поле "Хочу продать" в USD будет значение = 2000 / 73,75

![2022-09-14 12 02 06](https://user-images.githubusercontent.com/112703510/190111007-62a55f74-214c-4d4a-bf4c-51f429a192e8.jpg)

**Comment by klapada** [comment]
- если в файле курс валюты в “Купить” пришел пустой или = 0 (если значение 0.0001, то округляем до 0), то в поле “Хочу продать” в дропдауне выбора валюты эту валюту скрываем
- если в файле курс валюты в “Продать” пустой или = 0, то в поле “Получу” в дропдауне выбора валюты эту валюту скрываем
- при изменении в поле "Хочу продать" с RUB на USD или EUR, в поле "Получу" выбранная валюта меняется на RUB (т.е. при продаже евро или долларов можно узнать только, сколько ты получишь в рублях)
- если в поле "Получу" значение меняется с RUB на USD или EUR, то в поле “Хочу продать” меняется на RUB (т.е. при покупке евро или долларов можно узнать только, сколько нужно рублей для покупки)

Т.е. посмотреть евро относительно дол и наоборот не даем

**Comment by klapada** [comment]
1. Логика определения ближайшего офиса

   Необходимо получить у пользователя разрешение на получение его местоположения:
     - если пользователь дал разрешение, то получить координаты с помощью https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation
        - далее определить более точное положение пользователя, отправив координаты в сервис dadata.ru
        - на основании полученных данных определить:
          - адрес ближайшего офиса Банка (вывести в блоке)
          - расстояние в км до ближайшего офиса (вывести в блоке)
     - если разрешение получено не было, то в блоке под курсами валют ничего не выводить

2. Добавить в настройках блока новое текстовое поле для ввода URL для кнопки "Купить валюту"

**Comment by SergeyPilipenko** [comment]
2.3.17-beta проверено
