### ISSUE TITLE
[Uni Blocks] Ипотечный калькулятор

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#424]
Необходимо добавить логику для подсчета в ипотечном калькуляторе

Связанная задача, в которой можно найти описанную логику по ипотечному калькутяору: https://github.com/redneckz/wildless-cms-uni-blocks/issues/331

**Comment by klapada** [comment]
Ипотечный калькулятор пока на паузе, т.к. есть открытые вопросы как по дизайну, так и по логике работы, а также по организационной части (возможно его не нужно будет делать)

**Comment by klapada** [comment]
От ипотечного калькулятора решили отказаться, чтобы не дублировать функционал уже имеющегося калькулятора на сайте "Свое жилье", поэтому его нужно удалить
