### ISSUE TITLE
[Uni Blocks] Доработка блока Преимущества (BenefitsBlock)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#432]
Необходимо в блоке BenefitsBlock реализовать следующее:
- добавить возможность выбора у преимущества выводить описание в виде просто текста или списка без/с буллитами
  - Вид контента
    - тип: дропдаун
    - возможные значения: "Описание"/"Список"
    - значение по умолчанию: "Описание"
- Если в поле "Вид контента" выбрано значение "Описание", то доступно пустое текстовое поле "Описание" (Скрин 2), при этом картинка позиционируется как на Скрине 1 (центрируется по тексту)
- Если в поле "Вид контента" выбрано значение "Список", то появляются поля для добавления пунктов списка (Скрин 4), при этом картинка позиционируется как на Скрине 3 (отображается рядом с заголовком и началом списка)
  - Буллиты
    - тип: чекбокс
    - возможные значения: true (пункты списка отображаются с маркером)/ false (пункты списка без маркера)
    - значение по умолчанию: true
  - Пункт списка 1
    - тип: текстовое поле
    - значение по умолчанию: "Пункт 1"
  - Пункт списка 2
    - тип: текстовое поле
    - значение по умолчанию: "Пункт 2"
  - Добавить пункт
    - тип: кнопка
    - при клике добавляется пустое поле для пункта списка

Скрин 1. Выбрано описание ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=8009%3A288746))
![Image](https://user-images.githubusercontent.com/112703510/190630624-e09ba0ee-a848-4f5d-8d6a-001a2e076bcc.png)

Скрин 2. Панель настроек блока, если выбрано описание
![Image](https://user-images.githubusercontent.com/112703510/190652355-4859e927-b455-4cff-9261-e10edd37a7b1.png)

Скрин 3. Выбран список ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7906%3A221696))
![Image](https://user-images.githubusercontent.com/112703510/190630728-f8d37623-6b5f-4e1a-bc8d-9a4bd5a8c5bd.png)

Скрин 4. Панель настроек блока, если выбран список
![Image](https://user-images.githubusercontent.com/112703510/190652389-3ee7eec2-d68d-48ff-864f-111ae7352246.png)

**Comment by end0rfin** [comment]
Реализовал все пункты задачи

**Comment by end0rfin** [comment]
Реализовал всё необходимое
