### ISSUE TITLE
[Uni Blocks] Возможность изменения ширины у вложенных блоков в Аккордеоне (Accordion)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#443]
Необходимо в блоке Accordion реализовать возможность изменения ширины у вложенного блока, для этого:
- В настройках Аккордеона в разделе "Блоки" у каждого добавляемого блока в конце добавить 2 новых поля (Скрин ниже)
  - Ширина (колонок)
    - значение по умолчанию: 12
  - Class name
    - значение по умолчанию: "col-span-12"

Скрин. Поля для изменения ширины и стилей у вложенного блока
![Image](https://user-images.githubusercontent.com/112703510/191007519-0c1de62c-9327-4015-8dad-2a763189ddea.png)

**Comment by SergeyPilipenko** [comment]
2.3.21-beta првоерено
