### ISSUE TITLE
[Uni Blocks] Возможность изменения ширины у вложенных блоков в Других продуктах (OtherProducts)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#444]
Необходимо в блоке OtherProducts реализовать возможность изменения ширины у каждого вложенного блока, для этого в настройках Других продуктов:
- в разделе "Блоки" у каждого добавляемого блока в конце добавить 2 новых поля (Скрин ниже)
  - Ширина (колонок)
    - значение по умолчанию: 12
  - Class name
    - значение по умолчанию: "col-span-12"
- удалить поле "Количество колонок"

Скрин. Поля для изменения ширины и стилей у вложенного блока
![Image](https://user-images.githubusercontent.com/112703510/191008152-fa30af05-2e12-4203-b300-ae64a961ad18.png)

**Comment by SergeyPilipenko** [comment]
2.3.21-beta проверено
