### ISSUE TITLE
[Кабинет редактора] Добавить фильтр для добавляемых блоков

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#449]
Добавить поле поиска в модальном окне выбора блоков, по которому будет произведено фильтрация отображаемых для выбора блоков. Фильтр будет работать по названию блока и по его типу.

Пример: при вводе ProductBlock или Продуктовый блок в любом регистре, будет отображен соответствующий блок/блоки

**Comment by SergeyPilipenko** [comment]
2.3.16-beta проверено
