### ISSUE TITLE
[Uni Blocks] Доработка блока по Страхованию (Insurance)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#458]
Необходимо в блоке Insurance добавить возможность в пункте списка добавлять описание, поэтому нужно внести изменения в подразделе Список согласно Скрину 2 ниже
Описание полей:
- Список
  - Пункт
    - Заголовок
      - тип: текстовое поле
      - значение по умолчанию: "Заголовок 1"
    - Описание
      - тип: текстовое поле
      - значение по умолчанию: "Описание 1"
    - Выбрать иконку из списка (без изменений)
    - Добавить пункт
      - тип: кнопка
      - при клике добавляется обновленный список пустых полей для нового пункта (Заголовок/Описание/Выбор иконки из списка)

Скрин 1. Вид блока, если пункты списка с описанием ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7906%3A195726))
![Image](https://user-images.githubusercontent.com/112703510/191231033-c0826cc1-a797-4383-82fa-6ee0a7a81e1d.png)

Скрин 2. Обновленный подраздел Список в настройках блока
![Image](https://user-images.githubusercontent.com/112703510/191232274-cfa6ff03-faa7-44ea-b285-8838d502410f.png)

**Comment by SergeyPilipenko** [comment]
проверено
