### ISSUE TITLE
[Uni Blocks] Доработка блока Начисление баллов (Bonus)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#476]
Необходимо в блоке Bonus добавить возможность загрузки картинки и/или добавления кнопки.
В настройках необходимо добавить следующие поля (вид настроек по умолчанию показан на Скрине 2):
- Вид контента
  - тип: дропдаун
  - возможные значения:
    - Изображение
    - Баллы
  - значение по умолчанию: null
  - плейсхолдер: "Выберите значение"
  - если выбрано значение "Изображение", то отображаются поля для загрузки своей картинки или выбор иконки из списка
    - список полей указан на Скрине 4
    - все поля по умолчанию пустые
  - если выбрано значение "Баллы", то отображаются поля "Количество баллов" и "Наименование" как показано на Скрине 5
- Добавить кнопку
  - тип: кнопка
  - при клике добавляются поля по настройке кнопки (как показано на Скрине 3)
    - Текст
      - тип: текстовое поле
      - значение по умолчанию: "Кнопка"
    - URL
    - Переход по ссылке
      - тип: дропдаун
      - значение по умолчанию: "В текущей вкладке"
    - Цвет кнопки
      - тип: дропдаун
      - значение по умолчанию: "Второстепенный"
    - Закругленные углы
      - тип: чекбокс
      - значение по умолчанию: false
  - добавить можно только одну кнопку

Логика отображения контента в блоке:
- позиционирование изображения/иконки отличается от вывода кол-ва баллов и располагается под описанием плитки как показано на Скрине 1

Скрин 1. Вид блока с изображением и кнопкой
![Image](https://user-images.githubusercontent.com/112703510/191519928-3b5c409c-74fe-426e-ab1f-bf0aadd1eea2.png)

Скрин 2. Новые поля в настройках
<img width="187" alt="Screenshot 2022-09-22 at 13 50 33" src="https://user-images.githubusercontent.com/112703510/191730277-15887b6f-b59f-4adf-92e8-1e075a8863e6.png">

Скрин 3. Вид настроек при добавлении кнопки
<img width="178" alt="Screenshot 2022-09-22 at 14 06 41" src="https://user-images.githubusercontent.com/112703510/191731149-0fcf3d3c-49dd-4bb1-b07d-fe8beb2a4655.png">

Скрин 4. Вид настроек, если выбрано значение "Изображение"
<img width="162" alt="Screenshot 2022-09-22 at 13 52 20" src="https://user-images.githubusercontent.com/112703510/191730496-3d761c49-6cc5-4426-94e2-296c30642256.png">

Скрин 5. Вид настроек, если выбрано значение "Баллы" 
<img width="162" alt="Screenshot 2022-09-22 at 13 55 37" src="https://user-images.githubusercontent.com/112703510/191730594-3f87af15-7369-4b4c-8b5e-1ca035edb40f.png">

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0

**Comment by SergeyPilipenko** [comment]
Макет: https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=8325%3A157477&t=sAv5zzFqZtBIqO3t-4
