### ISSUE TITLE
[Uni Blocks] Изменение шрифта/отступов в блоке Продуктовая плитка согласно макету (ProductTile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#486]
Необходимо внести изменения в блок ProductTile в части шрифта и отступов согласно [макету](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7854%3A125648).

Скрин. Обновленный блок
![Image](https://user-images.githubusercontent.com/112703510/191980255-4739f2ee-8a26-4826-bc3b-dc4579f46afd.png)

**Comment by SergeyPilipenko** [comment]
проверено
