### ISSUE TITLE
Рефактор шрифтов в проекте

### ISSUE THREAD

**Issue by Longraf** [redneckz/wildless-cms-uni-blocks#502]
Внедрить шрифты из дизайна в проект.
Отрефакторить компоненты по всему проекту с проверкой что ничего не "поломалось"
Комментарий дизайнера про шрифты из UI-KIT _"В будующем возможно только создание дополнительных стилей, но думаю этих должно хватить под все нужды"_

![image](https://user-images.githubusercontent.com/32570545/192535779-fce2255b-3546-4669-95f8-0f9c79328d05.png)

**Comment by klapada** [comment]
Размер шрифта 26px после обсуждения с дизайнером был изменен на 24px.
Список актуальных значений размеров шрифтов есть [тут](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=13004%3A142970).
