### ISSUE TITLE
[Дизайн-ревью] Общие замечания. Все страницы кроме разводящей

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#537]
- Отступ от хэдера до контента: 40px. [https://disk.yandex.ru/i/-O6aLA7Cy1MR5w](https://disk.yandex.ru/i/-O6aLA7Cy1MR5w)
- Цвет фона всех страниц: EBEDF0. [https://disk.yandex.ru/i/I7-SouXH0qzgIQ](https://disk.yandex.ru/i/I7-SouXH0qzgIQ)

**Comment by SergeyPilipenko** [comment]
2.3.28-beta исправлено
