### ISSUE TITLE
[Дизайн-ревью] Общие замечания. Все иконки на разводящих и продуктовых страницах

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#539]
- Иконки искажаются. Толщина линий разная. [https://disk.yandex.ru/i/CI1sZaIrhMY1Eg](https://disk.yandex.ru/i/CI1sZaIrhMY1Eg)
- На зеленом фоне - должны быть белые иконки.  [https://disk.yandex.ru/i/CI1sZaIrhMY1Eg](https://disk.yandex.ru/i/CI1sZaIrhMY1Eg) (связано с https://github.com/redneckz/temp_wcms/issues/427)

**Comment by SergeyPilipenko** [comment]
2.3.29-beta исправлено
