### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку Шапка (Header)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#540]
- Спустить пункты меню 2 уровня вниз, чтобы они были по центру. Отступ от линии до меню 2 уровня 24px. От меню 2 уровня до границы хэдера 28px. [https://disk.yandex.ru/i/rYFh8SJhFwRfqQ](https://disk.yandex.ru/i/rYFh8SJhFwRfqQ)
- Добавить зеленую линию. У страницы на которой находимся. [https://disk.yandex.ru/i/QkrrPShkMizaqg](https://disk.yandex.ru/i/QkrrPShkMizaqg)
- Добавить иконкам поиска и с точками ховеры. Перекраска в зеленый цвет. [https://disk.yandex.ru/i/Aiq6PwYNk3TKIQ](https://disk.yandex.ru/i/Aiq6PwYNk3TKIQ)
- Немного сместить иконку с точками чтобы она была по центру. [https://disk.yandex.ru/i/JQ-aIqP1Bx8MtQ](https://disk.yandex.ru/i/JQ-aIqP1Bx8MtQ)
- Цвет фона иконки с точками: EBEDF0. [https://disk.yandex.ru/i/JQ-aIqP1Bx8MtQ](https://disk.yandex.ru/i/JQ-aIqP1Bx8MtQ)
- Убрать у иконок при ховере всплывающие подсказки с названием иконки. [https://disk.yandex.ru/i/Paub_nsIh5qx7Q](https://disk.yandex.ru/i/Paub_nsIh5qx7Q)

**Comment by SergeyPilipenko** [comment]
2.3.25-beta
https://10.80.4.9/natural

1. От меню 2 уровня до границы хэдера 28px, сейчас 12+20

**Comment by SergeyPilipenko** [comment]
2.3.31-beta исправлено
