### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку Подвал (Footer)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#541]
- Изменить Line height всех шрифтов в соответсвии с ui kit. [https://disk.yandex.ru/d/eFhbv6vOpiGIHA](https://disk.yandex.ru/d/eFhbv6vOpiGIHA)
- Увеличить отступы между: Частным клиентам/Бизнес клиентам/Экосистема Свое/О банке [https://disk.yandex.ru/i/VKoTCJ7voRQfXw](https://disk.yandex.ru/i/VKoTCJ7voRQfXw)
- Добавить иконки моб. приложения. [https://disk.yandex.ru/d/FABYfae_ThqzfA](https://disk.yandex.ru/d/FABYfae_ThqzfA)
- При ховере кнопок с иконками моб. приложения и соцсетей должна исчезать обводка, остается только заливка. [https://disk.yandex.ru/i/itEwGkT34q2_3w](https://disk.yandex.ru/i/itEwGkT34q2_3w)
- Кнопка "Обратная связь" шрифт: L Font size: 16px, Line height: 24px, Font - weight: Regular. [https://disk.yandex.ru/i/vgYymz-Fb8stXw](https://disk.yandex.ru/i/vgYymz-Fb8stXw)
- Частным клиентам/Бизнес клиентам/Экосистема Свое/О банке: добавить ховеры. [https://disk.yandex.ru/i/PS15Qm5VFcSs9A](https://disk.yandex.ru/i/PS15Qm5VFcSs9A)
- Номера телефонов: добавить ховеры. [https://disk.yandex.ru/i/W3p9m_TLSiDl1Q](https://disk.yandex.ru/i/W3p9m_TLSiDl1Q)
- РСХБ Страхование и тд, Информация о процентных ставках по договорам банковского вклада с физическими лицами и тд. добавить кликабельность. [https://disk.yandex.ru/i/nga2SzSmfim0RQ](https://disk.yandex.ru/i/nga2SzSmfim0RQ)

Поиск в футере:

- Радиус скругления поля: 6px. [https://disk.yandex.ru/i/7Rnxp_Z_ejX8sQ](https://disk.yandex.ru/i/7Rnxp_Z_ejX8sQ)
- Шрифт текста "Поиск по сайту": L Font size: 16px, Line height: 24px, Font - weight: Regular. [https://disk.yandex.ru/i/4PwN_8XrsumfNw](https://disk.yandex.ru/i/4PwN_8XrsumfNw)

**Comment by SergeyPilipenko** [comment]
2.3.24-beta не выполнен
Увеличить отступы между: Частным клиентам/Бизнес клиентам/Экосистема Свое/О банке https://disk.yandex.ru/i/VKoTCJ7voRQfXw
