### ISSUE TITLE
[Дизайн-ревью] Главная разводящая. Шапка

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#544]
- Шрифты заменить на Light, как на главной частным клиентам, только белые [https://skr.sh/sG8oMzwqLi7](https://skr.sh/sG8oMzwqLi7)
- Иконки сделать белыми. [https://skr.sh/sG8oMzwqLi7](https://skr.sh/sG8oMzwqLi7)
- Убрать меню 2 уровня. [https://skr.sh/sG8aHJu7siQ](https://skr.sh/sG8aHJu7siQ)
- Сделать не активным таб "Частным клиентам". [https://disk.yandex.ru/i/GL_YFADxB_xM1A](https://disk.yandex.ru/i/GL_YFADxB_xM1A)
- Добавить ховеры: [https://www.figma.com/file/….](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=11637%3A187202)

Ссылка на [скрин](https://skr.sh/sG8Hyi1xUWq)

<img width="273" alt="Screenshot 2022-10-03 at 15 17 54" src="https://user-images.githubusercontent.com/112703510/193578168-a4134a7a-72bd-4c41-8229-d5e5e2abf60f.png">

**Comment by SergeyPilipenko** [comment]
2.3.28-beta исправлено
