### ISSUE TITLE
[Дизайн-ревью] Главная разводящая. Контент

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#545]
- Шрифт заголовка. Font size: 60px, Line height: 60px, Font - weight: Regular. [https://disk.yandex.ru/d/t3C4A_srKoN0BA](https://disk.yandex.ru/d/t3C4A_srKoN0BA)
- Шрифт текста. XL Font size: 18px, Line height: 24px, Font - weight: Light. [https://disk.yandex.ru/i/9kkhBgclHooTEA](https://disk.yandex.ru/i/9kkhBgclHooTEA)
- Шрифт кнопки: L Font size: 16px, Line height: 24px, Font - weight: Regular. [https://disk.yandex.ru/i/9Yn6zT4uESFjzA](https://disk.yandex.ru/i/9Yn6zT4uESFjzA)
- На 20px спустить вниз изображения и блок с контента при ховере [https://disk.yandex.ru/d/bpzGj_v1sMJCBg](https://disk.yandex.ru/d/bpzGj_v1sMJCBg)

![Image](https://user-images.githubusercontent.com/112703510/193578291-6faa0fc5-f4d0-4cfc-ac84-c55ec2ddc7fc.png)

**Comment by klapada** [comment]
Добавлены макеты разводящей страницы в Figma для разных разрешений для корректной работы страницы на разных экранах.

[Ссылка](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16860%3A181732)

**Comment by Irinaristova** [comment]
Исправлено в рамках другой задачи

**Comment by SergeyPilipenko** [comment]
2.3.65-beta исправлено в даталайне
