### ISSUE TITLE
[Дизайн-ревью] Главная разводящая. Подвал

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#546]
- Шрифт текста. S Font size: 14px, Line height: 20px, Font - weight: Light. [https://disk.yandex.ru/i/2gK7d3T8weKklA](https://disk.yandex.ru/i/2gK7d3T8weKklA)
- Добавить икнки соцсетей и ховеры. [https://skr.sh/sG8euJBwdBI](https://skr.sh/sG8euJBwdBI)

![Image](https://user-images.githubusercontent.com/112703510/193578753-8bdf2f89-8c18-47f9-9ffe-ace1f3556ce8.png)

**Comment by SergeyPilipenko** [comment]
2.3.28-beta шрифт ui-san-serif, должен быть ubuntu

**Comment by SergeyPilipenko** [comment]
Не исправлено в ип2.0


![Image](https://user-images.githubusercontent.com/22083206/203658007-e77de13c-2590-4d6c-86c9-66b87c63fab9.png)

**Comment by SergeyPilipenko** [comment]
исправлено в ип2.0
