### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку ProductGallery

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#548]
**1. Блок**
- Высота блока: 560px постоянная. [https://disk.yandex.ru/i/M4I_B8Ks1xZeDQ](https://disk.yandex.ru/i/M4I_B8Ks1xZeDQ)
- Отступы между карточками: 8px, от крав: 26 px. [https://disk.yandex.ru/i/qugXTBCYQ62m8A](https://disk.yandex.ru/i/qugXTBCYQ62m8A)
- Шрифт заголовка. H0 Font size: 56px, Line height: 56px, Font - weight: Regular. [https://disk.yandex.ru/i/0r7VX7OGaC5g7w](https://disk.yandex.ru/i/0r7VX7OGaC5g7w)
- Шрифт второстепенного текста. Font size: 26px, Line height: 36px, Font - weight: Light. [https://disk.yandex.ru/d/Vy88W61cmtXbuA](https://disk.yandex.ru/d/Vy88W61cmtXbuA)
- Отступ от заголовка до текста: 18px, от текста до кнопки: 36px. [https://disk.yandex.ru/d/mMGUw23hPT_5MA](https://disk.yandex.ru/d/mMGUw23hPT_5MA)

**2. Навигация в блоке**
- При наведении увеличивается одна карточка, при этом не должны приподниматься остальные. [https://disk.yandex.ru/i/7E75WXjkUnkS3A](https://disk.yandex.ru/i/7E75WXjkUnkS3A)
- Убрать мерцание карточки при переходе от маленькой к большой. Сделать более плавную анимацию.
    - Активная карточка. Заголовок: H6 Font size: 20px, Line height: 28px, Font - weight: Regular. [https://disk.yandex.ru/i/8fapcudTaT3uuQ](https://disk.yandex.ru/i/8fapcudTaT3uuQ) Второстепенный текст Font size: 17px, Line height: 20px, Font - weight: Light. [https://disk.yandex.ru/i/T_X9Z7qCDeM0hw](https://disk.yandex.ru/i/T_X9Z7qCDeM0hw) Отступ между текстом: 8px. Отступ сверху/снизу: 23px. Отступ слева/справа: 26px. [https://disk.yandex.ru/i/Ki5jDh6eRAd3kw](https://disk.yandex.ru/i/Ki5jDh6eRAd3kw)
- Не активные карточки. Заголовок: Font size: 16px, Line height: 24px, Font - weight: Regular. [https://disk.yandex.ru/i/8bajhw28YlEo1g](https://disk.yandex.ru/i/8bajhw28YlEo1g) Второстепенный текст Font size: 15px, Line height: 20px, Font - weight: Light. [https://disk.yandex.ru/d/fBxOLC2WigyjEA](https://disk.yandex.ru/d/fBxOLC2WigyjEA) Отступ между текстом: 4px. Отступ сверху/снизу: 22px. Отступ слева/справа: 23px. [https://disk.yandex.ru/i/VNzUxl9nxkQN1A](https://disk.yandex.ru/i/VNzUxl9nxkQN1A)

[Figma](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=12131%3A171338)

**3. Отступ снизу между блоком Продуктовая галерея и следующим блоком**
- Отступ от блока cлайдер до других плиток: 24px. [https://disk.yandex.ru/i/Y0RoQIEHv1hHvQ](https://disk.yandex.ru/i/Y0RoQIEHv1hHvQ)

**Comment by SergeyPilipenko** [comment]
https://10.80.4.9/natural
2.3.29-beta не исправлено:
1. У слайда в Описании font-weight=400, по макету 300
2. От кнопки до текста не 36px (кнопка не привязана к контенту)
3. Активная кнопка навигации: заголовок font-weight=500, по макету 400
4. Активная кнопка навигации: описание font-weight=400, по макету 300
5. Неактивная кнопка навигации: заголовок font-weight=500, по макету 400
6. Неактивная кнопка навигации: описание font-weight=400, по макету 300
7. Не совпадают отсупы в активной кнопке навигации: Отступ между текстом: 8px. Отступ сверху/снизу: 23px. Отступ слева/справа: 26px. https://disk.yandex.ru/i/Ki5jDh6eRAd3kw
8. Не совпадают отсупы в неактивной кнопке навигации: Отступ между текстом: 4px. Отступ сверху/снизу: 22px. Отступ слева/справа: 23px. https://disk.yandex.ru/i/VNzUxl9nxkQN1A

**Comment by Irinaristova** [comment]
по 8 пункту договорились с дизайнерами горизонтальные и вертикальные отступы - 24px

**Comment by Irinaristova** [comment]
По второму пукту договорились с дизайнерами оставить 32px, как есть сейчас

**Comment by Irinaristova** [comment]
Договорились сделать минимальную ширину неактивной кнопки 290px

**Comment by Irinaristova** [comment]
По 4 пункут договорились использовать шрифт 
<img width="369" alt="Снимок экрана 2022-11-08 в 12 43 10" src="https://user-images.githubusercontent.com/38761239/200530150-c28d0b95-3298-40a0-b819-fe9b4d9fa587.png">

**Comment by Irinaristova** [comment]
По пункту 1 договорились оставить как есть сейчас

**Comment by SergeyPilipenko** [comment]
Проверено в ип2.0, не исправлены:
 7. Не совпадают отсупы в активной кнопке навигации: Отступ между текстом: 8px. Отступ сверху/снизу: 23px. Отступ слева/справа: 26px. https://disk.yandex.ru/i/Ki5jDh6eRAd3kw
8. Не совпадают отсупы в неактивной кнопке навигации: Отступ между текстом: 4px. Отступ сверху/снизу: 22px. Отступ слева/справа: 23px. https://disk.yandex.ru/i/VNzUxl9nxkQN1A
9. 9. Не выполняется п3: Отступ снизу между блоком Продуктовая галерея и следующим блоком должен быть 24px. Сейчас 24+ширина сетки между блоками

**Comment by SergeyPilipenko** [comment]
Првоерено в ИП2.0, не испарвлены пункты в комментарии выше

**Comment by Irinaristova** [comment]
Пункт 8 - горизонтальные и вертикальные отступы 20px - ближайшее значение из конфига, отступ от заголовка до описания - 4px

**Comment by Irinaristova** [comment]
Кнопки слайдов смещены вправо - баг на данный момент не актуален

**Comment by Irinaristova** [comment]
Пункт 9 - Отступ снизу между блоком Продуктовая галерея и следующим блоком должен быть 24px. Сейчас 24+ширина сетки между блоками - решили не фиксить, тк этот отступ есть только в данном блоке (кастомный)

**Comment by SergeyPilipenko** [comment]
2.3.65-beta исправлено в даталайне
