### ISSUE TITLE
[Дизайн-ревью] Замечания по кнопкам

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#550]
**1. Белые кнопки главной и внутренних страниц**
- Шрифт. Font size: 16px, Line height: 24px, Font - weight: Regular. [https://disk.yandex.ru/i/YPodTKuHqeQIjQ](https://disk.yandex.ru/i/YPodTKuHqeQIjQ)
 - Эффект при наведении, такой же как у зеленых кнопок: [Ссылка на Figma](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=11713%3A155577). [Ссылка на скрин](https://skr.sh/sG8JVtI8DcL)
- Текст по центру кнопки [https://disk.yandex.ru/i/18idb03h7oxrBQ](https://disk.yandex.ru/i/18idb03h7oxrBQ)

**2. Серые и зеленые кнопки главной и внутренних страниц**
- Цвет серых кнопок: EBEDF0. [https://disk.yandex.ru/i/FDD7DfM1LzEqeA](https://disk.yandex.ru/i/FDD7DfM1LzEqeA)
- Шрифт. Font size: 16px, Line height: 24px, Font - weight: Regular. [https://disk.yandex.ru/i/YPodTKuHqeQIjQ](https://disk.yandex.ru/i/YPodTKuHqeQIjQ)
- Эффект при наведении: [Ссылка на Figma](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=11713%3A155577). [Ссылка на скрин](https://skr.sh/sG8JVtI8DcL)

**Comment by SergeyPilipenko** [comment]
2.3.28-beta исправлено
