### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку Tile

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#551]
**1. Плитки на разводящей странице для частных клиентов**
- Высота плиток: 320px, постоянная. [https://disk.yandex.ru/i/Cxyx5EfHnpDxZg](https://disk.yandex.ru/i/Cxyx5EfHnpDxZg)
- Шрифт заголовка. H4 Font size: 28px, Line height: 36px, Font - weight: Regular. [https://disk.yandex.ru/d/yc-lkEtepPV7og](https://disk.yandex.ru/d/yc-lkEtepPV7og)
- Шрифт второстепенного текста. Font size: 26px, Line height: 36px, Font - weight: Light. [https://disk.yandex.ru/i/xdOr1eUm_gq2Xg](https://disk.yandex.ru/i/xdOr1eUm_gq2Xg)
- Отступ между преимуществами: 7px. [https://disk.yandex.ru/i/GoehCUvF809nGg](https://disk.yandex.ru/i/GoehCUvF809nGg)
- Отступ от заголовка до преимуществ/текста: 10px. [https://disk.yandex.ru/i/DItMfOOCgCSryQ](https://disk.yandex.ru/i/DItMfOOCgCSryQ)
- Текст в кнопках по центру. Ховер эффект, как у зеленых кнопок. [https://disk.yandex.ru/d/YC5cJyMsTQTAuw](https://disk.yandex.ru/d/YC5cJyMsTQTAuw)
[Ссылка на Figma](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=12131%3A171338)

**2. Блок преимуществ во вкладах** [Как выглядит](https://disk.yandex.ru/i/zgNJKem3xNYsdA)
- Высота блока 320px. [https://disk.yandex.ru/d/Yj58IH-ge7XQ1g](https://disk.yandex.ru/d/Yj58IH-ge7XQ1g)
- Заголовки белого и зеленого блоков: [https://disk.yandex.ru/d/H6DjhjqAYpv-9g](https://disk.yandex.ru/d/H6DjhjqAYpv-9g)
- Текст преимущест в обоих блоках: [https://disk.yandex.ru/d/6u_yXdVBA1abGQ](https://disk.yandex.ru/d/6u_yXdVBA1abGQ)
- Отступы белого блока. От заголовка до преимуществ 12px. Между преимуществами 6px. [https://disk.yandex.ru/i/2epdNcP2mOEUXw](https://disk.yandex.ru/i/2epdNcP2mOEUXw)
- Отступ зеленого блока от заголовка до описания 8px. [https://disk.yandex.ru/d/ThoGzZNqSpEpBw](https://disk.yandex.ru/d/ThoGzZNqSpEpBw)

**3. Блок преимуществ в кредитах и картах** [Как выглядит](https://disk.yandex.ru/i/yTIlEvFKApZMVw)
- Высота блока 400px. [https://disk.yandex.ru/i/AviXAhOguwGyrg](https://disk.yandex.ru/i/AviXAhOguwGyrg)
- Заголовок зеленого блока: [https://disk.yandex.ru/i/IObL84CgpMt02w](https://disk.yandex.ru/i/IObL84CgpMt02w)
- Заголовок белого блока: [https://disk.yandex.ru/d/v_zBvHr-DwVoLA](https://disk.yandex.ru/d/v_zBvHr-DwVoLA)
- Текст преимуществ: [https://disk.yandex.ru/i/S3cFHx0MeQSJ4g](https://disk.yandex.ru/i/S3cFHx0MeQSJ4g)

**Comment by klapada** [comment]
Ввиду того, что размеры текста в списке различаются на разных страницах и нет возможности привести их к единому значению, необходимо в панели настроек блока добавить возможность выбора размера шрифта для элементов списка.
Добавить новое поле "Размер пунктов списка" (место показано на Скрине ниже):
- тип: дропдаун
- возможные варианты: список всех размеров шрифтов
- значение по умолчанию: H5 (=24px)

<img width="457" alt="Screenshot 2022-10-14 at 11 49 25" src="https://user-images.githubusercontent.com/112703510/195807751-63bfeb56-8ae1-4a90-8a29-ef5d78b4a39c.png">

**Comment by SergeyPilipenko** [comment]
2.3.29-beta не исправлено:
- Плитки на разводящей странице для частных клиентов
1. Шрифт второстепенного текста. Font size: 26px, Line height: 36px, Font - weight: Light. https://disk.yandex.ru/i/xdOr1eUm_gq2Xg
2. Отступ от заголовка до преимуществ/текста: 10px. https://disk.yandex.ru/i/DItMfOOCgCSryQ

- Блок преимуществ во вкладах [Как выглядит](https://disk.yandex.ru/i/zgNJKem3xNYsdA)
1. Отступ зеленого блока от заголовка до описания 8px. https://disk.yandex.ru/d/ThoGzZNqSpEpBw

1. Блок преимуществ в кредитах и картах [Как выглядит](https://disk.yandex.ru/i/yTIlEvFKApZMVw)
-

**Comment by klapada** [comment]
Для поля "Размер пунктов списка" в дропдауне сделать доступными только 2 варианта:
- XL_L (=18px)
- H5_L (=24px)

**Comment by SergeyPilipenko** [comment]
В ип2.0 не исправлено:

- Плитки на разводящей странице для частных клиентов
1. Шрифт Описания 20, по макету 24
2. В КР в настройках размера списка есть 3 варианта: маленький 16, средний 20, большой 24, согласно комментарию Ксюши выше должно быть 2 варианта: 18 и 24

**Comment by Longraf** [comment]
![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/32570545/f986cff9-3e28-4f33-a62f-c9df59bc2846)
