### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку OtherProducts

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#552]
**1. Другие продукты**

- [x] - Шрифт. H4 Font size: 28px, Line height: 36px, Font - weight: Regular. [https://disk.yandex.ru/i/63kN9BGAbFuOJQ](https://disk.yandex.ru/i/63kN9BGAbFuOJQ)
- [x] - Иконка белого цвета. [https://disk.yandex.ru/i/oEbx4TY3rsrT9w](https://disk.yandex.ru/i/oEbx4TY3rsrT9w) (связано с https://github.com/redneckz/temp_wcms/issues/427 )
- [x] - Добавить ховер из ui kit. [https://disk.yandex.ru/i/oj21nptR0m8BYQ](https://disk.yandex.ru/i/oj21nptR0m8BYQ)
- [x] - Раскрывающиеся плитки с отступами 4px, такие же, как выше. [https://disk.yandex.ru/i/q248sXEL3HvqGA](https://disk.yandex.ru/i/q248sXEL3HvqGA)

**2. Раскрывающиеся продуктовые плитки (ProductTile)**

- [x] - Должны быть 2 блока 1/2 и 1 на всю ширину [https://disk.yandex.ru/d/jXPz5n-W8xd64A](https://disk.yandex.ru/d/jXPz5n-W8xd64A)

**Comment by Irinaristova** [comment]
По второму пункту в Safari баг будет поправлен в рамках бага #427

**Comment by SergeyPilipenko** [comment]
2.3.29-beta проверено, на ховер баг https://github.com/redneckz/temp_wcms/issues/568
