### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку Calculator

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#553]
**1. Табы калькулятора**
- Шрифт заголовка активного таба: Font size: 18px, Line height: 24px, Font - weight: regular. Второстепенный шрифт активного таба: L Font size: 16px, Line height: 24px, Font - weight: Light. [https://disk.yandex.ru/i/ggWL6EyaeWqeyQ](https://disk.yandex.ru/i/ggWL6EyaeWqeyQ)
- Шрифт заголовка не активного таба: L Font size: 16px, Line height: 24px, Font - weight: regular. Второстепенный шрифт не активного таба: M Font size: 15px, Line height: 20px, Font - weight: Light. [https://disk.yandex.ru/i/UjT7r18kYRrPzw](https://disk.yandex.ru/i/UjT7r18kYRrPzw)
- Иконку ипотеки сменить. [https://disk.yandex.ru/d/9amMb41qxcIb-Q](https://disk.yandex.ru/d/9amMb41qxcIb-Q)
- Иконки активного таба белые. [https://disk.yandex.ru/i/RUoHzKtvs2680Q](https://disk.yandex.ru/i/RUoHzKtvs2680Q)
- Добавить состояние при наведении на таб [https://disk.yandex.ru/i/GENcK0iUiAC24A](https://disk.yandex.ru/i/GENcK0iUiAC24A) 
[Ссылка на Figma](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_Основной_сайт-(Частным-клиентам)?node-id=7991%3A161459)

**2. Калькулятор на главной**
- Стилизовать input slider по ui kit. Добавить состояния ховера и активности. [https://disk.yandex.ru/i/CkM9Cw27wFjVYg](https://disk.yandex.ru/i/CkM9Cw27wFjVYg)
- Кнопки поправить по ui kit. Шрифт. Состояния. [https://disk.yandex.ru/i/WqL3bO5HerwpQw](https://disk.yandex.ru/i/WqL3bO5HerwpQw)
- Чекбокс. Ховер состояние по ui kit. Шрифт: L Font size: 16px, Line height: 24px, Font - weight: Light. [https://disk.yandex.ru/d/vAZL5HYXqPM-mg](https://disk.yandex.ru/d/vAZL5HYXqPM-mg)
- Поправить шрифты и отступы. [https://disk.yandex.ru/i/3cHZ74HIfSmAZg](https://disk.yandex.ru/i/3cHZ74HIfSmAZg)
- Сделать блок изменяющимся по высоте, чтобы не было пустого места снизу. [https://disk.yandex.ru/d/--d3KFTskK1MaQ](https://disk.yandex.ru/d/--d3KFTskK1MaQ)
[Ссылка на Figma](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=12780%3A147240)
- Добавить ховер для стрелки листания табов [https://disk.yandex.ru/i/9aup5qP2KeKBJQ](https://disk.yandex.ru/i/9aup5qP2KeKBJQ)
[Ссылка на Figma](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=12780%3A147240)

**Comment by KolyaBlacK** [comment]
Стилизовать input slider по ui kit. done

**Comment by KolyaBlacK** [comment]
2. Калькулятор на главной done

**Comment by SergeyPilipenko** [comment]
2.3.29-beta исправлено
