### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку ExchangeRateTile

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#554]
**1. Курсы обмена валют**

- [x] - Заголовок. H4 Font size: 28px, Line height: 36px, Font - weight: Regular. [https://disk.yandex.ru/i/3JSCEuwbEFDvyQ](https://disk.yandex.ru/i/3JSCEuwbEFDvyQ)
- [x] - Текст шапки таблицы. M Font size: 15px, Line height: 20px, Font - weight: Light. [https://disk.yandex.ru/i/8UGEFjMBbh2a2Q](https://disk.yandex.ru/i/8UGEFjMBbh2a2Q)
- [x] - Контент таблицы. H6 Font size: 20px, Line height: 28px, Font - weight: Regular. [https://disk.yandex.ru/i/RyWvN5YTGTrQlQ](https://disk.yandex.ru/i/RyWvN5YTGTrQlQ)
- [x] - Поправить отступы [https://disk.yandex.ru/i/BH2MZNqtwigjlw](https://disk.yandex.ru/i/BH2MZNqtwigjlw)
- [x] - Ближайший офис. L Font size: 16px, Line height: 24px, Font - weight: Regular. [https://disk.yandex.ru/i/RnO0wOG3jkwqIA](https://disk.yandex.ru/i/RnO0wOG3jkwqIA)
- [x] - Второстепенный текст. M Font size: 15px, Line height: 20px, Font - weight: Light. [https://disk.yandex.ru/i/jWEt_cGR026UCw](https://disk.yandex.ru/i/jWEt_cGR026UCw)

**2. Инпуты и кнопка курсов обмена валют**

- [x] - Стилизовать по дизайну размеры, шрифты. [https://disk.yandex.ru/d/WQDhDlfZkyMSGw](https://disk.yandex.ru/d/WQDhDlfZkyMSGw)
- [x] - Поправить отступы. [https://disk.yandex.ru/d/ELOtvGd8QhCXvg](https://disk.yandex.ru/d/ELOtvGd8QhCXvg)
- [x] - Поменять hover, active состояния из ui kit. [https://disk.yandex.ru/i/_Ek30iqCAUvnWQ](https://disk.yandex.ru/i/_Ek30iqCAUvnWQ)
- [x] - Добавить стилизованный droplist выбора валюты. [https://disk.yandex.ru/i/Db_53W7P_plPdw](https://disk.yandex.ru/i/Db_53W7P_plPdw)
- [x] [Ссылка на Figma](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7991%3A161459)
- [x] - Высота блока 320px постоянная. [https://disk.yandex.ru/i/RCwFWsE47sAQkA](https://disk.yandex.ru/i/RCwFWsE47sAQkA)

**Comment by Irinaristova** [comment]
В пункте 2 последний подпункт договорились на минимальную высоту

**Comment by Irinaristova** [comment]
В первом пункте по 4 подпункту договорили все отступы сделать 36px

**Comment by Irinaristova** [comment]
этот блок еще не влит просто, нужна перепроверка после обновления

**Comment by SergeyPilipenko** [comment]
Проверено в ИП2.0, не исправлены пункты:
1. Название валюты в полях с выпадающим списком: font-size 15(font-weight 300), по макету font-size 16(font-weight 400)
2. У выпадающего списка с валютами нет тени, по ui-kit есть
3. Выпадающий список с валютами не скрывается если кликнуть в произвольной области страницы



![Image](https://user-images.githubusercontent.com/22083206/201611640-4b71a05a-3def-4230-8f1f-aadb6683e625.png)
