### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку MobileAppTile

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#555]
- Заголовок. H4 Font size: 28px, Line height: 36px, Font - weight: Regular. [https://disk.yandex.ru/d/2rQDc5Kw7-ZDuA](https://disk.yandex.ru/d/2rQDc5Kw7-ZDuA)
- Текст. M Font size: 15px, Line height: 20px, Font - weight: Light. [https://disk.yandex.ru/d/sPFVISJ3PmbH2A](https://disk.yandex.ru/d/sPFVISJ3PmbH2A)
- Картинка QR кода 92х92px. [https://disk.yandex.ru/i/oXo8qKHjZmSAcA](https://disk.yandex.ru/i/oXo8qKHjZmSAcA)
- Убрать кликабельность у картинки.
- Кнопки. Добавить новый ховер эффект из ui kit. [https://disk.yandex.ru/i/dyXFMKSI6SeA3g](https://disk.yandex.ru/i/dyXFMKSI6SeA3g)
- Высота блока 320px постоянная. [https://disk.yandex.ru/d/FrspXuHnLSpfMw](https://disk.yandex.ru/d/FrspXuHnLSpfMw)

**Comment by SergeyPilipenko** [comment]
2.3.25-beta
https://10.80.4.9/natural

- Картинка QR кода 164*164
- По макету ширина кнопок должна быть 168, сейчас 152 и 163

**Comment by Longraf** [comment]
Картинка по макету 92x92px понимать как минимальную ширину иначе если в QR много текста становится нечитаемым.
Ширина кнопок поправлена.

**Comment by SergeyPilipenko** [comment]
2.3.29-beta, не исправлено: сейчас ширина кнопок 166, по макету 168
https://10.80.4.9/natural

**Comment by SergeyPilipenko** [comment]
Обсудили с Юрой, ширина 168 кнопки с бордером 168, бордер изначально прозрачный поэтому 166
