### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку NavigatorTabs

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#556]
- Отступы сверху/снизу и между табами 4px. [https://disk.yandex.ru/i/4fXrrmCoB8XJRQ](https://disk.yandex.ru/i/4fXrrmCoB8XJRQ)
- Отступ от названия таба до цифры: 8px. [https://disk.yandex.ru/i/IrkeGTYPchxiLg](https://disk.yandex.ru/i/IrkeGTYPchxiLg)
- Шрифт названия таба: [https://disk.yandex.ru/i/m35bwhCUhN8Gew](https://disk.yandex.ru/i/m35bwhCUhN8Gew)
- Шрифт цифры: Font size: 11px, Line height: 22px, Font - weight: Regular.
- Цвет фона цифры: [https://disk.yandex.ru/i/P4qpezKkzj9kqQ](https://disk.yandex.ru/i/P4qpezKkzj9kqQ)
- При ховере цифра тоже меняет цвет. [https://disk.yandex.ru/i/6wYGAUf_imM39A](https://disk.yandex.ru/i/6wYGAUf_imM39A)
- Текст табов: [https://disk.yandex.ru/d/UG5Xp6q9Dm89Xg](https://disk.yandex.ru/d/UG5Xp6q9Dm89Xg)
- При нажатии на таб добавить прокрутку страницы, вместо моментального перемещения

**Comment by klapada** [comment]
Тут неверно указала, к NavigatorTabs относятся только следующие пункты:
- Текст табов: https://disk.yandex.ru/d/UG5Xp6q9Dm89Xg
- При нажатии на таб добавить прокрутку страницы, вместо моментального перемещения

Остальные пункты относятся к GroupBlock, для которого будет отдельная задача.

**Comment by SergeyPilipenko** [comment]
2.3.24-beta NavigatorTabs проверено
