### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку ProductTile

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#557]
**1. Продуктовая плитка 1/2**

- [x] - Высота блока постоянная 364px [https://disk.yandex.ru/d/vXePfSfHqS6u5A](https://disk.yandex.ru/d/vXePfSfHqS6u5A)

- [x] - Отступы по краям 36px. [https://disk.yandex.ru/i/cvhIUZ6DEG_dhw](https://disk.yandex.ru/i/cvhIUZ6DEG_dhw)

- [x] - Отступ между заголовком и текстом: 8px. Между текстом и преимуществами 14px. 

[https://disk.yandex.ru/d/hOT4iVJ0iEj_cw](https://disk.yandex.ru/d/hOT4iVJ0iEj_cw)

- [x] - Контейнер текста на всю ширину блока с отступами 36px. [https://disk.yandex.ru/d/h-tF5vb1kPKkFQ](https://disk.yandex.ru/d/h-tF5vb1kPKkFQ)

- [x] - Отступ между преимуществами 10px. [https://disk.yandex.ru/i/Z5mEQXGTwFGHjA](https://disk.yandex.ru/i/Z5mEQXGTwFGHjA)

- [x] - Отступ между кнопками 16px. [https://disk.yandex.ru/i/gcb_YJt_w0fNTw](https://disk.yandex.ru/i/gcb_YJt_w0fNTw)
- [x] - Кнопки и их состояния привести ui kit. [https://disk.yandex.ru/i/CATvjB_WKbwl0A]

(https://disk.yandex.ru/i/CATvjB_WKbwl0A)

- [x] - Шрифт заголовка: [https://disk.yandex.ru/i/E8nGlFWW5PgrCQ](https://disk.yandex.ru/i/E8nGlFWW5PgrCQ)
- [x] - Шрифт описания: [https://disk.yandex.ru/i/Si_VhdhBunEIzA](https://disk.yandex.ru/i/Si_VhdhBunEIzA)
- [x] - Шрифт заголовка преимущества: [https://disk.yandex.ru/i/NHkP_wdkgMgnVQ](https://disk.yandex.ru/i/NHkP_wdkgMgnVQ)
- [x] - Шрифт описания преимущества: [https://disk.yandex.ru/i/EHtEVBIWQmuJZQ](https://disk.yandex.ru/i/EHtEVBIWQmuJZQ)

**2. Продуктовая плитка на всю ширину**

- [x] - Высота блока постоянная 364px [https://disk.yandex.ru/i/3NhKrc67KVmPKQ](https://disk.yandex.ru/i/3NhKrc67KVmPKQ)
- [x] - Отступы по краям 36px. [https://disk.yandex.ru/i/miTqzBXLbICOwA](https://disk.yandex.ru/i/miTqzBXLbICOwA)
- [x] - Отступ между заголовком и тектом: 8px. Между текстом и преимуществами 14px. [https://disk.yandex.ru/d/YEUdSV9-EGuPMA](https://disk.yandex.ru/d/YEUdSV9-EGuPMA)
- [x] - Контейнер текста на всю ширину блока с отступами 36px. [https://disk.yandex.ru/i/slc03s_GUgeC2w](https://disk.yandex.ru/i/slc03s_GUgeC2w)
- [x] - Отступ между преимуществами 10px. [https://disk.yandex.ru/d/hhBelAWsw1VmxA](https://disk.yandex.ru/d/hhBelAWsw1VmxA)
- [x] - Отступ между кнопками 16px. [https://disk.yandex.ru/i/mJWWy2GY4vV8cw](https://disk.yandex.ru/i/mJWWy2GY4vV8cw)
- [x] - Кнопки и их состояния привести ui kit. [https://disk.yandex.ru/i/CATvjB_WKbwl0A](https://disk.yandex.ru/i/CATvjB_WKbwl0A)
- [x] - Шрифт заголовка: [https://disk.yandex.ru/i/E8nGlFWW5PgrCQ](https://disk.yandex.ru/i/E8nGlFWW5PgrCQ)
- [x] - Шрифт описания: [https://disk.yandex.ru/i/Si_VhdhBunEIzA](https://disk.yandex.ru/i/Si_VhdhBunEIzA)
- [x] - Шрифт заголовка преимущества: [https://disk.yandex.ru/i/NHkP_wdkgMgnVQ](https://disk.yandex.ru/i/NHkP_wdkgMgnVQ)
- [x] - Шрифт описания преимущества: [https://disk.yandex.ru/i/EHtEVBIWQmuJZQ](https://disk.yandex.ru/i/EHtEVBIWQmuJZQ)

**Comment by Irinaristova** [comment]
по первому подпункту в обоих пунктах решили делать минимальную высоту 364px, а не фиксированную

**Comment by Irinaristova** [comment]
Пункты с состоянием кнопок и шрифтами поправлены в других мр-ах и влиты

**Comment by Irinaristova** [comment]
Третий пункт поправлен в мр-е - https://github.com/redneckz/wildless-cms-uni-blocks/pull/566

**Comment by SergeyPilipenko** [comment]
2.3.29-beta
https://10.80.4.9/loans

1. Не исправлены пункты с мин высотой блока, на странице они 360
2. На странице https://10.80.4.9/deposits некорректное отображение описания преимуществ

**Comment by Irinaristova** [comment]
по пункту 2:  picture width = 242px. текст может заходить на картинку примерно на 20px

**Comment by SergeyPilipenko** [comment]
2.3.31-beta
https://10.80.4.9/deposits

У описания преимуществ текст в несколько строк, по макету должно быть в одну строку

![Image](https://user-images.githubusercontent.com/22083206/200332207-de2e16a1-3e27-4367-aefe-848682d319b2.png)

**Comment by Irinaristova** [comment]
нужна перепроверка после обновления версии на портале

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0, проблема из комментария выше не исправлена

**Comment by Irinaristova** [comment]
На данный момент при col-span-6 и длинного описания баг не воспроизводится
<img width="1292" alt="Screenshot 2023-04-20 at 17 48 35" src="https://user-images.githubusercontent.com/38761239/233403282-d017978b-3167-4e31-a5b7-e43f284196c6.png">

**Comment by SergeyPilipenko** [comment]
2.3.65-beta исправлено в даталайне
