### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку BenefitsBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#558]
- Текст заголовока блока: [https://disk.yandex.ru/i/5Pt5moo342XqlA](https://disk.yandex.ru/i/5Pt5moo342XqlA)
- Текст заголовока преимущества: [https://disk.yandex.ru/i/3kpq8eLtWw_a1Q](https://disk.yandex.ru/i/3kpq8eLtWw_a1Q)
- Текст преимущества: [https://disk.yandex.ru/i/QlKDxxvO1bUA4Q](https://disk.yandex.ru/i/QlKDxxvO1bUA4Q)
- Цвет текста преимущества: [https://disk.yandex.ru/i/gLQOmNx8y5wvYg](https://disk.yandex.ru/i/gLQOmNx8y5wvYg)
- Отступ между преимуществами: 80px. [https://disk.yandex.ru/i/UnnGHUjP16rJwA](https://disk.yandex.ru/i/UnnGHUjP16rJwA)

**Comment by SergeyPilipenko** [comment]
2.3.29-beta исправлено
