### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку StepsBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#559]
- Заголовок блока: [https://disk.yandex.ru/i/9et7R_M_xGD20A](https://disk.yandex.ru/i/9et7R_M_xGD20A)
- Цвет фона цифр: [https://disk.yandex.ru/i/O-qljkuhZA_CUQ](https://disk.yandex.ru/i/O-qljkuhZA_CUQ)
- Выровнять цифры. [https://disk.yandex.ru/i/2KI2u2_t2I4Zpw](https://disk.yandex.ru/i/2KI2u2_t2I4Zpw)
- Заменить кнопку из ui kit. Другая высота, шрифт. [https://disk.yandex.ru/d/iWwQOhFDPPd5eg](https://disk.yandex.ru/d/iWwQOhFDPPd5eg)

**Comment by SergeyPilipenko** [comment]
2.3.24-beta проверено
