### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку Accordion

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#560]
- [x] - Растояние между блоками 4px. [https://disk.yandex.ru/i/CTGSWDQotlwFlA](https://disk.yandex.ru/i/CTGSWDQotlwFlA)

- [x] - Заголовок блока: [https://disk.yandex.ru/d/BImUl_XoiRchxA](https://disk.yandex.ru/d/BImUl_XoiRchxA)

- [x] - Заголовок вопроса: [https://disk.yandex.ru/i/XmNxYLHC3MY1Zg](https://disk.yandex.ru/i/XmNxYLHC3MY1Zg)

- [x] - Текст ответа: [https://disk.yandex.ru/i/tKg7qSRorA21hQ](https://disk.yandex.ru/i/tKg7qSRorA21hQ)

- [x] - Отступ от заголовка вопроса до текста 14px. [https://disk.yandex.ru/d/HsRPHt8TLah43w](https://disk.yandex.ru/d/HsRPHt8TLah43w)

**Comment by klapada** [comment]
<img width="647" alt="Screenshot 2022-10-10 at 10 48 04" src="https://user-images.githubusercontent.com/112703510/194820169-560c32c8-b194-4cdd-8747-4786db80dc23.png">

**Comment by klapada** [comment]
В описании в п.3 у заголовка вопроса указан неверный размер шрифта. Верный H6 (скрин ниже)
<img width="266" alt="Screenshot 2022-10-10 at 11 14 09" src="https://user-images.githubusercontent.com/112703510/194823677-6d316ee9-ca6e-42b5-af5e-3de4d32a4167.png">

**Comment by Irinaristova** [comment]
Поскольку в акордион может быть добавлен любой блок в качестве контента, решили с Ксенией оставить шрифты для пункта 4 в том виде, в котором они сейчас есть

**Comment by SergeyPilipenko** [comment]
2.3.29-beta не сиправлен п3: Заголовок вопроса: https://disk.yandex.ru/i/XmNxYLHC3MY1Zg
Сейчас размер шрифта 18, font-weight 500

**Comment by Irinaristova** [comment]
по пункту 3 с Ксенией договорились оставить так, как есть сейчас
