### ISSUE TITLE
[Uni Blocks] Новый блок Перевод с карты на карту

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#563]
Необходимо реализовать новый блок Перевод с карты на карту согласно Скрину 1 ниже.
Добавить в панели настроек поля для настройки блока как показано на Скрине 2.
Логика работы полей в новом блоке:
- Сумма перевода
  - тип: числовое поле
  - значение по умолчанию: null
  - плейсхолдер: "1500"
- Далее
  - тип: кнопка
  - при клике: переход в текущей вкладке браузера на страницу осуществления перевода с передачей суммы, которая введена в поле "Сумма перевода"
    - request URL: https://www.rshb.ru/p2p/
    - request method: POST
    - в теле запроса передача значения amount (введенная сумма в поле "Сумма перевода")

Скрин 1. Вид нового блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7928%3A152869))
![Image](https://user-images.githubusercontent.com/112703510/193546935-cdb5fd11-4a9f-463b-817e-7fa39cc1ead3.png)

Скрин 2. Настройки нового блока
![Image](https://user-images.githubusercontent.com/112703510/193549285-67675c94-1fe5-4ec4-93cb-b3399c89cd1d.png)

**Comment by SergeyPilipenko** [comment]
2.3.28-beta проверено
