### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку GroupBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#567]
- [x] - Отступы сверху/снизу и между табами 4px. [https://disk.yandex.ru/i/4fXrrmCoB8XJRQ](https://disk.yandex.ru/i/4fXrrmCoB8XJRQ)

- [x] - Отступ от названия таба до цифры: 8px. [https://disk.yandex.ru/i/IrkeGTYPchxiLg](https://disk.yandex.ru/i/IrkeGTYPchxiLg)

- [x] - Шрифт названия таба: [https://disk.yandex.ru/i/m35bwhCUhN8Gew](https://disk.yandex.ru/i/m35bwhCUhN8Gew)

- [x] - Шрифт цифры: Font size: 11px, Line height: 22px, Font - weight: Regular.

- [x] - Цвет фона цифры: [https://disk.yandex.ru/i/P4qpezKkzj9kqQ](https://disk.yandex.ru/i/P4qpezKkzj9kqQ)

- [x] - При ховере цифра тоже меняет цвет. [https://disk.yandex.ru/i/6wYGAUf_imM39A](https://disk.yandex.ru/i/6wYGAUf_imM39A)

**Comment by Irinaristova** [comment]
4 пункт договорились с дизайнером на шрифт 12px 300
