### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку ProductBlock

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#570]
- [x] - Высота блока 454px постоянная. [https://disk.yandex.ru/d/GGBGSQ8l164IKw](https://disk.yandex.ru/d/GGBGSQ8l164IKw)
- [x] - Шрифт заголовка. https://disk.yandex.ru/d/UHTXHgmYajdtdw
- [x] - Шрифт текста. https://disk.yandex.ru/i/EFIAE26j2w-9yg
- [x] - Шрифт заголовка преимущества. https://disk.yandex.ru/i/_UMI9Sa5SZBLWw
- [x] - Шрифт описания преимущества. https://disk.yandex.ru/d/aDt9zKio4SL5OQ
- [x] - Отступ от заголовка до верхней границы блока 50px. Отступ от кнопок до нижней границы блока 50px. [https://disk.yandex.ru/i/syWnpfoiU5Ofjg](https://disk.yandex.ru/i/syWnpfoiU5Ofjg)
- [x] - Текст в кнопках по центру. Шрифт в кнопке по ui kit. Поправить состояния. [https://disk.yandex.ru/d/yi7FLtoGj8EsBQ](https://disk.yandex.ru/d/yi7FLtoGj8EsBQ)
- [x] - Высота блока 528px постоянная (если в блоке есть кнопка для возврата). [https://disk.yandex.ru/d/d-w2aYbTpa9KPQ](https://disk.yandex.ru/d/d-w2aYbTpa9KPQ)
- [x] - Добавить ховер для кнопки возврата ко всем продуктам. Сделать кликабельным кнопку и текст. [https://disk.yandex.ru/d/Fw7WcdB8t-bPgQ](https://disk.yandex.ru/d/Fw7WcdB8t-bPgQ)
- [x] - Кнопка добавить новый hover: [https://disk.yandex.ru/d/RzNppP4QPs7I0Q](https://disk.yandex.ru/d/RzNppP4QPs7I0Q)

**Comment by Irinaristova** [comment]
По первому пункту договорились, что будет минимальная высота, а не постоянная

**Comment by SergeyPilipenko** [comment]
2.3.29-beta проверено
