### ISSUE TITLE
[Дизайн-ревью] Замечания по блоку Recommendation

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#571]
- Заголовок блока. H3 Font size: 32px, Line height: 40px, Font - weight: Regular. [https://disk.yandex.ru/i/JwGOdM9MC9bqHA](https://disk.yandex.ru/i/JwGOdM9MC9bqHA)
- Заголовок карточки. H5 Font size: 24px, Line height: 30px, Font - weight: Regular. [https://disk.yandex.ru/d/NYz__PVhNx9P3w](https://disk.yandex.ru/d/NYz__PVhNx9P3w)
- Текст карточки. XL Font size: 18px, Line height: 24px, Font - weight: Light. [https://disk.yandex.ru/i/wZy7jf0BlTM26w](https://disk.yandex.ru/i/wZy7jf0BlTM26w)
- Поправить отступы. [https://disk.yandex.ru/d/Y6edmBQOP5WZkg](https://disk.yandex.ru/d/Y6edmBQOP5WZkg)
- Высота блока: 426px.
- Добавить кнопкам новый hover из ui kit. [https://disk.yandex.ru/d/O35edc45jdhqYQ](https://disk.yandex.ru/d/O35edc45jdhqYQ)
- Кнопка со стрелкой по центру карточек. При наведении иконка красится в зеленый. [https://disk.yandex.ru/i/HDtBluknm53eoA](https://disk.yandex.ru/i/HDtBluknm53eoA)

**Comment by end0rfin** [comment]
Исправлено в рамках задачи https://github.com/redneckz/temp_wcms/issues/469
