### ISSUE TITLE
[Uni Blocks] Новый блок для ошибки

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#602]
Необходимо реализовать новый блок для вывода ошибки на странице (Скрин 1-2).

Добавить в панели справа следующие поля для настройки блока (Скрин 3):
- **Заголовок**
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок"
- **Описание**
  - тип: текстовое поле
  - значение по умолчанию: "Описание"
- **Вид контента**
  - тип: дропдаун
  - возможные значения:
    - Изображение
    - Число
  - значение по умолчанию: "Число"
  - при выборе значения "Число" появляется поле:
    - тип: числовое поле
    - значение по умолчанию: 404
  - при выборе значения "Изображение" появляются поля для загрузки своего изображения или выбора иконки из списка (Скрин 5)
- **Добавить кнопку**
  - тип: кнопка
  - при клике появляются следующие поля (Скрин 4):
    - **Текст**
      - тип: текстовое поле
      - значение по умолчанию: "Кнопка"
    - **URL**
      - тип: текстовое поле
      - значение по умолчанию: null
    - **Переход по ссылке**
      - тип: дропдаун
      - значение по умолчанию: В текущей вкладке
    - **Цвет кнопки**
      - тип: тип: дропдаун
      - значение по умолчанию: Основной
    - **Закругленные углы**
      - тип: чекбокс
      - значение по умолчанию: false
  - кнопку можно добавить/удалить

Скрин 1. Вид блока с номером ошибки и кнопкой ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=14448%3A150771))
![Image](https://user-images.githubusercontent.com/112703510/194577462-f936c8bf-c3a5-496c-88cc-ff7e2d375366.png)

Скрин 2. Вид блока с картинкой и без кнопки ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=14448%3A150786))
![Image](https://user-images.githubusercontent.com/112703510/194577505-255ff065-74ae-47ef-8622-756377d76208.png)

Скрин 3. Настройки блока по умолчанию
![Image](https://user-images.githubusercontent.com/112703510/194577621-008f888c-38e6-48c1-bc3b-6dc175ccf194.png)

Скрин 4. Настройки кнопки
![Image](https://user-images.githubusercontent.com/112703510/194577776-54625ee3-7d64-487b-944f-e1fe7e514e13.png)

Скрин 5. Выбор изображения
![Image](https://user-images.githubusercontent.com/112703510/194824943-303eebc5-dbf9-40ed-825a-34a4be828977.png)

**Comment by SergeyPilipenko** [comment]
2.3.28-beta проверено
