### ISSUE TITLE
[Uni Blocks] Убрать ограничение по кол-ву вложенных блоков внутри Других продуктов (OtherProducts)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#607]
Сейчас в OtherProducts есть ограничение на добавление только 10 вложенных блоков (на Скрине 2 видно, что кнопки "+Блоки" в настройках нет), но есть страницы, на которых может быть 14 или более вложенных блоков, поэтому необходимо данное ограничение убрать.

Скрин 1. Добавлено 9 блоков
![Image](https://user-images.githubusercontent.com/112703510/194848762-e7ed2705-c795-4de2-ba26-4a73e0efedf4.png)

Скрин 2. Добавлено 10 блоков
![Image](https://user-images.githubusercontent.com/112703510/194848863-22f9d23b-c610-473f-8bbf-233cc523064a.png)

**Comment by SergeyPilipenko** [comment]
проверено
