### ISSUE TITLE
[Uni Blocks] Объединить компонент Insurance с PictureBlock

### ISSUE THREAD

**Issue by Longraf** [redneckz/wildless-cms-uni-blocks#621]
Из компонента Insurance свойства sum и monthLimit перенести в PictureBlock это будут опциональные свойства
![image](https://user-images.githubusercontent.com/32570545/195104957-e7a63722-1d04-4361-befa-d8f4e079c3ef.png)
![image](https://user-images.githubusercontent.com/32570545/195105278-a8e1da1a-f738-4fcc-ba46-f6e84542d342.png)

**Comment by SergeyPilipenko** [comment]
проверено
