### ISSUE TITLE
[Uni Blocks] Новый блок с перечнем услуг офиса

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#652]
Необходимо реализовать новый блок для возможности создания списка с иконками (Скрин ниже).

В панели настроек блока необходимо добавить следующие поля:
- Заголовок
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок"
- Список
  - Пункт
    - Текст
      - тип: текстовое поле
      - значение по умолчанию: "Пункт 1"
    - Выбрать иконку из списка
      - тип: кнопка
      - при клике открывается список иконок
  - Добавить пункт
    - тип: кнопка
    - при клике добавляются поля для нового пункта - "Текст" и "Выбрать иконку из списка"
    - кол-во пунктов:
      - мин = 1
      - макс = нет ограничений
- Стили
  - Ширина (колонок)
  - Поле для ввода класса
  - Якорная ссылка
 

Скрин 1. Вид нового блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7847%3A200170))
![Image](https://user-images.githubusercontent.com/112703510/195854457-d2aae7d2-546f-4a21-92d3-306a824aff5f.png)

Скрин 2. Панель настроек нового блока
![Image](https://user-images.githubusercontent.com/112703510/195864643-6fccf014-44f1-4e9b-b943-d077453f81d1.png)

**Comment by Mikage777** [comment]
Имеется готовая верстка от стажера. Необходимо допилить ее до нужного состояния.

**Comment by SergeyPilipenko** [comment]
2.3.28-beta проверено
