### ISSUE TITLE
[Uni Blocks] Новый блок Карта всех офисов/банкоматов

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#694]
Необходимо реализовать новый блок для отображения карты со списком всех офисов или банкоматов в выбранном регионе

#### 1. В настройки блока необходимо добавить следующее поле (_Скрин 1_):
  - название поля: "Данные по:"
  - тип компнента : дропдаун
  - возможные значения: 
    - Офисам (= отображение блока с картой и списком всех офисов как на _Скрине 2 и 4_ ниже)
    - Банкоматам (= отображение блока с картой и списком всех банкоматов как на _Скрине 5 и 7_ ниже)
  - значение по умолчанию: "Офисам"
  - при выборе значения "Банкоматам" становятся доступными следующие поля в настройках (контент выводится в блоке как показано на _Скрине 8_ (выделено красным)):
    - **Описание**
    - Список
      - Пункт
        - **Текст**
          - тип компонента: текстовое поле
          - значение по умолчанию: null
        - **Изображение**
          - возможность загрузить иконку с компьютера или выбрать из списка
      - **Добавить пункт**
        - тип компонента: кнопка
        - при клике добавляются поля для создания нового пункта списка

![Image](https://user-images.githubusercontent.com/112703510/224999750-ad24d0ad-e86f-4fac-8a03-bfa06e564690.png)
_Скрин 1. Настройки блока_

#### 2. Описаний полей при выборе в настройках блока вывода данных по офисам

- Верхняя часть блока с картой (_Скрин 2_)
  - **Заголовок**
    - название в виде: "Офисы {"name" из справочника regions по выбранному региону в шапке в Род. падеже} филиала ({кол-во офисов в выбранном регионе})"
  - **Фильтры**
    - **Аренда индивидуальных сейфовых ячеек**
      - тип компонента: чекбокс
      - возможные значения:
        - true (= на карте, а также в списке карточек отображаются все офисы выбранного региона, у которых "safeBoxCaseVolumes" в справочнике branches не null)
        - false (= фильтр не применяется)
      - значение по умолчанию: false
    - **Открыты по субботам**
      - тип компонента: чекбокс
      - возможные значения:
        - true (= на карте, а также в списке карточек отображаются все офисы выбранного региона, у которых в массиве "workSchedule" значение "workingSaturday" = true в справочнике branches)
        - false (= фильтр не применяется)
      - значение по умолчанию: false
  - **Очистить фильтр**
    - тип компонента: кнопка
    - при клике происходит сброс всех фильтров до значений по умолчанию
    - отображается, если есть хотя бы один фильтр со значением true
  - **Карта**
    - **Введите адрес или метро**
      - при вводе адреса или метро на карте отображается указанная область с точками офисов
    - при клике на "точку" конкретного офиса отображается всплывающее окно со следующей информацией (данные из справочника branches):
      - название офиса (= "name")
      - адрес (= "address")
      - режим работы в виде: "Режим работы: {"workTime"} {"lunchHour"}; Рабочие дни: {пн,вт,ср,чт,пт,сб,вскр}" (примерный вид показан на _Скрине 3_)

![Image](https://user-images.githubusercontent.com/112703510/224052201-f7317338-84da-4b8e-9ae0-0c8601d3cfec.png)
_Скрин 2. Вид блока с данными по офисам ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=7847%3A206294&t=hoJT0YQRFBiBOLDq-4))_

![Image](https://user-images.githubusercontent.com/112703510/224054901-09c7efa8-83b3-46f0-b9f4-8088290cc5a8.png)
_Скрин 3. Информация об офисе во всплывающем окне_

- Карточка с данными по конкретному офису (данные из справочника branches) (_Скрин 4_)
  - **Название офиса** (= "name")
  - **Адрес** (= "address")
  - **Контакты**
    - **Телефон** (= "phone")
    - **Факс** (= "fax")
  - **Режим работы** (= "workSchedule")
  - **Курс обмена валюты** (= "exchangeRate")
  - **Лейбл режима работы** (в правом верхнем углу карточки)
    - отображается информация на текущий день
    - время указывается с учетом часового пояса (= "timeZone"), в котором находится офис
    - возможные варианты лейблов:
      - "Открыто до {время в формате HH:MM, до которого работает офис}"
      - "Перерыв {время в формате HH:MM, когда начинается обед}-{время в формате HH:MM, когда заканчивается обед}"
      - "Закрыто до завтра", если у офиса след день рабочий, а если нет, то "Закрыто до {дата, когда откроется офис в формате DD.MM}"
      - "Не работает", если у офиса в "closeDate" указана дата <= сегодняшней дате
    - одновременно могут быть только 2 лейбла: "Открыто до ..." и "Перерыв ..."

![Image](https://user-images.githubusercontent.com/112703510/223550742-7f53f5fa-dd53-40f0-86f9-5ff5c10a9bf8.png)
_Скрин 4. Вид карточки конкретного офиса_

#### 3. Описаний полей при выборе в настройках блока вывода данных по банкоматам/терминалам

- Верхняя часть блока с картой (_Скрин 5_)
  - **Заголовок** 
    - название в виде "Банкоматы {"name" из справочника regions по выбранному региону в шапке в Род. падеже} филиала ({кол-во банкоматов в выбранном регионе})"
  - **Фильтры**
    - **Банкоматы**
      - тип компонента: чекбокс
      - возможные значения:
        - true (= на карте, а также в списке карточек отображаются все банкоматы ("terminalType" = "банкомат" в справочнике atms))
        - false (= фильтр не применяется)
      - значение по умолчанию: true
    - **Терминалы**
      - тип компонента: чекбокс
      - возможные значения:
        - true (= на карте, а также в списке карточек отображаются все терминалы ("terminalType" = "терминал" в справочнике atms))
        - false (= фильтр не применяется)
      - значение по умолчанию: false
    - **Круглосуточно**
      - тип компонента: чекбокс
      - возможные значения:
        - true (= на карте, а также в списке карточек отображаются все банкоматы/терминалы выбранного региона, у которых "workTime" = "круглосуточно" в справочнике atms)
        - false (= фильтр не применяется)
      - значение по умолчанию: false
    - **Прием наличных**
      - тип компонента: чекбокс
      - возможные значения:
        - true (= на карте, а также в списке карточек отображаются все банкоматы/терминалы выбранного региона, у которых "billAcceptorEnable" = true в справочнике atms)
        - false (= фильтр не применяется)
      - значение по умолчанию: false
  - **Очистить фильтр**
    - тип компонента: кнопка
    - при клике происходит сброс всех фильтров до значений по умолчанию
    - отображается, если есть хотя бы один фильтр со значением true
  - **Карта** 
    - Введите адрес или метро
      - при вводе адреса или метро на карте отображается указанная область с точками банкоматов/терминалов
    - вид "точек":
      - для банкоматов ("terminalType" = "банкомат") темно-зеленого цвета
      - для терминалов ("terminalType" = "терминал") зеленого цвета
    - при клике на "точку" конкретного банкомата отображается всплывающее окно со следующей информацией (данные из справочника atms):
      - название банкомата: 
        - если "terminalType" = "банкомат", то в виде "Банкомат {atmCode}"
        - если "terminalType" = "терминал", то в виде "Платежный терминал {atmCode}"
      - адрес (= "address") (примерный вид показан на _Скрине 6_)
  
![Image](https://user-images.githubusercontent.com/112703510/225259960-8cfef25a-ac73-4994-920e-d7c2bab9825c.png)
_Скрин 5. Вид блока с данными по банкоматам ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=7847%3A203383&t=hoJT0YQRFBiBOLDq-4))_

![Image](https://user-images.githubusercontent.com/112703510/224057024-e345fab8-c666-494c-8085-d2f742f52458.png)
![Image](https://user-images.githubusercontent.com/112703510/224057106-6c11686d-56f5-47af-b035-084005fc18d7.png)
_Скрин 6. Информаци о банкомате/терминале во всплывающем окне_

- Карточка с данными по конкретному банкомату/терминалу (данные из справочника atms) (_Скрин 7_)
  - **Название** (= "location")
  - **Адрес банкомата** (= "address")
  - **Прием наличных пачкой**
    - отображается "Да", если в справочнике "billAcceptorType" = "банкомат принимает пачками"
    - отображается "Нет" в остальных случаях
  - **Устройство**
    - отображается "Банкомат", если в справочнике "terminalType" = "банкомат"
    - отображается "Терминал", если в справочнике "terminalType" = "терминал"
  - **Модуль приема наличных**
    - отображается "Да", если в справочнике "billAcceptorEnable" = true
    - отображается "Нет", если в справочнике "billAcceptorEnable" = false
  - **Доступ**
    - выводится значение "Общедоступный", если "atmAccess" = "внешняя установка" или "территория банка"
  - **Регистрационный номер** (= "atmCode")
  - **Лейбл режима работы** (= "workTime")

![Image](https://user-images.githubusercontent.com/112703510/224338253-e6873818-7eed-435d-b74f-1c3e2ae97aa6.png)
_Скрин 7. Вид карточки конкретного банкомата_

#### 4. Если в настройках блока было выбрано:
  - отображение данных по "Офисам", то после публикации на странице будет выводиться карта с "точками" офисов на ней, а под картой список всех офисов в выбранном регионе
  - отображение данных по "Банкоматам", то после публикации на странице будет выводиться карта с "точками" банкоматов на ней, а под картой список всех банкоматов в выбранном регионе

![Image](https://user-images.githubusercontent.com/112703510/225261347-9824a0a0-57e0-425a-a92b-d11e8afd7117.png)
_Скрин 8. Вывод информации по банкоматам_

**Comment by klapada** [comment]
Ссылка на API: https://dataservice.catalog.dev.rshbdev.ru/api/swagger-ui/index.html

**Comment by Guzlik123** [comment]
Проверено в ИП2.0
