### ISSUE TITLE
[Uni Blocks] Ограничение ширины блока

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#745]
Необходима возможность ограничения ширины блока в настройках у определенных блоков.

В подразделе "Стиль":
- слайдер "Ширина (колонок)":
  - может быть неактивным для изменения, если у блока есть ограничение, что он не может быть по ширине < 12 колонок
  - может иметь ограничения на мин значение, например = 8, т.е. слайдер можно изменять в пределах значений 8, 10 и 12
- поле для ввода class name
  - если есть ограничение, например блок не может быть меньше 6 колонок, то при выборе col-span < 6, ширина блока становится равным наименьшему значению, т.е. col-span-6

**Comment by vladeiko** [comment]
Необходимость в ограничении редактора в добавлении атома ширины отсутствует. Вероятнее всего, если редактор выбирает стилевые атомы самостоятельно, то он знает, что делает. Рядовой редактор вряд ли будет пользоваться чем-то, кроме слайдера

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
