### ISSUE TITLE
Вывод кастомной страницы-заглушки в IE при переходе на сайт

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#757]
Необходимо реализовать следующее:
1. сверстать кастомную страницу как на Скрине ниже
2. при переходе на сайт beta.rshb.ru в браузере IE выводить данную страницу-заглушку

Скрин. Страница-заглушки в IE ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=14448%3A150786&t=nw03N52ziofWNDMt-4))
![Image](https://user-images.githubusercontent.com/112703510/199737539-fc30c23d-aa32-4d18-96ee-740f1fff4065.png)

**Comment by Guzlik123** [comment]
![image](https://user-images.githubusercontent.com/110792030/205058999-8c902362-e84a-4ec9-b26e-d5bd68657c08.png)
![image](https://user-images.githubusercontent.com/110792030/205059021-8c1a35e0-c86e-4456-9660-a68282092247.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
