### ISSUE TITLE
Кабинет редактора. Открытие модалки выбора блоков в мобильном режиме - ошибки в консоли "undefuned href"

### ISSUE THREAD

**Issue by end0rfin** [redneckz/wildless-cms-uni-blocks#771]
При открытии модалки выбора блоков в мобильном режиме в консоли сыпятся ошибки:
- Uncaught TypeError: Cannot read properties of undefined (reading 'href') at renderButton (TableColumn.js:51:1)
-

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
