### ISSUE TITLE
[Uni Blocks] Доработка блока Мини-галерея (MiniGallery)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#775]
Необходимо доработать блок MiniGallery, а именно в настройках блока добавить следующие поля:
- **Размер заголовка блока**
  - название поля "Размер заголовка"
  - тип: дропдаун
  - возможные значения: все варианты заголовков
  - значение по умолчанию: H2 (40px)
- **Карточки**
  - **Размер заголовка карточки**
    - название поля "Размер заголовка"
    - тип: дропдаун
    - возможные значения: все варианты заголовков (среди значений должен быть L_L)
    - значение по умолчанию: XL_L (18px)
  - **Доп. описание (для указания даты в нижней части карточки как на Скрине 2)**
    - название поля "Дополнительное описание"
    - тип: текстовое поле
    - значение по умолчанию: null
  - **Выравнивание**
    - название поля "Выравнивание текста"
    - тип: дропдаун
    - возможные значения:
      - По левому краю
      - По центру
      - По правому краю
    - значение по умолчанию: "По центру"
    - выравнивание текста применяется к контенту карточки в полях "Заголовок", "Описание" и "Дополнительное описание"

Скрин 1. Вид блока - вариант 1 ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=14783%3A186890))
![Image](https://user-images.githubusercontent.com/112703510/200285646-85103363-5954-41eb-bcb9-b0db48a6803c.png)

Скрин 2. Вид блока - вариант 2 ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=14783%3A188781))
![Image](https://user-images.githubusercontent.com/112703510/200285664-e0629f01-4943-48e3-b71d-bb3ec3f318f1.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
