### ISSUE TITLE
[Uni Blocks] Новый блок для вывода информации по ИИС

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#795]
Необходимо реализовать новый блок как на Скрине 1 ниже.

В настройках блока необходимо добавить следующие поля:
- Список (п.1 на Скрине 1)
  - Буллиты
    - название поля: "Буллиты"
    - тип: чекбокс
    - возможные значения:
      - true (список с буллитами)
      - false (список без буллитов)
    - значение по умолчанию: true
  - Пункт списка 1
    - тип: текстовое поле
    - значение по умолчанию "Пункт 1"
    - можно удалить
    - можно поменять местами, если кол-во пунктов >1
  - Пункт списка 2
    - тип: текстовое поле
    - значение по умолчанию "Пункт 2"
    - можно удалить
    - можно поменять местами, если кол-во пунктов >1
  - Пункт списка 3
    - тип: текстовое поле
    - значение по умолчанию "Пункт 3"
    - можно удалить
    - можно поменять местами, если кол-во пунктов >1
  - Добавить пункт списка
    - название кнопки: "Добавить пункт"
    - тип: кнопка
    - при клике добавляется пустое текстовое поле внизу списка для ввода нового пункта

- Данные
  - **Элемент данных 1**
    - Название таймлайна (п.2 на Скрине 1)
      - название поля: "Название"
      - тип: текстовое поле
      - значение по умолчанию: "Название 1"
  - **Элемент данных 2**
    - Название таймлайна (п.3 на Скрине 1)
      - название поля: "Название"
      - тип: текстовое поле
      - значение по умолчанию: "Название 2"
    - Ячейка (можно удалить/поменять местами, если кол-во ячеек >1) (п.3.1 на Скрине 1)
      - Текст в ячейке
        - название поля: "Текст"
        - тип: текстовое поле
        - значение по умолчанию: "Ячейка 2-1"
      - Цвет ячейки
        - название поля: "Цвет"
        - тип: дропдаун
        - возможные значения:
          - Оранжевый
          - Светло-зеленый
          - Зеленый
          - Тёмно-зеленый
        - значение по умолчанию: "Тёмно-зеленый"
      - Высота ячейки
        - название поля: "Высота"
        - тип: дропдаун
        - возможные значения:
          - XS (=40px)
          - S (=68px)
          - M (=102px)
          - L (=136px)
          - XL (=204px)
        - значение по умолчанию: "S"
      - Добавить новую ячейку
        - название кнопки: "Добавить ячейку"
        - тип: кнопка
        - при клике добавляется подраздел "Ячейка" с пустыми полями
        - новая ячейка в блоке добавляется сверху
  - **Элемент данных 3**
    - Название таймлайна (п.4 на Скрине 1)
      - название поля: "Название"
      - тип: текстовое поле
      - значение по умолчанию: "Название 3"
    - Ячейка (можно удалить/поменять местами, если кол-во ячеек >1) (п.4.1 на Скрине 1)
      - Текст в ячейке
        - название поля: "Текст"
        - тип: текстовое поле
        - значение по умолчанию: "Ячейка 3-1"
      - Цвет ячейки
        - название поля: "Цвет"
        - тип: дропдаун
        - возможные значения:
          - Оранжевый
          - Светло-зеленый
          - Зеленый
          - Тёмно-зеленый
        - значение по умолчанию: "Тёмно-зеленый"
      - Высота ячейки
        - название поля: "Высота"
        - тип: дропдаун
        - возможные значения:
          - XS (=40px)
          - S (=68px)
          - M (=102px)
          - L (=136px)
          - XL (=204px)
        - значение по умолчанию: "S"
      - Добавить новую ячейку
        - название кнопки: "Добавить ячейку"
        - тип: кнопка
        - при клике добавляется подраздел "Ячейка" с пустыми полями
        - новая ячейка в блоке добавляется сверху
  - **Элемент данных 4**
    - Название таймлайна (п.5 на Скрине 1)
      - название поля: "Название"
      - тип: текстовое поле
      - значение по умолчанию: "Название 4"
    - Ячейка (можно удалить/поменять местами, если кол-во ячеек >1) (п.5.1 на Скрине 1)
      - Текст в ячейке
        - название поля: "Текст"
        - тип: текстовое поле
        - значение по умолчанию: "Ячейка 4-1"
      - Цвет ячейки
        - название поля: "Цвет"
        - тип: дропдаун
        - возможные значения:
          - Оранжевый
          - Светло-зеленый
          - Зеленый
          - Тёмно-зеленый
        - значение по умолчанию: "Тёмно-зеленый"
      - Высота ячейки
        - название поля: "Высота"
        - тип: дропдаун
        - возможные значения:
          - XS (=40px)
          - S (=68px)
          - M (=102px)
          - L (=136px)
          - XL (=204px)
        - значение по умолчанию: "L"
      - Добавить новую ячейку
        - название кнопки: "Добавить ячейку"
        - тип: кнопка
        - при клике добавляется подраздел "Ячейка" с пустыми полями
        - новая ячейка в блоке добавляется сверху
  - **Элемент данных 5**
    - Название таймлайна (п.6 на Скрине 1)
      - название поля: "Название"
      - тип: текстовое поле
      - значение по умолчанию: "Название 5"
    - Ячейка (можно удалить/поменять местами, если кол-во ячеек >1) (п.6.1 на Скрине 1)
      - Текст в ячейке
        - название поля: "Текст"
        - тип: текстовое поле
        - значение по умолчанию: "Ячейка 5-1"
      - Цвет ячейки
        - название поля: "Цвет"
        - тип: дропдаун
        - возможные значения:
          - Оранжевый
          - Светло-зеленый
          - Зеленый
          - Тёмно-зеленый
        - значение по умолчанию: "Тёмно-зеленый"
      - Высота ячейки
        - название поля: "Высота"
        - тип: дропдаун
        - возможные значения:
          - XS (=40px)
          - S (=68px)
          - M (=102px)
          - L (=136px)
          - XL (=204px)
        - значение по умолчанию: "XL"
      - Добавить новую ячейку
        - название кнопки: "Добавить ячейку"
        - тип: кнопка
        - при клике добавляется подраздел "Ячейка" с пустыми полями
        - новая ячейка в блоке добавляется сверху

- Стили
  - Ширина (колонок) = 12 колонкам и ее нельзя изменить

Скрин 1. Вид блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=14783%3A198685))
![Image](https://user-images.githubusercontent.com/112703510/200325136-57d8b782-77ea-4565-83a7-6d290ab376eb.png)

Скрин 2. Настройки нового блока
![Image](https://user-images.githubusercontent.com/112703510/200332984-d6636688-52b7-4791-aa4f-c29712010b21.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
