### ISSUE TITLE
[Uni Blocks] Новый блок с контактами

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#796]
Необходимо реализовать новый блок с контактами как на Скрине 1 ниже.

В настройках блока необходимо добавить следующие поля:
- ДАННЫЕ
  - **Плитка 1**
    - Заголовок (п.1.1 на Скрине 1)
      - тип: текстовое поле
      - значение по умолчанию: "Заголовок 1"
    - Описание (п.1.2 на Скрине 1)
      - тип: текстовое поле
      - значение по умолчанию: "Описание 1"
    - Кнопка (п.1.3 на Скрине 1)
      - Текст
        - тип: текстовое поле
        - значение по умолчанию: "Кнопка 1"
      - URL
        - тип: текстовое поле
        - значение по умолчанию: null
      - Таргет
        - тип: дропдаун
        - значение по умолчанию: null
      - Цвет кнопки
        - тип: дропдаун
        - значение по умолчанию: "Второстепенный"
      - Закругленные углы
        - тип: чекбокс
        - значение по умолчанию: false
  - **Плитка 2**
    - Заголовок (п.2.1 на Скрине 1)
      - текстовое поле
      - значение по умолчанию: "Заголовок 2"
    - Описание (п.2.2 на Скрине 1)
      - тип: текстовое поле
      - значение по умолчанию: "Описание 2"
    - Кнопка (п.2.3 на Скрине 1)
      - Текст
        - тип: текстовое поле
        - значение по умолчанию: "Кнопка 2"
      - URL
        - тип: текстовое поле
        - значение по умолчанию: null
      - Таргет
        - тип: дропдаун
        - значение по умолчанию: null
      - Цвет кнопки
        - тип: дропдаун
        - значение по умолчанию: "Второстепенный"
      - Закругленные углы
        - тип: чекбокс
        - значение по умолчанию: false  
- КОНТАКТЫ
  - **Плитка 3**
    - Элемент плитки 1
      - Заголовок (п.3.1 на Скрине 1)
        - текстовое поле
        - значение по умолчанию: "Заголовок 3"
      - Описание (п.3.2 на Скрине 1)
        - текстовое поле
        - значение по умолчанию: "Описание 3"
    - Элемент плитки 2
      - Заголовок (п.4.1 на Скрине 1)
        - текстовое поле
        - значение по умолчанию: "Заголовок 4"
      - Описание (п.4.2 на Скрине 1)
        - текстовое поле
        - значение по умолчанию: "Описание 4"
  - **Плитка 4**
    - Элемент плитки 1
      - Заголовок (п.5.1 на Скрине 1)
        - текстовое поле
        - значение по умолчанию: "Заголовок 5"
      - Описание (п.5.2 на Скрине 1)
        - текстовое поле
        - значение по умолчанию: "Описание 5"
    - Элемент плитки 2
      - Заголовок (п.6.1 на Скрине 1)
        - текстовое поле
        - значение по умолчанию: "Заголовок 6"
      - Описание (п.6.2 на Скрине 1)
        - текстовое поле
        - значение по умолчанию: "Описание 6" 
- СТИЛИ
  - Ширина (колонок)
    - ширина = 12 колонкам и изменить ее нельзя
  - Цвет блока
    - тип: дропдаун
    - значение по умолчанию: "Второстепенный"

Скрин 1. Вид блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=14783%3A178755))
![Image](https://user-images.githubusercontent.com/112703510/200526333-226ec461-8742-42eb-83fa-4411c932feef.png)

Скрин 2. Настройки нового блока
![Image](https://user-images.githubusercontent.com/112703510/200541742-fd4048e4-cf1a-4259-8930-4c20cb1fedb9.png)
![Image](https://user-images.githubusercontent.com/112703510/200541769-15625030-637d-4b84-b057-33bbeb8fe234.png)

**Comment by klapada** [comment]
Необходимо в настройках блока добавить еще одно поле "Дополнительное описание" в пп. 3.2, 4.2, 5.2, 6.2 (место показано на Скрине ниже):
- название поля "Дополнительное описание"
- тип: текстовое поле
- значение по умолчанию: "Доп описание"

<img width="297" alt="Screenshot 2022-11-21 at 12 02 42" src="https://user-images.githubusercontent.com/112703510/203010009-ba858474-c58d-460e-a6df-98f951c8a427.png">

**Comment by tatinacher** [comment]
Заголовок взят наиболее подходящий из uikit - h5 (отличается line-height)

**Comment by tatinacher** [comment]
В блоке нужно поправить версию Цвета блока - добавить основную версию

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
