### ISSUE TITLE
[Uni Blocks] Доработка блока Рекомендации (Recommendation)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#800]
Необходимо доработать блок Recommendation, а именно:
- Добавить новое поле для изменения цвета всех карточек:
  - название поля: "Цвет карточек"
  - тип: дропдаун
  - возможные значения:
    - Основной
    - Второстепенный
  - значение по умолчанию: "Основной"
  - цвет применяется сразу ко всем карточкам в блоке (Скрин 1)
- Добавить у кнопок для соц. сетей новое поле для изменения фона:
  - название поля: "Цвет фона"
  - тип: дропдаун
  - возможные значения:
    - Белый
    - Серый
  - значение по умолчанию: "Белый"
  - цвет применяется сразу ко всем кнопкам соц. сетей в блоке (Скрин 2)

Скрин 1. Изменен цвет карточек ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=15751%3A103735&t=YkN5JRKlfIZLiOgo-4))
![Image](https://user-images.githubusercontent.com/112703510/201668988-e0acfa62-8326-4f79-8526-43d8064847a5.png)

Скрин 2. Серые кнопки ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16132%3A127413&t=YkN5JRKlfIZLiOgo-4))
![Image](https://user-images.githubusercontent.com/112703510/201669044-ea0e62cd-4c56-4fb6-9935-157f069e0b30.png)

**Comment by klapada** [comment]
После обсуждения договорились внести следующие изменения:
Вместо поля "Цвет фона" в карточке нужно добавить подраздел "Кнопка" с возможностью добавления кнопки в карточке (вид кнопки в блоке как на Скрине 2):
- Добавить кнопку
  - тип: кнопка
  - при клике добавляются следующие поля:
    - URL
      - тип: текстовое поле
      - значение по умолчанию: null
    - Таргет
      - тип: дропдаун
      - значение по умолчанию: null
    - Цвет кнопки
      - тип: дропдаун
      - значение по умолчанию: "Основной"
    - Иконка

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
