### ISSUE TITLE
[Uni Blocks] Новый блок Список ссылок

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#810]
Необходимо реализовать новый блок для списка ссылок (Скрин 1).

В панели настроек блока нужно добавить следующие поля (Скрин 2):
- Заголовок
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок"
- Ссылка
  - Текст
    - тип: текстовое поле
    - значение по умолчанию: "Текст 1"
  - URL
    - тип: текстовое поле
    - значение по умолчанию: null
  - Таргет
    - тип: дропдаун
    - значение по умолчанию: null
  - Количество значений
    - тип: числовое поле
    - значение по умолчанию: null
    - если поле заполнено, то рядом с названием ссылки в скобках указывается данное значение (как на Скрине 1)
    - если поле не заполнено, то отображается только название ссылки
- Добавить ссылку
  - тип: кнопка
  - при клике добавляются поля для новой ссылки
  - мин. кол-во ссылок = 1
  - макс. кол-во = нет ограничений
- Стили (стандартный список полей)

Скрин 1. Вид блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7847%3A200170))
![Image](https://user-images.githubusercontent.com/112703510/196133282-a2314d4a-abf9-45b7-83e3-e9d551ff646c.png)

Скрин 2. Настройки нового блока
![Image](https://user-images.githubusercontent.com/112703510/196143028-01f2374e-a9e9-4a4b-90da-ce9fd77e156f.png)

**Comment by Mikage777** [comment]
Закрываю задачу в связи с ее неактуальностью. Задача в блоке предназначалась для страниц-филиалов (их карточек) которые планировалось генерить на уровне портала. В связи с недостаточностью данных из сервиса справочника, такие страницы сгенерировать невозможно.
