### ISSUE TITLE
[Uni Blocks] Новый блок с реквизитами офиса

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#811]
Необходимо реализовать новый блок с реквизитами офиса (Скрин ниже).

В настройках блока добавить следующие поля:
- Офис (возможность выбора офиса для подтягивания по нему данных)
- Реквизиты для валютных переводов
  - Текст
    - тип: текстовое поле
    - значение по умолчанию: "Реквизиты для валютных переводов"
  - URL
    - тип: текстовое поле
    - значение по умолчанию: null
  - Таргет
    - тип: дропдаун
    - значение по умолчанию: null
- Скачать реквизиты
  - URL
    - тип: текстовое поле
    - значение по умолчанию: null
- Печать
  - URL
    - тип: текстовое поле
    - значение по умолчанию: null

Логика работы блока:
- № корсубсчета
  - данные из справочника = "corAcc"
  - если значения в справочнике нет, то строка в блоке не отображается
- ИНН
  - данные из справочника = "inn"
  - если значения в справочнике нет, то строка в блоке не отображается
- КПП
  - данные из справочника = "kpp"
  - если значения в справочнике нет, то строка в блоке не отображается
- БИК
  - данные из справочника = "bik"
  - если значения в справочнике нет, то строка в блоке не отображается
- КГР КО
  - данные из справочника = "???"
  - если значения в справочнике нет, то строка в блоке не отображается
- Реквизиты для валютных переводов
  - при клике открытие страницы, указанной в настройках блока в поле "URL" в подразделе настроек "Реквизиты для валютных переводов"
  - если поле с URL пустое, то в блоке строка не отображается
- Скачать реквизиты
  - при клике начинается загрузка файла, который находится по ссылке, указанной в настройках блока
  - если ссылки нет, то кнопка не отображается
- Печать
  - при клике открывается форма для печати того файла, который находится по ссылке, указанной в настройках
  - если ссылки нет, то кнопка не отображается

Скрин. Вид нового блока ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=7847%3A200170))
![Image](https://user-images.githubusercontent.com/112703510/195824877-c708d024-f353-4fa1-b7ed-d7351fc222b0.png)

**Comment by Mikage777** [comment]
Закрываю задачу в связи с ее неактуальностью. Задача в блоке предназначалась для страниц-филиалов (их карточек) которые планировалось генерить на уровне портала. В связи с недостаточностью данных из сервиса справочника, такие страницы сгенерировать невозможно.
