### ISSUE TITLE
[Uni Blocks] Новый блок Галерея для инвестиций

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#813]
Необходимо реализовать новый блок Галерею с возможностью выводить список в один столбец или два.

В настройках блока должны быть следующие поля (Скрин 3):
- Заголовок блока (п.1 на Скрине 1)
  - название поля: "Заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок блока"
- Заголовок карточки (п.2 на Скрине 1)
  - название поля: "Заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок карточки"
- Описание карточки (п.3 на Скрине 2)
  - название поля: "Описание"
  - тип: текстовое поле
  - значение по умолчанию: "Описание"
- Доп. описание карточки (п.4 на Скрине 1)
  - название поля: "Дополнительное описание"
  - тип: текстовое поле
  - значение по умолчанию: "Описание 1-2"
- Количество колонок в списке
  - название поля: "Количество колонок"
  - тип: дропдаун
  - возможные значения:
    - 1 колонка
    - 2 колонки
  - значение по умолчанию: "1 колонка"
  - вид списка в блоке при выборе варианта "1 колонка" показан на Скрине 1 (размер текста **Параметра** = 20px)
  - вид списка в блоке при выборе варианта "2 колонки" показан на Скрине 2 (размер текста **Параметра** = 16px)
- Параметр списка (п.5 на Скрине 1)
  - название поля: "Параметр"
  - тип: текстово поле
  - значение по умолчанию: "Параметр"
- Описание пункта (п.6 на Скрине 1)
  - название поля: "Описание"
  - тип: текстово поле
  - значение по умолчанию: "Описание пункта"
- Добавление изображения/иконки (п.7 на Скрине 1)
  - возможность добавить/удалить изображение или иконку из списка
- Добавить пункт
  - тип: кнопка
  - при клике добавляется пункт списка с пустыми полями "Параметр" и "Описание"
  - если в поле **Количество колонок** выбрано значение = "1 колонка", то добавить можно макс 5 пунктов списка
  - если в поле **Количество колонок** выбрано значение = "2 колонки", то добавить можно макс 10 пунктов списка
- Добавить карточку
  - тип: кнопка
  - при клике добавляется новая карточка с полями

Скрин 1. Вид блока со списком в 1 столбец ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=14783%3A177414&t=nw03N52ziofWNDMt-4))
![Image](https://user-images.githubusercontent.com/112703510/202142924-e4e598ef-e99c-45a3-bacc-5201f9ee41cb.png)

Скрин 2. Вид блока со списком в 2 столбца ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=14783%3A175954&t=nw03N52ziofWNDMt-4))
![Image](https://user-images.githubusercontent.com/112703510/202143008-6df93b08-9a79-4364-827c-ca3cdac89a59.png)

Скрин 3. Настройки блока
![Image](https://user-images.githubusercontent.com/112703510/202143577-eb99e1d3-a05a-4563-ae8f-d83f6fa93885.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
