### ISSUE TITLE
[Uni Blocks] Доработка блока Преимущества кредита (BonusBenefitsBlock)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#815]
Необходимо в настройках блока BonusBenefitsBlock в подразделе "Список бонусов" добавить новое поле:
- Выбор кол-ва элементов в строке
  - название поля: "Количество элементов в строке"
  - тип: дропдаун
  - возможные значения:
    - 4
    - 5
  - значение по умолчанию: 4
  - при выборе значения = 5 элементы располагаются как на Скрине ниже

Скрин. Вид блока с 5ю элементами в строке ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=14783%3A169811&t=nw03N52ziofWNDMt-4))
![Image](https://user-images.githubusercontent.com/112703510/202153524-3cd9bf14-5f52-47f4-945f-e743d2e10c54.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
