### ISSUE TITLE
[Uni Blocks] Новый блок с плитками и кнопкой

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#821]
Необходимо реализовать новый блок согласно Скрину 1 ниже.

В настройках блока добавить следующие поля:
- **Заголовок блока**
  - название поля: "Заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок блока"
- **Добавить кнопку**
  - тип: кнопка
  - при клике добавляются следующие поля:
    - Текст
      - тип: текстовое поле
      - значение по умолчанию: "Кнопка"
    - URL
      - тип: текстовое поле
      - значение по умолчанию: null
    - Таргет
      - тип: дропдаун
      - значение по умолчанию: null
    - Цвет кнопки
      - тип: дропдаун
      - значение по умолчанию: "Основной"
  - добавить можно только одну кнопку
  - кнопку можно удалить
- **Описание плитки**
  - название поля: "Описание"
  - тип: текстовое поле
  - значение по умолчанию: "Описание"
- **Изображение в плитке**
  - добавление/удаление изображения или иконки из списка
- **Добавить плитку**
  - тип: кнопка
  - при клике добавляются пустые поля **Описание плитки** и **Изображение для плитки** для создания еще одной плитки
  - можно добавить мин. 1, а макс. 3 плитки

_Скрин 1. Плитки и кнопка_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=15743%3A88568&t=OA2FDA5GUsuVfjgs-4))
![Image](https://user-images.githubusercontent.com/112703510/201921598-af672af5-51e4-4c38-9442-9db93410d806.png)

_Скрин 2. Плитки без кнопки_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16466%3A105391&t=OA2FDA5GUsuVfjgs-4))
![Image](https://user-images.githubusercontent.com/112703510/201921629-2e889370-a7c1-4150-a317-996e53da9e4a.png)

_Скрин 3. Настройки нового блока_
![Image](https://user-images.githubusercontent.com/112703510/202198295-5ba055ab-fac6-466c-9927-4783ffbd2290.png)

**Comment by Longraf** [comment]
У нас уже есть схожий компонент Галерея, соответственно из требований нужно убрать ограничение `макс. 3 плитки`
С Эльдаром согласовал изменения Галереи и нового блока что бы привести их к одному виду
Ширину плиток берём от галереи 364px
Шрифты Галереи меняем на вариант из нового макете (Размер шрифта заголовка тH3 по ui-kit) (Размер шрифта в карточке H6 по ui-kit)

**Comment by SergeyPilipenko** [comment]
проверео в ип2.0
