### ISSUE TITLE
[Uni Blocks] Доработка блока Моб приложение (MobileAppTile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#823]
Необходимо доработать блок MobileAppTile, а именно в настройках блока сделать следующее:
1. Добавить новые поля (Скрин 2):
    - **Выравнивание заголовка**
      - тип: дропдаун
      - возможные значения:
        - По левому краю
        - По центру
        - По правому краю
      - значение по умолчанию: "По левому краю"
    - **Описание**
      - тип: текстовое поле
      - значение по умолчанию: "Описание"

2. Переименовать поле "Описание", которое отображается только в моб. версии, в "Описание (моб.)"

_Скрин 1. Вид блока_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16640%3A115683&t=OA2FDA5GUsuVfjgs-4))
![Image](https://user-images.githubusercontent.com/112703510/202457311-7876aed5-d0cf-4990-a010-72b82e5b389b.png)

_Скрин 2. Настройки блока_
![Image](https://user-images.githubusercontent.com/112703510/202456907-08230946-cd88-4cc4-8ea6-c31e34cf4a77.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
