### ISSUE TITLE
[Uni Blocks] Новый блок Табы с вложенным др блоком

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#829]
Необходимо реализовать новый блок Табы, в котором для каждого таба можно выбрать блок (Скрины 1-5).

В настройках блока нужны следующие поля (Скрин 6):
- **Заголовок блока**
  - название поля: "Заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок блока"
- **Название вкладки**
  - название поля: "Название"
  - значение по умолчанию: "Вкладка 1"
- **Выбор вложенного блока**
  - название поля: "Блок"
  - тип: дропдаун
  - возможные значения: названия всех имеющихся блоков в конструкторе
  - значение по умолчанию: null
  - плейсхолдер: "Выберите блок"
  - при выборе конкретного блока появляются поля для его настройки
  - добавить можно только один блок
- **Добавить вкладку**
  - тип: кнопка
  - при клике добавляются пустые поля для **Названия вкладки** и **Выбора вложенного блока**
- **Удалить вкладку**
  - вкладку можно удалить, если их кол-во > 1
- **Переместить вкладку вверх/вниз**
  - вкладку можно перемещать, если их кол-во > 1

_Скрин 1. Вид блока с вложенной плиткой_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16640%3A115683&t=OA2FDA5GUsuVfjgs-4))
![Image](https://user-images.githubusercontent.com/112703510/202477248-50617783-4839-4719-bf42-63f0810b6607.png)

_Скрин 2. Вид блока с вложенной мини-галереей_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=15751%3A103735&t=OA2FDA5GUsuVfjgs-4))
![Image](https://user-images.githubusercontent.com/112703510/202477278-88cd8787-9884-41d8-8045-8c34654e3560.png)

_Скрин 3. Вид блока с вложенными шагами_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16289%3A104358&t=OA2FDA5GUsuVfjgs-4))
![Image](https://user-images.githubusercontent.com/112703510/202477344-161cd5dd-e0e7-436e-bd84-effe30359126.png)

_Скрин 4.  Вид блокам с вложенной формой обратной связи_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16432%3A106500&t=OA2FDA5GUsuVfjgs-4))
![Image](https://user-images.githubusercontent.com/112703510/202477362-87469fb9-bd02-4cf9-80f1-d7b4dae296be.png)

_Скрин 5. Вид блока со скроллом вкладок_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16640%3A118960&t=rYcWwY8DZdMeP0Px-4))
![Image](https://user-images.githubusercontent.com/112703510/203055160-2418bf21-0764-415d-9485-db60739b953b.png)

_Скрин 6. Настройки блока_
![Image](https://user-images.githubusercontent.com/112703510/202647779-f4bb5af4-1c49-4906-b3b6-3abc487358a0.png)

**Comment by Mikage777** [comment]
Задача частично покрывается другой задачей https://github.com/redneckz/wildless-cms-uni-blocks/issues/907 . После внедрения вертикального компоновщика, можно будет взять в работу над доработкой стилей и возмоностью прокрутки текущих табов

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
