### ISSUE TITLE
[Uni Blocks] Новый блок для вывода ссылок в виде карусели

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#856]
Необходимо реализовать новый блок для разводящей страницы "О Банке" согласно Скрину 1 ниже. 

Для настройки блока необходимы следующие поля (Скрин 2):
- Заголовок в блоке
  - название поля: "Заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок"
- Описание 1
  - тип: текстовое поле
  - значение по умолчанию: "Описание 1"
- Описание 2
  - тип: текстовое поле
  - значение по умолчанию: "Описание 2"
- Текст ссылки
  - название поля: "Текст"
  - тип: текстовое поле
  - значение по умолчанию: "Текст"
- URL
  - название поля: "URL"
  - тип: текстовое поле
  - значение по умолчанию: null
- Таргет
  - название поля: "Таргет"
  - тип: дропдаун
  - значение по умолчанию: null
- Добавить ссылку
  - тип: кнопка
  - при клике добавляются пустые поля Текст, URL и Таргет для новой ссылки
  - ссылку можно удалить/поменять местами, если их кол-во > 1
- Стили
  - ширину блока нельзя сделать < 12 колонок

_Скрин 1. Вид блока_ ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16750%3A180900&t=yRPXsVv2egMZMkWf-4))
![Image](https://user-images.githubusercontent.com/112703510/203432947-26af0db4-9035-4e55-adf0-52d2b52958b3.png)

_Скрин 2. Настройки блока_
![Image](https://user-images.githubusercontent.com/112703510/203432968-b01624a5-2826-4930-8d5a-8844358102fa.png)

**Comment by Longraf** [comment]
Считаю не верным называть компонент по Заголовку отдельной страницы. это скорее "Описание + Карусель " У меня нет нормального названия , но "О банке" вообще ничего не говорит о компоненте, а только о конкретной странице

**Comment by tatinacher** [comment]
Договорились с дизайнерами, что заголовок "О банке" будет 50px

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
