### ISSUE TITLE
[Uni Blocks] Новый блок с каруселью для страницы "О Банке"

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#859]
Необходимо реализовать еще один вариант карусели как на Скрине 1 ниже.

Для настройки блока нужны следующие поля (Скрин 2):
- Заголовок блока
  - название поля: "Заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок блока"
- Описание блока
  - название поля: "Описание"
  - тип: текстовое поле
  - значение по умолчанию: "Описание блока"
- Карточка 1
  - Заголовок
    - тип: текстовое поле
    - значение по умолчанию: "Заголовок 1"
  - Описание
    - тип: текстовое поле
    - значение по умолчанию: "Описание 1"
- Карточка 2
  - Заголовок
    - тип: текстовое поле
    - значение по умолчанию: "Заголовок 2"
  - Описание
    - тип: текстовое поле
    - значение по умолчанию: "Описание 2"
- Карточка 3
  - Заголовок
    - тип: текстовое поле
    - значение по умолчанию: "Заголовок 3"
  - Описание
    - тип: текстовое поле
    - значение по умолчанию: "Описание 3"
- Добавить карточку
  - тип: кнопка
  - при клике добавляется еще один подраздел "Карточка" с пустыми полями Заголовок и Описание
  - карточку можно удалить/поменять местами, если их кол-во > 1
- Стили
  - ширину блока нельзя сделать < 12 колонок

Логика работы карусели в блоке:
- при клике на "стрелку" вправо (или влево) центральная карточка смещается вправо (или влево), при этом у боковых карточек выводится только значение из Заголовка карточкки, а у центральной - как Заголовок, так и Описание карточки

_Скрин 1. Вид блока_ ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16750%3A180900&t=QQmNm1EIavivf5El-4))
![Image](https://user-images.githubusercontent.com/112703510/203563190-e61f7186-0e87-47f8-9556-55ce6280afb2.png)

_Скрин 2. Настройки блока_
![Image](https://user-images.githubusercontent.com/112703510/203563267-62348a42-1db2-48fd-8932-19dbf5c43c6b.png)

**Comment by lis42000** [comment]
Расхождения макета с компонентом (отступы, ширина/высота) согласованы с дизайнером.

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
