### ISSUE TITLE
[Uni Blocks] Новый блок с преимуществами Банка

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#861]
Необходимо реализовать новый блок с преимуществами Банка как на Скрине 1-2 ниже.

Для настройки блока нужны следующие поля (Скрин 3):
- Верхний заголовок в карточке
  - название поля: "Верхний заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок 1"
- Нижний заголовок в карточке
  - название поля: "Нижний заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок 2"
- Добавить изображение/иконку
  - можно загрузить свою картинку или выбрать иконку из списка
- Добавить карточку
  - тип: кнопка
  - при клике добавляется новая карточка с полями Верхний заголовок (значение по умолчанию "Заголовок"), Нижний заголовок (значение по умолчанию "Заголовок") и Изображение
  - можно удалить/поменять местами карточки, если их кол-во > 1
  - можно добавить макс 4 карточки, мин 1
- Стили
  - мин ширина = 3 колонкам

_Скрин 1. Вид блока с заголовком над и под картинкой_ ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=16750%3A180900&t=5H4Xr8dXIwhis9YS-4))
![Image](https://user-images.githubusercontent.com/112703510/203728300-99685b8c-7e31-473c-839e-3c7775123f23.png)

_Скрин 2. Вид блока с заголовком только под картинкой_
![Image](https://user-images.githubusercontent.com/112703510/203728360-804dd037-196c-4b5c-8106-b5946cc0c63a.png)

_Скрин 3. Настройки блока_
![Image](https://user-images.githubusercontent.com/112703510/203733182-7c7f81d4-8fe0-405b-94d5-90cb78351789.png)

**Comment by tatinacher** [comment]
Блок реализован через доработку BonusBenefitsBlock

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
