### ISSUE TITLE
[Uni Blocks] Новый блок с картинкой и текстом

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#865]
Необходимо реализовать новый блок с картинкой и текстом как на Скрине 1 ниже.

Для настройки блока нужны следующие поля (Скрин 2):
- Пункт 1 (пункт можно удалить, если их кол-во > 1)
  - Заголовок
    - тип: текстовое поле
    - значение по умолчанию: "Заголовок 1"
  - Описание
    - тип: текстовое поле
    - значение по умолчанию: "Описание 1"
- Пункт 2 (пункт можно удалить, если их кол-во > 1)
  - Заголовок
    - тип: текстовое поле
    - значение по умолчанию: "Заголовок 2"
  - Описание
    - тип: текстовое поле
    - значение по умолчанию: "Описание 2"
- Добавление изображения/иконки
  - можно загрузить свою картинку или выбрать иконку из списка

_Скрин 1. Вид блока_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16376%3A105348&t=Ca6MjnfEDYkxBZEW-4))
![Image](https://user-images.githubusercontent.com/112703510/203792331-652790ba-0b68-4a86-9eb7-807396067d47.png)

_Скрин 2. Настройки блока_
![Image](https://user-images.githubusercontent.com/112703510/203792353-37750f51-bf48-4d22-9a70-b6e0d2771d7e.png)

**Comment by Longraf** [comment]
Нужно изучать, но очень похоже на PictureText. Возможно получиться не вводить новый компонент

**Comment by Longraf** [comment]
![image](https://user-images.githubusercontent.com/32570545/203821730-f106701e-a84e-484d-ad31-71c1a8b3c5d9.png)

**Comment by Longraf** [comment]
В PictureText вместо преимуществ можно выводить компонент Headline это пункт 1.1. и 1.2 

Так же появились новые требования по анимации. При скроле картинка должна останавливаться , а скролиться Headline(Загловокп1.1 и описание п.1.2 ) их на странице несколько . Задача требует проработки технического решения данного функционала

**Comment by Mikage777** [comment]
Задача на холде, до дальнейшего распоряжения. Представленные требования к анимации, нарушают пользовательский экспириенс. Необходимо переосмысление логики анимации.

**Comment by klapada** [comment]
Анимацию пока отложили, поэтому делаем, как описано в требованиях.

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
