### ISSUE TITLE
[Uni Blocks] Новый блок Тарифная галерея

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#873]
Необходимо реализовать новый блок согласно Скрину 1 ниже.

Для настройки блока нужны следующие поля:
- **Заголовок блока**
  - название поля: "Заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок блока"
- **Карточка** (можно удалить/поменять местами, если их кол-во > 1)
  - **Выделение карточки**
    - название поля: "Выделить карточку"
    - тип: чекбокс
    - возможные значения:
      - true (= карточка выделена как на Скрине 2 п.2)
      - false (= карточка не выделена)
    - значение по умолчанию: false
  - **Заголовок карточки**
    - название поля: "Заголовок"
    - тип: текстовое поле
    - значение по умолчанию: "Заголовок карточки"
  - **Добавление изображения/иконки**
    - можно загрузить свою картинку или выбрать иконку из списка
  - **Кнопка**
    - **Добавить кнопку**
      - тип: кнопка
      - при клике добавляются следующие поля:
        - **Текст**
          - тип: текстовое поле
          - значение по умолчанию: "Кнопка"
        - **URL**
          - тип: текстовое поле
          - значение по умолчанию: null
        - **Таргет**
          - тип: дропдаун
          - значение по умолчанию: null
        - **Цвет кнопки**
          - тип: дропдаун
          - значение по умолчанию: "Второстепенный"
      - добавить можно только одну кнопку
      - кнопку можно удалить
  - **Ячейка** (можно удалить/поменять местами, если их кол-во > 1)
    - **Название**
      - тип: текстовое поле
      - значение по умолчанию: "Ячейка"
    - **Описание**
      - тип: текстовое поле
      - значение по умолчанию: "Описание для ячейки"
    - **Добавить ячейку**
      - тип: кнопка
      - при клике добавляются поля **Название** и **Описание** для новой ячейки
  - **Добавить карточку**
    - тип: кнопка
    - при клике добавляются поля для новой карточки (список полей описан выше в разделе "Карточка")
- **Стили**
  - ширину блока нельзя установить < 12 колонок

_Скрин 1. Вид блока со свернутыми данными_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=17078%3A113674&t=PwTbdyn8jiJrNBeK-4))
![Image](https://user-images.githubusercontent.com/112703510/203965075-3a623b50-3aed-4245-822c-07ec488ba2e8.png)

_Скрин 2. Вид блока с развернутыми данными_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16640%3A115683&t=PwTbdyn8jiJrNBeK-4))
![Image](https://user-images.githubusercontent.com/112703510/203991379-fb86ce50-e61a-4e0c-a866-3b9cb3c781fd.png)

_Скрин 3. Настройки блока_
![Image](https://user-images.githubusercontent.com/112703510/203999176-cfd09dc1-0bc7-4639-8c13-9bae68adeabc.png)

**Comment by SergeyPilipenko** [comment]
Проверено в ип2.0
