### ISSUE TITLE
[Uni Blocks] Возможность в Плитке добавлять теги (Tile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#879]
Необходимо в настройках блока Tile добавить новые поля для создания тегов (Скрин 1-2):
- Теги
  - Текст тега
    - тип: текстовое поле
    - значение по умолчанию: "Тег"
    - ограничение на макс кол-во символов в поле = 40
  - Добавить тег
    - тип: кнопка
    - при клике добавляется пустое текстовое поле для нового тега

_Скрин 1. Вид блока с тегами_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/RSHB_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D1%81%D0%B0%D0%B9%D1%82-(%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC)?node-id=16863%3A104880&t=H6IftWT7Php5sllD-4))
![Image](https://user-images.githubusercontent.com/112703510/204295152-dff4c263-0c8f-49d3-8e5b-8181e49437be.png)

![Image](https://user-images.githubusercontent.com/112703510/204246178-1b699f59-ab34-4ce2-9657-8cedc662cce2.png)

_Скрин 2. Настройки блока_
![Image](https://user-images.githubusercontent.com/112703510/204293866-80391e5d-f8d1-4b9b-9c4a-7e2812a8c442.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
