### ISSUE TITLE
[Uni Blocks] Изменение формулировки текста в блоке Курсы валют (ExchangeRateTile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#894]
Изменить текст в блоке 
с "Курс указан для ближайшего офиса ({расстояние в км от пользователя до офиса} км)" 
на "Курс указан для заданного офиса"

![Image](https://user-images.githubusercontent.com/112703510/204758203-41e3fde5-5618-49ee-a71d-6a87e41c92a0.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
