### ISSUE TITLE
[UniBlocks + КР] Перенести из контента блока подвала пропсы в справочник

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#898]
Необходимо весь контент из подвала вынести в отдельный самостоятельный справочник. 
Основное и дополнительное меню - убрать.

**Comment by SergeyPilipenko** [comment]
Сейчас в ИП2.0 в справочнике Подвала присутствуют параметры Основное меню, Дополнительное меню, их быть не должно



![Image](https://user-images.githubusercontent.com/22083206/208785321-dabf7668-04ae-4dcd-9c8c-3691552c1d70.png)

**Comment by SergeyPilipenko** [comment]
2.3.52-beta проверено в даталайне
