### ISSUE TITLE
[UniBlocks + КР] Внедрение возможности ввода форматирования текста

### ISSUE THREAD

**Issue by Mikage777** [redneckz/wildless-cms-uni-blocks#909]
Необходимо подключить возможность ввода форматированного текста к свойствам этих двух блоков, путем добавления префикса `__md` к именованию свойств. Также добавить ui:schema виджеты к этим полям - `md`
 
Также требуется написать миграцию для "боевого" контента

В итоге должна получиться возможность вводить подобный форматированный ввод текста в эти блоки:

![Image](https://user-images.githubusercontent.com/5903264/205063125-bfe25978-3742-4c4e-9299-5524e6772bf5.jpg)

![Image](https://user-images.githubusercontent.com/5903264/205063145-b5d4ee88-3b58-45b5-ad1d-bdb5daf497fd.jpg)

**Comment by klapada** [comment]
### 1. Доработка блока Продуктовая плитка (ProductTile)

Необходимо в настройках блока для поля "Описание" под заголовком добавить возможность форматирования текста для возможности ввести контент как на Скрине ниже

![Image](https://user-images.githubusercontent.com/112703510/205938624-66051ac9-df67-46e7-a703-57fa9c89f1f0.png)
_Скрин. Вид блока_ ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=14783%3A186890&t=vxDBkSc0JPuBd0CX-4))


### 2. Доработка блока Картинка с текстом (PictureText)

Необходимо в настройках блока добавить возможность форматирования текста для поля **Название** преимущества (поле показано на _Скрине 2_), например для создания гиперссылок как на _Скрине 1_.

![Image](https://user-images.githubusercontent.com/112703510/207360505-15804476-af5a-4b19-b64e-28d71a812e79.png)
*Скрин 1. Вид блока с гиперссылками [Макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=16750%3A183623&t=KbUby481g1jZqvRL-4)*

---

![Image](https://user-images.githubusercontent.com/112703510/207360981-4f76ed81-91e4-4ba7-a5d5-dd6e1ef8d181.png)
*Скрин 2. Поле "Название" преимущества*

### 3. Доработка блока Шаги (StepsBlock)

Необходимо в настройках блока добавить возможность форматирования текста в поле **Название шага** (поле выделено на *Скрине* ниже)

![Image](https://user-images.githubusercontent.com/112703510/207561236-6ddff92c-ced8-4e92-8224-dfe7d46644c4.png)
*Скрин. Поле Название шага*

### 4.  Доработка Плитки (Tile)

Необходимо в настройках блока добавить возможность форматирования текста в поле **Описание** (поле показано на _Скрине_ ниже)

![Image](https://user-images.githubusercontent.com/112703510/207576813-7ce0701d-3fee-449e-af15-53f375429371.png)
*Скрин. Поле **Описание***

### 5. Доработка Продуктового блока (ProductBlock)

Необходимо в настройках блока добавить новое поле с возможностью выбора контента - списка или текста с форматированием
- название поля: "Вид контента"
- компонент: дропдаун
- возможные значения:
  - Список
  - Текст
- значение по умолчанию: "Список"
- при выборе значения "Список" доступны поля (выделены на _Скрине 1_ ниже) для заполнения пунктов списка (при добавлении нового поля вид будет как на _Скрине 2_)
- при выборе значения "Текст" доступно поле с возможностью форматирования текста (в поле значение по умолчанию = "Текст" как показано на _Скрине 3_)


![Image](https://user-images.githubusercontent.com/112703510/207586181-a764ac91-2465-4351-870f-0f3282333999.png)
*Скрин 1. Поля для заполнения списка*

---

![Image](https://user-images.githubusercontent.com/112703510/207585009-d56df6ef-2bc4-4552-8405-dcbd8ceb2de5.png)
*Скрин 2. Новое поле в выбранным значением "Список"*

---

![Image](https://user-images.githubusercontent.com/112703510/207585071-8cd78fd2-dd74-4a62-b8d9-b785c7e80940.png)
*Скрин 3. Новое поле в выбранным значением "Текст"*

---

![Image](https://user-images.githubusercontent.com/112703510/207586841-4c39d6f3-1aa0-4d90-8233-a84afda1cd5b.png)

![Image](https://user-images.githubusercontent.com/112703510/207586864-9788fe6c-9cd7-4d63-b43b-2c3d3bf8959a.png)
*Скрин 4. Вид блока с текстом ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=16410%3A184128&t=AI2LQS52Uy7O3Lcu-4))*

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
