### ISSUE TITLE
[Uni Blocks] Новый блок Форма заявки

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#911]
Необходимо реализовать новый блок Форма заявки, для этого нужно:

### 1. Добавить в настройках нового блока следующие поля (Скрин 6)
- Вид заявки
  - тип: дропдаун
  - возможные значения:
    - Бизнес-карта
    - ВЭД
    - Депозит
    - Кредит
    - Эквайринг
  - значение по умолчанию: "Кредит"
- Кнопка
  - Текст
    - тип: текстовое поле
    - значение по умолчанию: "Кнопка"
  - Цвет кнопки
    - тип: дропдаун
    - значение по умолчанию: "Основной"
- Условия передачи данных
  - Текст
    - тип: текстовое поле
    - значение по умолчанию: "условиями передачи данных"
  - URL
    - тип: текстовое поле
    - значение по умолчанию: null
- Стили
  - ширина блока не может быть < 12 колонок

#### 2.1 При выборе в поле Вид заявки значения "Эквайринг" (Скрин 1):
- **Вид эквайринга**
  - тип: дропдаун
  - возможные значения:
    - Торговый эквайринг
    - Мобильный эквайринг
    - Интернет-эквайринг
    - QR-эквайринг (СБП)
    - Все виды эквайринга
  - значение по умолчанию: "Торговый эквайринг"
  - обязательное поле
- **Регион**
  - тип: дропдаун
  - возможные значения: все значения из справочника regions
  - значение по умолчанию: выбранное значение региона в шапке
  - обязательное поле
- **Наименование организации**
  - тип: текстовое поле
  - значение по умолчанию: null
  - обязательное поле
- **ИНН**
  - тип: текстовое поле
  - значение по умолчанию: null
  - при блюре осуществляется валидация значения на кол-во символов - 10 или 12 чисел для ООО или ИП и если значение содержит не 10 или 12 чисел, то отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Контактное лицо**
  - тип: текстовое поле
  - значение по умолчанию: null
  - если введен только 1 символ, то при блюре отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Телефон**
  - тип: числовое поле с маской моб телефона с уже указанным кодом "+7"
  - значение по умолчанию: null
  - если введено от 1 до 9 чисел, то при блюре отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Хочу купить онлайн кассу**
  - тип: радио
  - значение по умолчанию: выкл
- **Хочу купить POS-терминал**
  - тип: радио
  - значение по умолчанию: выкл
- **Отправка заявку**
  - тип: кнопка
  - логика работы описана в отдельной задаче
- **Условия передачи данных**
  - тип: кнопка
  - при клике на гиперссылку осуществляется скачивание файла по адресу, указанному в настройках блока

#### 2.2. При выборе в поле Вид заявки значения "Кредит" (Скрин 2)
- **Сумма кредита**
  - тип: слайдер
  - мин. значение: 50 000
  - макс. значение: 3 000 000
  - значение по умолчанию: 50 000
- **Срок кредита**
  - тип: слайдер
  - мин. значение: 12
  - макс. значение: 60
  - значение по умолчанию: 12
- **Наименование организации**
  - тип: текстовое поле
  - значение по умолчанию: null
  - необязательное поле
- **Годовая выручка**
  - тип: числовое поле
  - значение по умолчанию: null
  - обязательное поле
- **ИНН**
  - тип: текстовое поле
  - значение по умолчанию: null
  - при блюре осуществляется валидация значения на кол-во символов - 10 или 12 чисел для ООО или ИП и если значение содержит не 10 или 12 чисел, то отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Контактное лицо**
  - тип: текстовое поле
  - значение по умолчанию: null
  - если введен только 1 символ, то при блюре отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Телефон**
  - тип: числовое поле с маской ввода номера моб телефона с кодом +7
  - значение по умолчанию: null
  - если введено от 1 до 9 чисел, то при блюре отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Электронная почта**
  - тип: текстовое поле
  - значение по умолчанию: null
  - необязательное поле
- **Регион**
  - тип: дропдаун
  - возможные значения: значения из справочника regions
  - значение по умолчанию: выбранный регион в шапке
  - обязательное поле
- **Адрес**
  - тип: дропдаун
  - возможные значения: все адреса офисов в выбранном регионе
  - значения по умолчанию: null
  - обязательное поле
- **Отправка заявки**
  - тип: кнопка
  - логика работы описана в отдельной задаче
- **Условия передачи данных**
  - тип: кнопка
  - при клике на гиперссылку осуществляется скачивание файла по адресу, указанному в настройках блока

#### 2.3 При выборе в поле Вид заявки значения "Бизнес-карта" (Скрин 3)
- **Регион**
  - тип: дропдаун
  - возможные значения: список регионов из справочника regions
  - значение по умолчанию: выбранный регион в шапке
  - обязательное поле
- **Контактное лицо**
  - тип: текстовое поле
  - значение по умолчанию: null
  - если введен только 1 символ, то при блюре отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Телефон**
  - тип: числовое поле с маской ввода номера моб телефона с кодом +7
  - значение по умолчанию: null
  - если введено от 1 до 9 чисел, то при блюре отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **ИНН**
  - тип: текстовое поле
  - значение по умолчанию: null
  - при блюре осуществляется валидация значения на кол-во символов - 10 или 12 чисел для ООО или ИП и если значение содержит не 10 или 12 чисел, то отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Электронная почта**
  - тип: текстовое поле
  - значение по умолчанию: null
  - обязательное поле
- **Отправка заявки**
  - тип: кнопка
  - логика работы описана в отдельной задаче
- **Условия передачи данных**
  - тип: кнопка
  - при клике на гиперссылку осуществляется скачивание файла по адресу, указанному в настройках блока

#### 2.4 При выборе в поле Вид заявки значения "Депозит" (Скрин 4)
- **Имя**
  - тип: текстовое поле
  - значение по умолчанию: null
  - если введен только 1 символ, то при блюре отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Телефон**
  - тип: числовое поле с маской ввода номера моб телефона с кодом +7
  - значение по умолчанию: null
  - если введено от 1 до 9 чисел, то при блюре отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Оправка заявки**
  - тип: кнопка
  - логика работы описана в отдельной задаче
- **Условия передачи данных**
  - тип: кнопка
  - при клике на гиперссылку осуществляется скачивание файла по адресу, указанному в настройках блока

#### 2.5 При выборе в поле Вид заявки значения "ВЭД" (Скрин 5)
- **Наименование организации**
  - тип: текстовое поле
  - значение по умолчанию: null
  - необязательное поле
- **ФИО**
  - тип: текстовое поле
  - значение по умолчанию: null
  - если введен только 1 символ, то при блюре отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Телефон**
  - тип: числовое поле с маской ввода номера моб телефона с кодом +7
  - значение по умолчанию: null
  - если введено от 1 до 9 чисел, то при блюре отображается ошибка "Некорректно заполненное поле"
  - обязательное поле
- **Электронная почта**
  - тип: текстовое поле
  - значение по умолчанию: null
  - необязательное поле
- **Валютный контроль**
  - тип: чекбокс
  - значение по умолчанию: false
- **Документарные операции**
  - тип: чекбокс
  - значение по умолчанию: false
- **Конверсионные операции**
  - тип: чекбокс
  - значение по умолчанию: false
- **Доп информация**
  - тип: текстовое поле
  - значение по умолчанию: null
  - обязательное поле
  - плейсхолдер: "Укажите интересующий Вас вопрос, место ведения бизнеса и удобное время для телефонного звонка"
- **Отправка данных**
  - тип: кнопка
  - логика работы описана в отдельной задаче
- **Условия передачи данных**
  - тип: кнопка
  - при клике на гиперссылку осуществляется скачивание файла по адресу, указанному в настройках блока

_Скрин 1. Вид блока при выборе варианты "Эквайринг" ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=16863%3A102307&t=HASJ6006FrWTk30q-4))_
![Image](https://user-images.githubusercontent.com/112703510/205039146-fc4ac025-0b4e-4838-aac0-46d56ef26a48.png)

_Скрин 2. Вид блока при выборе варианта "Кредит" ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=15743%3A88568&t=HASJ6006FrWTk30q-4))_
![Image](https://user-images.githubusercontent.com/112703510/205039308-30328141-b088-4f5d-9ba3-3569b64ac2ba.png)

_Скрин 3. Вид блока при выборе варианта "Бизнес-карта" ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=16491%3A117134&t=HASJ6006FrWTk30q-4))_
![Image](https://user-images.githubusercontent.com/112703510/205039616-f136768a-4ab9-4ec6-8150-44cf79a84848.png)

_Скрин 4. Вид блока при выборе варианта "Депозит" ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=16432%3A106500&t=HASJ6006FrWTk30q-4))_
![Image](https://user-images.githubusercontent.com/112703510/205038699-04a1604a-b445-484c-bb8f-7232f2db8191.png)

_Скрин 5. Вид блока при выборе варианта "ВЭД" ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=16640%3A118960&t=HASJ6006FrWTk30q-4))_
![Image](https://user-images.githubusercontent.com/112703510/205038850-c03321f7-0891-4972-b59a-94c7715f4b1b.png)

_Скрин 6. Настройки блока_
<img width="187" alt="Screenshot 2022-12-05 at 17 19 52" src="https://user-images.githubusercontent.com/112703510/205659562-93d7516d-d422-4152-a222-12bf4392c73b.png">

**Comment by SergeyPilipenko** [comment]
.3.52-beta проверено в даталайне
