### ISSUE TITLE
[Uni Blocks] Новый блок Галерея для бизнеса

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#912]
Необходимо реализовать новый блок с гелереей как показано на Скрине 1 ниже.

Для настройки блока нужны следующие поля (Скрин 2):

- **Заголовок блока**
  - название поля: "Заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок блока"
- Карточки
  - Карточка
    - **Заголовок карточки**
      - название поля: "Заголовок"
      - тип: текстовое поле
      - значение по умолчанию: "Заголовок карточки"
    - **Изображение**
      - можно загрузить свою картинку или выбрать иконку из списка
    - Список
      - Пункт 1
        - **Название пункта**
          - название поля: "Название"
          - тип: текстовое поле
          - значение по умолчанию: "Заголовок 1"
        - **Описание пункта**
          - название поля: "Описание"
          - тип: текстовое поле
          - значение по умолчанию: "Описание 1"
      - Пункт 2
        - **Название пункта**
          - название поля: "Название"
          - тип: текстовое поле
          - значение по умолчанию: "Заголовок 2"
        - **Описание пункта**
          - название поля: "Описание"
          - тип: текстовое поле
          - значение по умолчанию: "Описание 2"
  - **Добавить карточку**
    - тип: кнопка
    - при клике добавляются поля подраздела Карточка для заполнения новой карточки
- Стиль
  - ширина блока не может быть < 12 колонок

Логика работы галереи:
- "стрелка" справа отображается, если есть последующие карточки
- "стрелка" слева отображается, если есть предыдущие карточки
- галерея не зациклена
- при клике на "стрелку" пролистывается сразу 2 карточки, т.е. если мы видим изначально 1ю и 2ю карточки, то при нажатии на "стрелку" вправо увидим 3ю и 4ю карточки (если карточек > 3)

_Скрин 1. Вид блока_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=17078%3A110846&t=mUtFjTHySPC9PU35-4))
![Image](https://user-images.githubusercontent.com/112703510/205104140-cba1a1ae-2c3f-48f3-9b8e-1e61c1f2c631.png)

_Скрин 2. Настройки блока_
![Image](https://user-images.githubusercontent.com/112703510/205104191-d4fc9435-34b4-4592-9549-ccd5b601bde2.png)

**Comment by Guzlik123** [comment]
2.3.51-beta

1. Поменять дефолтные значения списков на Заголовок 1, Заголовок 2, Заголовок 3, сейчас Ячейка 1-1, Ячейка 1-2, Ячейка 1-3
2. При наличии >3 карточек при нажатии на кнопку вправо(влево) должно скролить по 2 карточки, сейчас скролит по 1

**Comment by Longraf** [comment]
Откуда требование пролистывания 2-х карточек за рад ? Мы вроде когда обсуждали карусель отказались от пролистывания по несколько карточек за раз т.к. пролистывание основано на дефолтноим скролинге браузера

**Comment by klapada** [comment]
Пролистывание 2х карточек было из-за наличия точек внизу карусели. Их сейчас нет, поэтому оставляем пролистывание по одной карточке, как сейчас реализовано.

**Comment by Guzlik123** [comment]
2.3.53-beta

Исправлено
