### ISSUE TITLE
[Uni Blocks] Новый блок Видео

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#933]
Добавить новый блок Видео для возможности добавления видеоконтента на страницу.

Для настройки блока нужны следующие поля:
- **Заголовок блока**
  - название поля: "Заголовок"
  - тип: текстовое поле
  - значение по умолчанию: "Заголовок блока"
- **Ссылка на видео**
  - название поля: "URL"
  - тип: текстовое поле
  - значение по умолчанию: null
- **Заставка в блоке**
  - можно загрузить картинку и добавить в качестве заставки видео
- **Стили**
  - ширину блока нельзя сделать < 3 колонок

_Скрин 1. Вид блока_ ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=14783%3A192243&t=vxDBkSc0JPuBd0CX-4))
![Image](https://user-images.githubusercontent.com/112703510/205859638-84d3a6bf-22c3-43fe-a656-14ba75dc6aa4.png)

_Скрин 2. Настройки блока_
![Image](https://user-images.githubusercontent.com/112703510/205861048-32360e7b-d01e-4fae-9085-aeee4ee47b14.png)

**Comment by Mikage777** [comment]
Задача связанная с https://github.com/redneckz/temp_wcms/issues/551

**Comment by Guzlik123** [comment]
2.3.44-beta

Проверено
