### ISSUE TITLE
[Uni Blocks] Доработка блока Бонусов и преимуществ (BonusBenefitsBlock)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#936]
В настройках блока BonusBenefitsBlock внести следующее изменение:
- в поле "Количество элементов с строке" в дропдауне добавить еще один вариант - "Три колонки", при выборе которого расположение элементов как на Скрине ниже.

_Скрин. Вид блока, если выбран вариант "Три колонки"_ ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=14783%3A192950&t=vxDBkSc0JPuBd0CX-4))
![Image](https://user-images.githubusercontent.com/112703510/206118604-29b28a0a-8212-4726-b189-4c25b05b92ba.png)

**Comment by SergeyPilipenko** [comment]
проверено в ип2.0
