### ISSUE TITLE
[Uni Blocks] Доработка Продуктовой плитки (ProductTile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#940]
Необходимо в настройках блока ProductTile добавить новое поле для выбора вида контента (Скрин 1):
  - название поля: "Вид преимуществ"
  - тип: дропдаун
  - возможные значения:
    - Стандартный
    - Индивидуальный
  - значение по умолчанию: "Стандартный"
  - при выборе значения "Стандартный" есть возможность добавить **Название** и **Описание** для каждого преимущества, как сейчас реализовано (Скрин 1)
  - при выборе значения "Индивидуальный" становится доступно одно поле с возможностью форматирования (Скрин 2):
    - тип: текстовое поле
    - значение по умолчанию: "Преимущество" (шрифт и размер текста как на выделенном фрагменте на Скрине 3)

![Image](https://user-images.githubusercontent.com/112703510/206144089-5ee0da02-7516-4c1d-acf0-ddf844fc317d.png)
_Скрин 1. Настройки блока по умолчанию_

---

![Image](https://user-images.githubusercontent.com/112703510/206144140-efcd4cd9-9242-4856-9b8b-1224351fe855.png)
_Скрин 2. Настройки блока при выборе ввода преимуществ в индивидуальном формате_

---

![Image](https://user-images.githubusercontent.com/112703510/205941862-5e669ed0-5566-4370-9a27-276b2096d522.png)
_Скрин 3. Блок с выделенным текстом по умолчанию_ ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=14788%3A169534&t=vxDBkSc0JPuBd0CX-4))

**Comment by Mikage777** [comment]
возможность форматирования текста, ее реализацию можно взять из задачи https://github.com/redneckz/wildless-cms-uni-blocks/issues/909

**Comment by klapada** [comment]
Реализация в рамках задачи https://github.com/redneckz/wildless-cms-uni-blocks/issues/909
