### ISSUE TITLE
[Uni Blocks] Новый блок для фильтрации блоков по выбранным параметрам

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#960]
### 1. Необходимо реализовать блок как на _Скрине 1-2_:
- в блок можно вложить другие блоки (пока только Продуктовые плитки)
- вложенные продуктовые плитки можно сворачивать/разворачивать (кол-во отображаемых плиток задается в настройках блока)
- у вложенных продуктовых плиток можно проставить флаги по заданным в блоке Фильтры параметрам для возможности фильтрации по ним (указать сумму "от", задать сроки "от" и "до", проставить флаги по параметрам)
  - например в род. блоке было добавлено **Параметр в группе** = Рубль, а также чекбокс **Сумма вклада** = true и **Срок вклада** = true, то у вложенных продуктовых плиток в настройках появятся следующие поля:
    - поле "Рубль"
      - компонент: чекбокс
      - значение по умолчанию: false
    - поле "Сумма вклада "от""
      - компонент: числовое поле
      - значение по умолчанию: null
      - в поле указывается мин сумма вклада
    - поле "Срок вклада "от" в мес"
      - компонент: числовое поле
      - единица изменения: мес
      - значение по умолчанию: null
      - в поле указывается мин срок вклада в месяцах
    - поле "Срок вклада "до" в мес"
      - компонент: числовое поле
      - единица изменения: мес
      - значение по умолчанию: null
      - в поле указывается макс срок вклада в месяцах

### 2. Для настройки блока нужны следующие поля (Скрин 3):
- **Отображение заданного количества строк**
  - название поля: "Отображать заданное количества строк"
  - компонент: числовое поле
  - значение по умолчанию: null
  - если в поле пусто, то "плашка" для разворачивания/сворачивания не отображается
  - если в поле значение = 0, то все плитки сворачиваются/разворачиваются
  - если в поле значение > 0, то указанное кол-во плиток будет отображаться всегда независимо от того, свернут ли блок или развернут
- **Сумма вклада**
  - название поля: "Сумма"
  - компонент: чекбокс
  - возможные значения:
    - true (= в блоке отображается поле **Сумма**)
    - false (= в блоке не отображается поле **Сумма**)
  - значение по умолчанию: true
- **Срок вклада**
  - название поля: "Срок"
  - компонент: чекбокс
  - возможные значения:
    - true (= в блоке отображается поле **Срок**)
    - false (= в блоке не отображается поле **Срок**)
  - значение по умолчанию: true
- Группы параметров
  - Группа
    - **Название группы**
      - название поля: "Название"
      - компонент: текстовое поле
      - значение по умолчанию: "Название группы"
    - **Тип группы**
      - название поля: "Тип"
      - компонент: дропдаун
      - возможные значения:
        - Одиночный выбор
        - Множественный выбор
      - значение по умолчанию: "Одиночный выбор"
      - при выборе значения "Одиночный выбор" в данной группе в блоке можно будет выбрать только один параметр
      - при выборе значения "Множественный выбор" в данной группе в блоке можно будет выбрать несколько параметров
    - **Параметр в группе**
      - название поля: "Параметр"
      - компонент: текстовое поле
      - значение по умолчанию: "Параметр"
    - **Добавить параметр**
      - компонент: кнопка
      - при клике добавляется пустое текстовое поле для создания нового параметра
    - **Удалить параметр**
      - компонент: кнопка
      - при клике поле удаляется
      - удаление доступно, если параметров > 1
    - **Переместить параметр**
      - компонент: кнопка
      - при клике значения полей меняются местами
      - перемещение доступно, если параметров > 1
  - **Добавить группу**
    - компонент: кнопка
    - при клике добавляется новый подраздел Группа с полями
    - добавить можно макс 4 группы 
  - **Удалить группу**
    - компонент: кнопка
    - при клике подраздел Группа с полями удаляется
  - **Переместить группу**
    - компонент: кнопка
    - при клике подразделы Группы меняются местами
    - перемещение доступно, если групп > 1
- Кнопки
  - Кнопка
    - **Текст**
      - тип: текстовое поле
      - значение по умолчанию: "Кнопка"
    - **Цвет кнопки**
      - тип: дропдаун
      - значение по умолчанию: "Основной"
  - Кнопка
    - **Текст**
      - тип: текстовое поле
      - значение по умолчанию: "Очистить фильтры"
    - **Цвет кнопки**
      - тип: дропдаун
      - значение по умолчанию: "Второстепенный"
- Стиль
  - ширину блока нельзя сделать < 12 колонок

### 3. Логика работы блока и полей в нем:
- **Сумма** (п.1 на _Скрине 1_)
  - тип: числовое поле
  - значение по умолчанию: 1000
  - плейсхолдер: "От 500 р"
  - если введено значения < 500р, то при блюре подставлять значение = 500
- **Срок** (п.2 на _Скрине 1_)
  - тип: слайдер
  - единица измерения: месяцы
  - мин значение = 3
  - макс значение = 24
  - шаг: 1
  - значение по умолчанию: 18
- Группа (п.3 на _Скрине 1_)
  - название группы параметров, созданная в настройках блока в поле **Название группы**
- Параметры (п.4 на _Скрине 1_)
  - указываются названия параметров, созданные в настройках блока в полях **Параметр в группе**
  - у всех параметров значение по умолчанию: false
- **Подобрать**
  - тип: кнопка
  - при клике осуществляется подбор и отображение вкладов, которые подходят под заданные параметры
  - продуктовая плитка отображается, если по всем выбранным значениям в фильтре у нее стоит true в настройках, включая попадание в диапазон по сумме и сроку (если данные поля отображаются в блоке Фильтры)
- **Очистить фильтры**
  - тип: кнопка
  - при клике все фильтры сбрасываются до значений по умолчанию

![Image](https://user-images.githubusercontent.com/112703510/208631130-9d8c5d4f-697f-41fa-b682-bc1e743ceb43.png)
_Скрин 1. Вид блока с полями для суммы и срока_ ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=7991%3A166921&t=RcW45iUf7ggyN0GE-4))

---

![Image](https://user-images.githubusercontent.com/112703510/208632213-b2089718-1d2d-4043-a5d1-fcacb980acb2.png)
*Скрин 2. Вид блока без полей для суммы и срока* ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=20027%3A171007&t=8fiEg5mPwI57DDVs-4))

---

![Image](https://user-images.githubusercontent.com/112703510/208631211-5db09acc-df48-4d9e-ac8d-a5266869111e.png)
_Скрин 3. Настройки блока_

**Comment by Mikage777** [comment]
Необходимо продумать систему наполнения тегами

**Comment by klapada** [comment]
Обсудили с Владом и Сашей и зафиксировали следующее:

1) Кнопка для сворачивания/разворачивания продуктовых плиток:
    - задавать количество показываемых по умолчанию продуктовых плиток, а не строк
    - если при фильтрации кол-во продуктовых плиток, соответствующих выбранным параметрам <= кол-ву заданных по умолчании, то кнопка становится disabled
    - пользователь сам регулирует открытие/скрытие продуктовых плиток
2) Продуктовые плитки, не соответствующие выбранным параметрам, совсем убираем

**Comment by klapada** [comment]
Для случаев, когда под выбранные критерии ничего не подходит, вид блока как на Скрине ниже ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=24586%3A180284&t=Pe6Wty0WOQgjZagv-4))
<img width="688" alt="Screenshot 2023-01-26 at 18 32 21" src="https://user-images.githubusercontent.com/112703510/214878330-89991eed-fe3c-4d2e-aa94-2c0a81c81036.png">

**Comment by vladeiko** [comment]
В рамках первой итерации решено было добавить только ипотечный блок фильтрации.
При необходимости добавления новых блоков фильтрации, создать новый тикет и использовать текущий как пример.

**Comment by SergeyPilipenko** [comment]
2.3.51-beta првоерено в даталайне

**Comment by Longraf** [comment]
Согласовал с Ксенией и Эльдаром что картинка для всех подобных мест будет единой + картинка упрощена до обычной лупы макет прикладываю [МАКЕТ](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?type=design&node-id=28863-229437&t=crWDWsS5mD0gG04e-11)
