### ISSUE TITLE
[Uni Blocks] Возможность изменения расположения картинки в Продуктовой плитке (ProductTile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#963]
Необходимо доработать ProductTile, чтобы можно было изменять расположение картинки и ставить ее не только справа, но и слева как на *Скрине 1* ниже.

В настройках блока добавить новое поле (*Скрин 2*):
- название поля: "Картинка справа/текст слева"
- компонент: чекбокс
- тип: boolean 
- возможные значения:
  - true (= картинка располагается справа от текста)
  - false (= картинка находится слева от текста)
- значение по умолчанию: true

![Image](https://user-images.githubusercontent.com/112703510/207055631-95b05554-75af-4a24-bf13-f06e4c1407d6.png)
![Image](https://user-images.githubusercontent.com/112703510/207055653-4cc7d84b-f0fe-4c4f-b0f5-cbd75b57c001.png)
*Скрин 1. Вид блока с картинкой слева* ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=16615%3A201591&t=QeyS3VqaEei9mvvI-4))

![Image](https://user-images.githubusercontent.com/112703510/207064985-5f9b824a-d7cc-458c-aa09-da0c3a4e4f85.png)
_Скрин 2. Настройки блока_

**Comment by Guzlik123** [comment]
2.3.44-beta

Проверено
