### ISSUE TITLE
[Uni Blocks] Доработка Плитки (Tile)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#973]
Необходимо в настройках Tile внести следующие изменения:

1. Добавить новое поле для изменения размера текста в поле **Описание** (_Скрин_)
    - название поля: "Размер описания"
    - компонент: дропдаун
    - возможные значения:
      - XL_L (=18px)
      - XL_R (=18px)
      - L_L (=16px)
      - L_R (=16px)
    - значение по умолчанию: XL_L

2. Добавить новое поле для изменения расположения картинки (_Скрин_):
    - название поля: "Картинка справа/текст слева"
    - компонент: чекбокс
    - тип: boolean
    - возможные значения:
      - true (= картинка располагается справа от текста)
      - false (= картинка находится слева от текста)
    - значение по умолчанию: true

![Image](https://user-images.githubusercontent.com/112703510/207576842-3b123719-cb50-4c16-b6d7-d559ef94f2d1.png)
*Скрин. Новые поля в настройках блока*

**Comment by klapada** [comment]
Возможность форматирования текста, ее реализацию можно взять из задачи https://github.com/redneckz/wildless-cms-uni-blocks/issues/909

**Comment by klapada** [comment]
В данной задаче п.1 пока неактуален, сделать нужно только п.2.

**Comment by SergeyPilipenko** [comment]
2.3.52-beta проверено в даталайне
