### ISSUE TITLE
[Uni Blocks] Доработка Продуктового блока в части расположения картинки (ProductBlock)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#974]
Необходимо в настройках ProductBlock добавить новое поле для изменения расположения картинки в блоке (_Скрин 2_)
- название поля: "Картинка справа/текст слева"
- компонент: чекбокс
- тип: boolean
- возможные значения:
  - true (= картинка располагается справа от текста) (Скрин 1 верхняя картинка)
  - false (= картинка находится слева от текста) (Скрин 1 нижняя картинка)
- значение по умолчанию: true

![Image](https://user-images.githubusercontent.com/112703510/207586841-4c39d6f3-1aa0-4d90-8233-a84afda1cd5b.png)

![Image](https://user-images.githubusercontent.com/112703510/207586864-9788fe6c-9cd7-4d63-b43b-2c3d3bf8959a.png)
*Скрин 1. Вид блока с текстом ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=16410%3A184128&t=AI2LQS52Uy7O3Lcu-4))*

---

![Image](https://user-images.githubusercontent.com/112703510/207591293-1ba83084-4c7b-414a-af61-6f7f281bbeb3.png)
*Скрин 2. Новое поле для изменения расположения картинки*

**Comment by klapada** [comment]
Возможность форматирования текста, ее реализацию можно взять из задачи https://github.com/redneckz/wildless-cms-uni-blocks/issues/909

**Comment by SergeyPilipenko** [comment]
2.3.51-beta проверено в даталайне
