### ISSUE TITLE
[Uni Blocks] Доработка блока Калькулятор (Calculator)

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#978]
Необходимо доработать блок Calculator, добавив новый калькулятор вкладов для бизнеса как на _Скрине 1_ ниже.

#### 1. В настройках блока внести следующие изменения:
- Добавить в дропдаун выбора вида калькулятора новое значение = "Калькулятор вкладов - Бизнес"
- При выборе значения "Калькулятор вкладов - Бизнес" помимо текущих полей выводятся также 2 новых (_Скрин 2_):
  - **Сноска в самом низу блока**
    - название поля: "Сноска снизу блока"
    - компонент: текстовое поле
    - значение по умолчанию: null
  - **Название депозита**
    - название поля: "Показывать название депозита"
    - компнент: чекбокс
    - тип данных: boolean
    - возможные значения:
      - true (=выводить название депозита)
      - false (=название депозита не отображается)
    - значение по умолчанию: false

#### 2. Логика работы полей в калькуляторе:
- **Сумма**
  - компонент: слайдер
  - единица измерения: рубли
  - мин значение: наименьшее значение суммы из справочника (например 1000)
  - макс значение: наибольшее значение суммы из справочника (например 500 000)
  - значение по умолчанию: 100 000
- **Срок**
  - компонент: слайдер
  - единица измерения: дни
  - мин значение: 1
  - макс значение: 1095
  - значение по умолчанию: 90
  - если **Пополнение** и/или **Частичное снятие** = true, то:
    - мин значение = 90
    - макс значение = 730
  - если выбрано значение от 1 до 30 дней вкл, то вместо ставки отображается картинка и подсказка как на _Скрине 3_
- **Ставка**
  - если **Являюсь малым предприятием** = false, то значение ставки берется из справочника для бизнеса
  - если **Являюсь малым предприятием** = true, то значение ставки берется из справочника для ИП
- **Название депозита**
  - отображается, если в настройках блока значение поля **Название депозита** = true
  - выводится "Депозит "Стабильный"", если:
    - **Пополнение**=false и **Частичное снятие**=false
  - выводится "Депозит "Оперативный"", если:
    - **Пополнение**=true и **Частичное снятие**=false
    - **Пополнение**=false и **Частичное снятие**=true
    - **Пополнение**=true и **Частичное снятие**=true
- **Доход в конце срока**
  - рассчитывается по формуле: **Сумма** * **Ставка** / 100 / 365 * **Срок**
- **Сумма в конце срока**
  - рассчитывается по формуле: **Сумма** + **Доход в конце срока**
- **Пополнение**
  - компонент: чекбокс
  - значение по умолчанию: false
  - становится недоступно, если:
    - 0<**Срок**<90 ИЛИ
    - 730<**Срок**<1096
- **Частичное снятие**
  - компонент: чекбокс
  - значение по умолчанию: false
  - становится недоступно, если:
    - 0<**Срок**<90 ИЛИ
    - 730<**Срок**<1096
- **Являюсь малым предприятием**
  - компонент: чекбокс
  - значение по умолчанию: false
- **Выплата процентов**
  - Ежемесячно
    - компонент: радио
    - значение по умолчанию: false
  - В конце срока
    - компонент: радио
    - значение по умолчанию: true
- **Оформление**
  - компонент: кнопка
  - при клике осуществляется переход на страницу, указанный в поле "URL" в подразделе "Кнопки"

![Image](https://user-images.githubusercontent.com/112703510/205291120-eae87d2a-7c6b-4b4d-87de-f954dd82cda1.png)
_Скрин 1. Вид блока_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=15972%3A107000&t=d55UxNnsrGyildjG-4))

---

![Image](https://user-images.githubusercontent.com/112703510/208072705-7391c06a-4dc0-4f84-9e53-5c5ba72c39f8.png)
_Скрин 2. Выбор калькулятора "Калькулятор вкладов - Бизнес"_

---

![Image](https://user-images.githubusercontent.com/112703510/208380525-ee5678b2-e1e8-49c4-8339-a25e631948a1.png)
_Скрин 3. Вывод подсказки, если выбран срок 1-30_ ([макет](https://www.figma.com/file/3Ra9wCUtQJZKulrP3PN4bO/%E2%AD%90%EF%B8%8F-RSHB---%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=18265%3A118815&t=N1vlULEdTV8viWzp-4))

**Comment by Mikage777** [comment]
За основу можно взять "Вклады"

**Comment by klapada** [comment]
Небольшая корректировка: по полю **Срок** мин и макс значение берется из справочника и зависит от вида депозита ("Стабильный" или "Оперативный") и от значения в поле **Являюсь малым предприятием**
