### ISSUE TITLE
[Uni Blocks] Новый блок с информацией о представительстве

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#980]
#### 2. Для настройки блока нужны следующие поля (_Скрин 2_):
- **Заголовок блока**
  - название поля: "Заголовок"
  - компонент: текстовое поле
  - значение по умолчанию: "Заголовок"
- **Описание блока**
  - название поля: "Описание"
  - компонент: текстовое поле с возможностью форматирования
  - значение по умолчанию: "Описание"
- **Адрес**
  - название поля: "Адрес"
  - компонент: текстовое поле
  - значение по умолчанию: null
- **Телефон (факс)**
  - название поля: "Телефон (факс)"
  - компонент: текстовое поле
  - значение по умолчанию: null
- **E-mail**
  - название поля: "E-mail"
  - компонент: текстовое поле
  - значение по умолчанию: null
- **Изображение**
  - можно загрузить свою картинку или выбрать иконку из списка
- Кнопка
  - **Текст**
    - компонент: текстовое поле
    - значение по умолчанию: "Информация о регионе"
  - **URL**
    - компонент: текстовое поле
    - значение по умолчанию: null
  - **Таргет**
    - компонент: дропдаун
    - значение по умолчанию: null
- Стили
  - ширина блока = 6 колонкам (col-span-6)
  - изменить ширину блока нельзя

![Image](https://user-images.githubusercontent.com/112703510/207889374-6fbef2c5-0e39-40c6-a196-eb6c41a97b15.png)
*Скрин 1. Вид блока ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=17180%3A165890&t=yRVCEaCsKhef9qic-4))*

---

![Image](https://user-images.githubusercontent.com/112703510/207889443-42ad528f-19c3-4ce5-b4e2-7e489f92a49d.png)
*Скрин 2. Настройки блока*

**Comment by klapada** [comment]
Возможность форматирования текста, ее реализацию можно взять из задачи https://github.com/redneckz/wildless-cms-uni-blocks/issues/909

**Comment by SergeyPilipenko** [comment]
2.3.52-beta проверено в даталайне
