### ISSUE TITLE
[Uni Blocks] Доработка Rich Text для выбора вида таблицы

### ISSUE THREAD

**Issue by klapada** [redneckz/wildless-cms-uni-blocks#990]
Необходимо доработать Rich Text, чтобы была возможность выбора вида таблицы.
- **Выбор вида таблицы**
  - название поля: “Вид таблицы”
  - компонент: дропдаун
  - возможные значения:
    - Горизонтальные разделители
    - Строки разного цвета
  - значение по умолчанию: "Горизонтальные разделители"
  - при выборе значения "Горизонтальные разделители" при добавлении таблицы она будет выглядеть как на _Скрине 1_
  - при выборе значения "Строки разного цвета" при добавлении таблицы она будет выглядеть как на _Скрине 2_

![Image](https://user-images.githubusercontent.com/112703510/208113073-84c8919c-d542-4619-9608-8a5fe675c17b.png)
*Скрин 1. Вид таблицы при выборе варианта "Горизонтальные разделители" ([макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=16922%3A182426&t=OkFOTwOH6mW8nNhw-4))*

![Image](https://user-images.githubusercontent.com/112703510/214515436-80738d91-e153-47d4-9384-12c1f86c8eff.png)
_[Макет](https://www.figma.com/file/a7irArFEdYTFohnJsxky0Q/%E2%AD%90%EF%B8%8F-RSHB---%D0%9E-%D0%91%D0%B0%D0%BD%D0%BA%D0%B5?node-id=18538%3A180782&t=ENlXplZR1u9Ikqoe-4)_

---

![Image](https://user-images.githubusercontent.com/112703510/208113707-4c889894-ff47-4637-97fc-75f83c0e5763.png)
*Скрин 2. Вид таблицы при выборе варианта "Строки разного цвета" ([макет](https://www.figma.com/file/npQlLUs3VVMgZ5FTENEfZx/%E2%AD%90%EF%B8%8F-RSHB---%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC?node-id=14783%3A173211&t=ve4zGk7WhxkFnG0p-4))*

**Comment by klapada** [comment]
Возможность форматирования текста, ее реализацию можно взять из задачи https://github.com/redneckz/wildless-cms-uni-blocks/issues/909

**Comment by Longraf** [comment]
"Полосатая" таблица залито в main

**Comment by SergeyPilipenko** [comment]
2.3.53-beta проверено в даталайне
