### ISSUE TITLE
[Uni Blocks] Рефаторинг типографики. Блок BenefitsBlock

### ISSUE THREAD

**Issue by vladeiko** [redneckz/wildless-cms-uni-blocks#995]
**Прошу обратить внимание на то, что вместо `text-m-light` используется `size="text-m"` и `font="font-light"`. Позже все свойства текста с приставкой `light` будут удалены из конфига**

# Рефакторинг типографики.

## Обновления

Недавно в репозитории uni blocks произошло обновление, связанное с типографикой.
Были добавлены компоненты в `ui-kit`:
- Text
- Paragraph

`Paragraph` является уточнением компонента `Text`.

## Семантика

Для того, чтобы понять какой из компонентов использовать недостаточно проанализировать код и начать вносить изменения. Необходимо посмотреть на уже существующий блок и выявить его составляющие.

На примере блока `Accordion`:

![Image](https://user-images.githubusercontent.com/46086126/208405761-ba714e3c-0b9c-4ec8-9e33-e88891d44a78.png)

Например, в `InvestmentGallery` следует использовать `Text`, т.к. содержимое внутри каждой карточки - это таблица:

![Image](https://user-images.githubusercontent.com/46086126/208407054-7bd7b042-580a-4591-b2b4-a9e638288824.png)

Внутрь ячеек таблицы (которые могут быть либо `<div>`, либо `<td>` необходимо вкладывать компонент `<Text>`

## Как вносить изменения в код

Основные принципы:
- Текст (`Text` или `Paragraph`) несёт в себе только типографику (размер шрифта, отступы, толщина линий, text alignment)
- Позиционирование осуществляется при помощи оборачивания в другой тег, которому задаются `margin`, `padding`, `width` и т.д.
- **НЕ ИСПОЛЬЗОВАТЬ `size` с приставкой `light` вместо этого использовать свойство `font`**

#### Пример 1

Было:

```html
        <div className="mb-5 text-m-light text-center">{description}</div>
```

Стало:

```html
        <div className="mb-5">
          <Paragraph size="text-m" font="font-light" align="text-center">
            {description}
          </Paragraph>
        </div>
```

#### Пример 2

Было:

```html
    <span className="text-xl font-medium pr-2.5">{label}</span>
```

Стало:

```html
    <Text size="text-xl" font="font-medium">
      {label}
    </Text>
```

**Comment by AlexsaTasara** [comment]
Рефакторинг не требуется
